import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'inputWidth', type: 'value', variations: ['size'], params: { web: ['inputWidth'] } },
    { name: 'tooltipColor', type: 'color', variations: ['hintView'], params: { web: ['tooltipColor'] } },
    { name: 'tooltipArrowBackground', type: 'color', variations: ['hintView'], params: { web: ['tooltipArrowBackground'] } },
    { name: 'tooltipTextStyle', type: 'typography', variations: ['hintSize'], params: { web: ['tooltipTextFontFamily', 'tooltipTextFontSize', 'tooltipTextFontStyle', 'tooltipTextFontWeight', 'tooltipTextFontLetterSpacing', 'tooltipTextFontLineHeight'] } },
    { name: 'tooltipArrowMaskImage', type: 'value', variations: ['hintSize'], params: { web: ['tooltipArrowMaskImage'] } },
    { name: 'helpersBackgroundColorActive', type: 'color', variations: ['view'], params: { web: ['helpersBackgroundColorActive'] } },
    { name: 'helpersBackgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['helpersBackgroundColorFocus'] } },
    { name: 'inputColor', type: 'color', variations: ['view'], params: { web: ['inputColor'] } },
    { name: 'inputCaretColor', type: 'color', variations: ['view'], params: { web: ['inputCaretColor'] } },
    { name: 'placeholderColor', type: 'color', variations: ['view'], params: { web: ['placeholderColor'] } },
    { name: 'placeholderColorFocus', type: 'color', variations: ['view'], params: { web: ['placeholderColorFocus'] } },
    { name: 'leftHelperColor', type: 'color', variations: ['view'], params: { web: ['leftHelperColor'] } },
    { name: 'rightHelperColor', type: 'color', variations: ['view'], params: { web: ['rightHelperColor'] } },
    { name: 'rightContentColor', type: 'color', variations: ['view'], params: { web: ['rightContentColor'] } },
    { name: 'rightContentColorHover', type: 'color', variations: ['view'], params: { web: ['rightContentColorHover'] } },
    { name: 'rightContentColorActive', type: 'color', variations: ['view'], params: { web: ['rightContentColorActive'] } },
    { name: 'indicatorColor', type: 'color', variations: ['view'], params: { web: ['indicatorColor'] } },
    { name: 'optionalColor', type: 'color', variations: ['view'], params: { web: ['optionalColor'] } },
    { name: 'scrollbarThumbBackgroundColor', type: 'color', variations: ['view'], params: { web: ['scrollbarThumbBackgroundColor'] } },
    { name: 'scrollbarThumbBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['scrollbarThumbBackgroundColorHover'] } },
    { name: 'scrollbarThumbBackgroundColorActive', type: 'color', variations: ['view'], params: { web: ['scrollbarThumbBackgroundColorActive'] } },
    { name: 'scrollbarTrackBackgroundColor', type: 'color', variations: ['view'], params: { web: ['scrollbarTrackBackgroundColor'] } },
    { name: 'scrollbarTrackBackgroundColorActive', type: 'color', variations: ['view'], params: { web: ['scrollbarTrackBackgroundColorActive'] } },
    { name: 'scrollbarTrackBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['scrollbarTrackBackgroundColorHover'] } },
    { name: 'dividerColor', type: 'color', variations: ['view'], params: { web: ['dividerColor'] } },
    { name: 'labelInnerStyle', type: 'typography', variations: ['size'], params: { web: ['labelInnerFontFamily', 'labelInnerFontSize', 'labelInnerFontStyle', 'labelInnerFontWeight', 'labelInnerLetterSpacing', 'labelInnerLineHeight'] } },
    { name: 'inputStyle', type: 'typography', variations: ['size'], params: { web: ['inputFontFamily', 'inputFontSize', 'inputFontStyle', 'inputFontWeight', 'inputLetterSpacing', 'inputLineHeight'] } },
    { name: 'helpersStyle', type: 'typography', variations: ['size'], params: { web: ['helpersFontFamily', 'helpersFontSize', 'helpersFontStyle', 'helpersFontWeight', 'helpersLetterSpacing', 'helpersLineHeight'] } },
    { name: 'titleCaptionColorReadOnly', type: 'color', params: { web: ['titleCaptionColorReadOnly'] } },
    { name: 'hintMargin', type: 'value', variations: ['size'], params: { web: ['hintMargin'] } },
    { name: 'helpersPaddingRight', type: 'dimension', variations: ['size'], params: { web: ['helpersPaddingRight'] } },
    { name: 'helpersPaddingBottom', type: 'dimension', variations: ['size'], params: { web: ['helpersPaddingBottom'] } },
    { name: 'helpersPaddingLeft', type: 'dimension', variations: ['size'], params: { web: ['helpersPaddingLeft'] } },
    { name: 'helpersOffset', type: 'dimension', variations: ['size'], params: { web: ['helpersOffset'] } },
    { name: 'rightContentTop', type: 'dimension', variations: ['size'], params: { web: ['rightContentTop'] } },
    { name: 'rightContentRight', type: 'dimension', variations: ['size'], params: { web: ['rightContentRight'] } },
    { name: 'rightContentHeight', type: 'dimension', variations: ['size'], params: { web: ['rightContentHeight'] } },
    { name: 'labelMarginBottom', type: 'dimension', variations: ['size'], params: { web: ['labelMarginBottom'] } },
    { name: 'labelInnerTop', type: 'dimension', variations: ['size'], params: { web: ['labelInnerTop'] } },
    { name: 'inputBackgroundColor', type: 'color', variations: ['view'], params: { web: ['inputBackgroundColor'] } },
    { name: 'inputBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['inputBackgroundColorHover'] } },
    { name: 'inputBackgroundColorActive', type: 'color', variations: ['view'], params: { web: ['inputBackgroundColorActive'] } },
    { name: 'inputBackgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['inputBackgroundColorFocus'] } },
    { name: 'helpersBackgroundColor', type: 'color', variations: ['view'], params: { web: ['helpersBackgroundColor'] } },
    { name: 'helpersBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['helpersBackgroundColorHover'] } },
    { name: 'inputColorFocus', type: 'color', variations: ['view'], params: { web: ['inputColorFocus'] } },
    { name: 'dividerColorHover', type: 'color', variations: ['view'], params: { web: ['dividerColorHover'] } },
    { name: 'dividerColorFocus', type: 'color', variations: ['view'], params: { web: ['dividerColorFocus'] } },
    { name: 'titleCaptionColor', type: 'color', variations: ['view'], params: { web: ['titleCaptionColor'] } },
    { name: 'hintIconColor', type: 'color', variations: ['view'], params: { web: ['hintIconColor'] } },
    { name: 'titleCaptionStyle', type: 'typography', variations: ['size'], params: { web: ['titleCaptionFontFamily', 'titleCaptionFontSize', 'titleCaptionFontStyle', 'titleCaptionFontWeight', 'titleCaptionLetterSpacing', 'titleCaptionLineHeight'] } },
    { name: 'tooltipBackgroundColor', type: 'color', variations: ['hintView'], params: { web: ['tooltipBackgroundColor'] } },
    { name: 'tooltipBoxShadow', type: 'shadow', variations: ['hintView'], params: { web: ['tooltipBoxShadow'] } },
    { name: 'inputHeight', type: 'dimension', variations: ['size'], params: { web: ['inputHeight'] } },
    { name: 'inputMinHeight', type: 'dimension', variations: ['size'], params: { web: ['inputMinHeight'] } },
    { name: 'inputPaddingTop', type: 'dimension', variations: ['size'], params: { web: ['inputPaddingTop'] } },
    { name: 'inputPaddingRight', type: 'dimension', variations: ['size'], params: { web: ['inputPaddingRight'] } },
    { name: 'inputPaddingRightWithRightContent', type: 'dimension', variations: ['size'], params: { web: ['inputPaddingRightWithRightContent'] } },
    { name: 'inputPaddingBottom', type: 'dimension', variations: ['size'], params: { web: ['inputPaddingBottom'] } },
    { name: 'inputPaddingLeft', type: 'dimension', variations: ['size'], params: { web: ['inputPaddingLeft'] } },
    { name: 'helpersPaddingTop', type: 'dimension', variations: ['size'], params: { web: ['helpersPaddingTop'] } },
    { name: 'indicatorSizeInner', type: 'dimension', variations: ['size'], params: { web: ['indicatorSizeInner'] } },
    { name: 'indicatorSizeOuter', type: 'dimension', variations: ['size'], params: { web: ['indicatorSizeOuter'] } },
    { name: 'indicatorLabelPlacementHintOuterRight', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementHintOuterRight'] } },
    { name: 'scrollbarWidth', type: 'dimension', variations: ['size'], params: { web: ['scrollbarWidth'] } },
    { name: 'scrollbarBorderWidth', type: 'dimension', variations: ['size'], params: { web: ['scrollbarBorderWidth'] } },
    { name: 'hintTargetSize', type: 'dimension', variations: ['size'], params: { web: ['hintTargetSize'] } },
    { name: 'titleCaptionInnerLabelOffset', type: 'dimension', variations: ['size'], params: { web: ['titleCaptionInnerLabelOffset'] } },
    { name: 'tooltipPaddingBottom', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingBottom'] } },
    { name: 'hintInnerLabelPlacementOffset', type: 'dimension', variations: ['size'], params: { web: ['hintInnerLabelPlacementOffset'] } },
    { name: 'inputColorReadOnly', type: 'color', params: { web: ['inputColorReadOnly'] } },
    { name: 'dividerColorReadOnly', type: 'color', params: { web: ['dividerColorReadOnly'] } },
    { name: 'inputColorDisabled', type: 'color', params: { web: ['inputColorDisabled'] } },
    { name: 'labelInnerTopHelper', type: 'dimension', variations: ['size'], params: { web: ['labelInnerTopHelper'] } },
    { name: 'labelInnerMarginBottom', type: 'dimension', variations: ['size'], params: { web: ['labelInnerMarginBottom'] } },
    { name: 'tooltipPaddingTop', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingTop'] } },
    { name: 'tooltipPaddingRight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingRight'] } },
    { name: 'tooltipContentLeftMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipContentLeftMargin'] } },
    { name: 'tooltipArrowMaskWidth', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowMaskWidth'] } },
    { name: 'tooltipArrowMaskHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowMaskHeight'] } },
    { name: 'tooltipArrowHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowHeight'] } },
    { name: 'tooltipArrowEdgeMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowEdgeMargin'] } },
    { name: 'readOnlyOpacity', type: 'float', params: { web: ['readOnlyOpacity'] } },
    { name: 'contentSlotRightOpacityReadOnly', type: 'float', params: { web: ['contentSlotRightOpacityReadOnly'] } },
    { name: 'disabledOpacity', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'borderRadius', type: 'dimension', variations: ['size'], params: { web: ['borderRadius'] } },
    { name: 'tooltipBorderRadius', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipBorderRadius'] } },
    { name: 'borderRadiusWithHelpers', type: 'dimension', variations: ['size'], params: { web: ['borderRadiusWithHelpers'] } },
    { name: 'indicatorLabelPlacementInner', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementInner'] } },
    { name: 'indicatorLabelPlacementOuter', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementOuter'] } },
    { name: 'indicatorLabelPlacementInnerRight', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementInnerRight'] } },
    { name: 'indicatorLabelPlacementOuterRight', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementOuterRight'] } },
    { name: 'backgroundColorReadOnly', type: 'color', params: { web: ['backgroundColorReadOnly'] } },
    { name: 'tooltipPaddingLeft', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingLeft'] } },
    { name: 'tooltipMinHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipMinHeight'] } },
];
