import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'inputBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'inputBackgroundColorActive', token: 'surface.default.transparent-primary-active' },
            { prop: 'inputBackgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'helpersBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'helpersBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'helpersBackgroundColorActive', token: 'surface.default.transparent-primary-active' },
            { prop: 'helpersBackgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'inputColor', token: 'text.default.primary' },
            { prop: 'inputColorFocus', token: 'text.default.primary' },
            { prop: 'inputCaretColor', token: 'text.default.accent' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'leftHelperColor', token: 'text.default.secondary' },
            { prop: 'rightHelperColor', token: 'text.default.secondary' },
            { prop: 'rightContentColor', token: 'text.default.secondary' },
            { prop: 'rightContentColorHover', token: 'text.default.secondary-hover' },
            { prop: 'rightContentColorActive', token: 'text.default.secondary-active' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
            { prop: 'scrollbarThumbBackgroundColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'scrollbarThumbBackgroundColorHover', token: 'surface.default.transparent-tertiary-hover' },
            { prop: 'scrollbarThumbBackgroundColorActive', token: 'surface.default.transparent-tertiary-active' },
            { prop: 'scrollbarTrackBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'scrollbarTrackBackgroundColorActive', token: 'surface.default.transparent-primary-active' },
            { prop: 'scrollbarTrackBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'dividerColorHover', token: 'text.default.secondary' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
        ],
        positive: [
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-positive' },
            { prop: 'inputBackgroundColorHover', token: 'surface.default.transparent-positive-hover' },
            { prop: 'inputBackgroundColorActive', token: 'surface.default.transparent-positive-active' },
            { prop: 'inputBackgroundColorFocus', token: 'surface.default.transparent-positive' },
            { prop: 'helpersBackgroundColor', token: 'surface.default.transparent-positive' },
            { prop: 'helpersBackgroundColorHover', token: 'surface.default.transparent-positive-hover' },
            { prop: 'helpersBackgroundColorActive', token: 'surface.default.transparent-positive-active' },
            { prop: 'helpersBackgroundColorFocus', token: 'surface.default.transparent-positive' },
            { prop: 'inputColor', token: 'text.default.primary' },
            { prop: 'inputColorFocus', token: 'text.default.primary' },
            { prop: 'inputCaretColor', token: 'text.default.positive' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'leftHelperColor', token: 'text.default.positive' },
            { prop: 'rightHelperColor', token: 'text.default.secondary' },
            { prop: 'rightContentColor', token: 'text.default.secondary' },
            { prop: 'rightContentColorHover', token: 'text.default.secondary-hover' },
            { prop: 'rightContentColorActive', token: 'text.default.secondary-active' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
            { prop: 'scrollbarThumbBackgroundColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'scrollbarThumbBackgroundColorHover', token: 'surface.default.transparent-tertiary-hover' },
            { prop: 'scrollbarThumbBackgroundColorActive', token: 'surface.default.transparent-tertiary-active' },
            { prop: 'scrollbarTrackBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'scrollbarTrackBackgroundColorActive', token: 'surface.default.transparent-primary-active' },
            { prop: 'scrollbarTrackBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'dividerColor', token: 'surface.default.positive' },
            { prop: 'dividerColorHover', token: 'surface.default.positive' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
        ],
        warning: [
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-warning' },
            { prop: 'inputBackgroundColorHover', token: 'surface.default.transparent-warning-hover' },
            { prop: 'inputBackgroundColorActive', token: 'surface.default.transparent-warning-active' },
            { prop: 'inputBackgroundColorFocus', token: 'surface.default.transparent-warning' },
            { prop: 'helpersBackgroundColor', token: 'surface.default.transparent-warning' },
            { prop: 'helpersBackgroundColorHover', token: 'surface.default.transparent-warning-hover' },
            { prop: 'helpersBackgroundColorActive', token: 'surface.default.transparent-warning-active' },
            { prop: 'helpersBackgroundColorFocus', token: 'surface.default.transparent-warning' },
            { prop: 'inputColor', token: 'text.default.primary' },
            { prop: 'inputColorFocus', token: 'text.default.primary' },
            { prop: 'inputCaretColor', token: 'text.default.warning' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'leftHelperColor', token: 'text.default.warning' },
            { prop: 'rightHelperColor', token: 'text.default.secondary' },
            { prop: 'rightContentColor', token: 'text.default.secondary' },
            { prop: 'rightContentColorHover', token: 'text.default.secondary-hover' },
            { prop: 'rightContentColorActive', token: 'text.default.secondary-active' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
            { prop: 'scrollbarThumbBackgroundColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'scrollbarThumbBackgroundColorHover', token: 'surface.default.transparent-tertiary-hover' },
            { prop: 'scrollbarThumbBackgroundColorActive', token: 'surface.default.transparent-tertiary-active' },
            { prop: 'scrollbarTrackBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'scrollbarTrackBackgroundColorActive', token: 'surface.default.transparent-primary-active' },
            { prop: 'scrollbarTrackBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'dividerColor', token: 'surface.default.warning' },
            { prop: 'dividerColorHover', token: 'surface.default.warning' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
        ],
        negative: [
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-negative' },
            { prop: 'inputBackgroundColorHover', token: 'surface.default.transparent-negative-hover' },
            { prop: 'inputBackgroundColorActive', token: 'surface.default.transparent-negative-active' },
            { prop: 'inputBackgroundColorFocus', token: 'surface.default.transparent-negative' },
            { prop: 'helpersBackgroundColor', token: 'surface.default.transparent-negative' },
            { prop: 'helpersBackgroundColorHover', token: 'surface.default.transparent-negative-hover' },
            { prop: 'helpersBackgroundColorActive', token: 'surface.default.transparent-negative-active' },
            { prop: 'helpersBackgroundColorFocus', token: 'surface.default.transparent-negative' },
            { prop: 'inputColor', token: 'text.default.primary' },
            { prop: 'inputColorFocus', token: 'text.default.primary' },
            { prop: 'inputCaretColor', token: 'text.default.negative' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'leftHelperColor', token: 'text.default.negative' },
            { prop: 'rightHelperColor', token: 'text.default.secondary' },
            { prop: 'rightContentColor', token: 'text.default.secondary' },
            { prop: 'rightContentColorHover', token: 'text.default.secondary-hover' },
            { prop: 'rightContentColorActive', token: 'text.default.secondary-active' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
            { prop: 'scrollbarThumbBackgroundColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'scrollbarThumbBackgroundColorHover', token: 'surface.default.transparent-tertiary-hover' },
            { prop: 'scrollbarThumbBackgroundColorActive', token: 'surface.default.transparent-tertiary-active' },
            { prop: 'scrollbarTrackBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'scrollbarTrackBackgroundColorActive', token: 'surface.default.transparent-primary-active' },
            { prop: 'scrollbarTrackBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'dividerColor', token: 'surface.default.negative' },
            { prop: 'dividerColorHover', token: 'surface.default.negative' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
        ],
    },
    size: {
        xl: [
            { prop: 'inputWidth', value: '100%' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'inputHeight', value: '108.992' },
            { prop: 'inputMinHeight', value: '26' },
            { prop: 'inputPaddingTop', value: '21.008' },
            { prop: 'inputPaddingRight', value: '20' },
            { prop: 'inputPaddingRightWithRightContent', value: '56' },
            { prop: 'inputPaddingBottom', value: '12' },
            { prop: 'inputPaddingLeft', value: '20' },
            { prop: 'helpersPaddingTop', value: '12' },
            { prop: 'helpersPaddingRight', value: '20' },
            { prop: 'helpersPaddingBottom', value: '12' },
            { prop: 'helpersPaddingLeft', value: '20' },
            { prop: 'helpersOffset', value: '0' },
            { prop: 'rightContentTop', value: '20' },
            { prop: 'rightContentRight', value: '20' },
            { prop: 'rightContentHeight', value: '24' },
            { prop: 'labelMarginBottom', value: '12' },
            { prop: 'labelInnerTop', value: '13.008' },
            { prop: 'labelInnerTopHelper', value: '-5.008' },
            { prop: 'labelInnerMarginBottom', value: '4' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorLabelPlacementHintOuterRight', value: '-4' },
            { prop: 'scrollbarWidth', value: '3.008' },
            { prop: 'scrollbarBorderWidth', value: '1.008' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'labelInnerStyle', value: 'body.xs.normal' },
            { prop: 'inputStyle', value: 'body.l.normal' },
            { prop: 'helpersStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '16' },
            { prop: 'borderRadiusWithHelpers', value: '16', adjust: [{ platform: 'web', param: 'borderRadiusWithHelpers', template: '$1 $1 0 0' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '8', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.675rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.625rem auto auto' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '12.016', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
        ],
        l: [
            { prop: 'inputWidth', value: '100%' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'inputHeight', value: '108.992' },
            { prop: 'inputMinHeight', value: '26' },
            { prop: 'inputPaddingTop', value: '17.008' },
            { prop: 'inputPaddingRight', value: '18' },
            { prop: 'inputPaddingRightWithRightContent', value: '58' },
            { prop: 'inputPaddingBottom', value: '12' },
            { prop: 'inputPaddingLeft', value: '18' },
            { prop: 'helpersPaddingTop', value: '12' },
            { prop: 'helpersPaddingRight', value: '18' },
            { prop: 'helpersPaddingBottom', value: '12' },
            { prop: 'helpersPaddingLeft', value: '18' },
            { prop: 'helpersOffset', value: '0' },
            { prop: 'rightContentTop', value: '17.008' },
            { prop: 'rightContentRight', value: '16' },
            { prop: 'rightContentHeight', value: '20' },
            { prop: 'labelMarginBottom', value: '12' },
            { prop: 'labelInnerTop', value: '9' },
            { prop: 'labelInnerTopHelper', value: '-5.008' },
            { prop: 'labelInnerMarginBottom', value: '2' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorLabelPlacementHintOuterRight', value: '-4' },
            { prop: 'scrollbarWidth', value: '3.008' },
            { prop: 'scrollbarBorderWidth', value: '1.008' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'labelInnerStyle', value: 'body.xs.normal' },
            { prop: 'inputStyle', value: 'body.l.normal' },
            { prop: 'helpersStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '14' },
            { prop: 'borderRadiusWithHelpers', value: '14', adjust: [{ platform: 'web', param: 'borderRadiusWithHelpers', template: '$1 $1 0 0' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '8', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.675rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.625rem auto auto' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '9.008', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
        ],
        m: [
            { prop: 'inputWidth', value: '100%' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'inputHeight', value: '112' },
            { prop: 'inputMinHeight', value: '18' },
            { prop: 'inputPaddingTop', value: '14' },
            { prop: 'inputPaddingRight', value: '16' },
            { prop: 'inputPaddingRightWithRightContent', value: '54' },
            { prop: 'inputPaddingBottom', value: '12' },
            { prop: 'inputPaddingLeft', value: '16' },
            { prop: 'helpersPaddingTop', value: '12' },
            { prop: 'helpersPaddingRight', value: '16' },
            { prop: 'helpersPaddingBottom', value: '12' },
            { prop: 'helpersPaddingLeft', value: '16' },
            { prop: 'helpersOffset', value: '0' },
            { prop: 'rightContentTop', value: '14' },
            { prop: 'rightContentRight', value: '14' },
            { prop: 'rightContentHeight', value: '20' },
            { prop: 'labelMarginBottom', value: '10' },
            { prop: 'labelInnerTop', value: '6' },
            { prop: 'labelInnerTopHelper', value: '-5.008' },
            { prop: 'labelInnerMarginBottom', value: '2' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorLabelPlacementHintOuterRight', value: '-4' },
            { prop: 'scrollbarWidth', value: '3.008' },
            { prop: 'scrollbarBorderWidth', value: '1.008' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'labelInnerStyle', value: 'body.xs.normal' },
            { prop: 'inputStyle', value: 'body.m.normal' },
            { prop: 'helpersStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '12' },
            { prop: 'borderRadiusWithHelpers', value: '12', adjust: [{ platform: 'web', param: 'borderRadiusWithHelpers', template: '$1 $1 0 0' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '7', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.675rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '3', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.625rem auto auto' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '4.992', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
        ],
        s: [
            { prop: 'inputWidth', value: '100%' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'inputHeight', value: '114.992' },
            { prop: 'inputMinHeight', value: '10' },
            { prop: 'inputPaddingTop', value: '11.008' },
            { prop: 'inputPaddingRight', value: '14' },
            { prop: 'inputPaddingRightWithRightContent', value: '50' },
            { prop: 'inputPaddingBottom', value: '12' },
            { prop: 'inputPaddingLeft', value: '14' },
            { prop: 'helpersPaddingTop', value: '12' },
            { prop: 'helpersPaddingRight', value: '14' },
            { prop: 'helpersPaddingBottom', value: '12' },
            { prop: 'helpersPaddingLeft', value: '14' },
            { prop: 'helpersOffset', value: '0' },
            { prop: 'rightContentTop', value: '11.008' },
            { prop: 'rightContentRight', value: '12' },
            { prop: 'rightContentHeight', value: '20' },
            { prop: 'labelMarginBottom', value: '8' },
            { prop: 'labelInnerTop', value: '6' },
            { prop: 'labelInnerTopHelper', value: '-5.008' },
            { prop: 'labelInnerMarginBottom', value: '2' },
            { prop: 'indicatorSizeInner', value: '6' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorLabelPlacementHintOuterRight', value: '-4' },
            { prop: 'scrollbarWidth', value: '3.008' },
            { prop: 'scrollbarBorderWidth', value: '1.008' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'labelInnerStyle', value: 'body.xs.normal' },
            { prop: 'inputStyle', value: 'body.s.normal' },
            { prop: 'helpersStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '10' },
            { prop: 'borderRadiusWithHelpers', value: '10', adjust: [{ platform: 'web', param: 'borderRadiusWithHelpers', template: '$1 $1 0 0' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '6', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.675rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.625rem auto auto' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '0.992', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
        ],
        xs: [
            { prop: 'inputWidth', value: '100%' },
            { prop: 'hintMargin', value: '-0.75rem -0.625rem -0.75rem -0.5rem' },
            { prop: 'inputHeight', value: '116.992' },
            { prop: 'inputMinHeight', value: '10' },
            { prop: 'inputPaddingTop', value: '9.008' },
            { prop: 'inputPaddingRight', value: '10' },
            { prop: 'inputPaddingRightWithRightContent', value: '34' },
            { prop: 'inputPaddingBottom', value: '9.008' },
            { prop: 'inputPaddingLeft', value: '10' },
            { prop: 'helpersPaddingTop', value: '8' },
            { prop: 'helpersPaddingRight', value: '10' },
            { prop: 'helpersPaddingBottom', value: '9.008' },
            { prop: 'helpersPaddingLeft', value: '10' },
            { prop: 'helpersOffset', value: '0' },
            { prop: 'rightContentTop', value: '9.008' },
            { prop: 'rightContentRight', value: '8' },
            { prop: 'rightContentHeight', value: '16' },
            { prop: 'labelMarginBottom', value: '6' },
            { prop: 'labelInnerTop', value: '0' },
            { prop: 'labelInnerTopHelper', value: '-5.008' },
            { prop: 'labelInnerMarginBottom', value: '0' },
            { prop: 'indicatorSizeInner', value: '6' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorLabelPlacementHintOuterRight', value: '-4' },
            { prop: 'scrollbarWidth', value: '3.008' },
            { prop: 'scrollbarBorderWidth', value: '1.008' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'labelInnerStyle', value: 'body.xxs.normal' },
            { prop: 'inputStyle', value: 'body.xs.normal' },
            { prop: 'helpersStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '8' },
            { prop: 'borderRadiusWithHelpers', value: '8', adjust: [{ platform: 'web', param: 'borderRadiusWithHelpers', template: '$1 $1 0 0' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.675rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '2', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.625rem auto auto' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '-3.008', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
        ],
    },
    hintView: {
        default: [
            { prop: 'tooltipBackgroundColor', token: 'surface.default.solid-card-brightness' },
            { prop: 'tooltipBoxShadow', value: 'down.hard.m' },
            { prop: 'tooltipColor', token: 'text.default.primary' },
            { prop: 'tooltipArrowBackground', token: 'surface.default.solid-card-brightness' },
        ],
    },
    hintSize: {
        m: [
            { prop: 'tooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMC4xNywxMS44M2wyMCwwYy01LjUyLDAgLTEwLDMuNTkgLTEwLDhjMCwtNC40MSAtNC40OCwtOCAtMTAsLTh6IiBmaWxsPSIjMTcxNzE3IiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGlkPSJUYWlsIi8+Cjwvc3ZnPg==")' },
            { prop: 'tooltipPaddingTop', value: '11' },
            { prop: 'tooltipPaddingRight', value: '14' },
            { prop: 'tooltipPaddingBottom', value: '11' },
            { prop: 'tooltipPaddingLeft', value: '14' },
            { prop: 'tooltipMinHeight', value: '40' },
            { prop: 'tooltipContentLeftMargin', value: '6' },
            { prop: 'tooltipArrowMaskWidth', value: '20' },
            { prop: 'tooltipArrowMaskHeight', value: '20' },
            { prop: 'tooltipArrowHeight', value: '8' },
            { prop: 'tooltipArrowEdgeMargin', value: '10' },
            { prop: 'tooltipTextStyle', value: 'body.s.normal' },
            { prop: 'tooltipBorderRadius', value: '10' },
        ],
        s: [
            { prop: 'tooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMCw5Ljg1bDE2LDBjLTQuNDEsMCAtOCwyLjY5IC04LDZjMCwtMy4zMSAtMy41OSwtNiAtOCwtNnoiIGZpbGw9IiMxNzE3MTciIGZpbGwtcnVsZT0iZXZlbm9kZCIgaWQ9IlRhaWwiLz4KPC9zdmc+")' },
            { prop: 'tooltipPaddingTop', value: '8' },
            { prop: 'tooltipPaddingRight', value: '12' },
            { prop: 'tooltipPaddingBottom', value: '8' },
            { prop: 'tooltipPaddingLeft', value: '12' },
            { prop: 'tooltipMinHeight', value: '32' },
            { prop: 'tooltipContentLeftMargin', value: '4' },
            { prop: 'tooltipArrowMaskWidth', value: '16' },
            { prop: 'tooltipArrowMaskHeight', value: '16' },
            { prop: 'tooltipArrowHeight', value: '6' },
            { prop: 'tooltipArrowEdgeMargin', value: '9' },
            { prop: 'tooltipTextStyle', value: 'body.xs.normal' },
            { prop: 'tooltipBorderRadius', value: '8' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'backgroundColorReadOnly', token: 'surface.default.transparent-primary' },
    { prop: 'inputColorReadOnly', token: 'text.default.primary' },
    { prop: 'dividerColorReadOnly', token: 'surface.default.transparent-primary' },
    { prop: 'readOnlyOpacity', value: '0.1' },
    { prop: 'contentSlotRightOpacityReadOnly', value: '0.4' },
    { prop: 'inputColorDisabled', token: 'text.default.secondary' },
    { prop: 'titleCaptionColorReadOnly', token: 'text.default.secondary' },
    { prop: 'disabledOpacity', value: '0.4' },
];
