import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'background', token: 'surface.default.transparent-secondary' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'contentBeforeColor', token: 'text.default.primary' },
        ],
        positive: [
            { prop: 'background', token: 'surface.default.transparent-positive' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'contentBeforeColor', token: 'text.default.positive' },
        ],
        warning: [
            { prop: 'background', token: 'surface.default.transparent-warning' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'contentBeforeColor', token: 'text.default.warning' },
        ],
        negative: [
            { prop: 'background', token: 'surface.default.transparent-negative' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'contentBeforeColor', token: 'text.default.negative' },
        ],
        info: [
            { prop: 'background', token: 'surface.default.transparent-info' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'contentBeforeColor', token: 'text.default.info' },
        ],
    },
    size: {
        s: [
            { prop: 'closeIconColor', token: 'text.default.secondary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.secondary-hover' },
            { prop: 'paddingScalable', value: '1rem' },
            { prop: 'fixedContentBeforePadding', value: '0.063rem 0rem' },
            { prop: 'gap', value: '8' },
            { prop: 'gapScalable', value: '12' },
            { prop: 'contentGap', value: '2' },
            { prop: 'paddingBottomWithActionContent', value: '5' },
            { prop: 'closeIconTop', value: '10' },
            { prop: 'closeIconRight', value: '10' },
            { prop: 'closeIconSize', value: '24' },
            { prop: 'closeIconButtonSize', value: '24' },
            { prop: 'fixedContentBeforeWidth', value: '16' },
            { prop: 'fixedContentBeforeHeight', value: '18' },
            { prop: 'titlePaddingRight', value: '26' },
            { prop: 'titleStyle', value: 'text.s.bold' },
            { prop: 'textStyle', value: 'text.s.normal' },
            { prop: 'borderRadius', value: '10' },
            { prop: 'padding', value: '20', adjust: [{ platform: 'web', param: 'padding', template: '1.5rem $1' }] },
        ],
        xs: [
            { prop: 'closeIconColor', token: 'text.default.secondary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.secondary-hover' },
            { prop: 'paddingScalable', value: '0.75rem' },
            { prop: 'fixedContentBeforePadding', value: '0rem' },
            { prop: 'gap', value: '6' },
            { prop: 'gapScalable', value: '8' },
            { prop: 'contentGap', value: '2' },
            { prop: 'paddingBottomWithActionContent', value: '3' },
            { prop: 'closeIconTop', value: '10' },
            { prop: 'closeIconRight', value: '10' },
            { prop: 'closeIconSize', value: '16' },
            { prop: 'closeIconButtonSize', value: '16' },
            { prop: 'fixedContentBeforeWidth', value: '16' },
            { prop: 'fixedContentBeforeHeight', value: '16' },
            { prop: 'titlePaddingRight', value: '24' },
            { prop: 'titleStyle', value: 'text.xs.bold' },
            { prop: 'textStyle', value: 'text.xs.normal' },
            { prop: 'borderRadius', value: '8' },
            { prop: 'padding', value: '16', adjust: [{ platform: 'web', param: 'padding', template: '1.5rem $1' }] },
        ],
        l: [
            { prop: 'closeIconColor', token: 'text.default.secondary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.secondary-hover' },
            { prop: 'paddingScalable', value: '1.5rem 1.75rem' },
            { prop: 'fixedContentBeforePadding', value: '0.25rem 0rem' },
            { prop: 'gap', value: '12' },
            { prop: 'gapScalable', value: '16' },
            { prop: 'contentGap', value: '4' },
            { prop: 'paddingBottomWithActionContent', value: '7' },
            { prop: 'closeIconTop', value: '16' },
            { prop: 'closeIconRight', value: '16' },
            { prop: 'closeIconSize', value: '24' },
            { prop: 'closeIconButtonSize', value: '24' },
            { prop: 'fixedContentBeforeWidth', value: '24' },
            { prop: 'fixedContentBeforeHeight', value: '32' },
            { prop: 'titlePaddingRight', value: '30' },
            { prop: 'titleStyle', value: 'text.l.bold' },
            { prop: 'textStyle', value: 'text.l.normal' },
            { prop: 'borderRadius', value: '14' },
            { prop: 'padding', value: '30', adjust: [{ platform: 'web', param: 'padding', template: '1.5rem $1' }] },
        ],
        m: [
            { prop: 'closeIconColor', token: 'text.default.secondary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.secondary-hover' },
            { prop: 'paddingScalable', value: '1.25rem' },
            { prop: 'fixedContentBeforePadding', value: '0rem' },
            { prop: 'gap', value: '10' },
            { prop: 'gapScalable', value: '12' },
            { prop: 'contentGap', value: '2' },
            { prop: 'paddingBottomWithActionContent', value: '8' },
            { prop: 'closeIconTop', value: '12' },
            { prop: 'closeIconRight', value: '12' },
            { prop: 'closeIconSize', value: '24' },
            { prop: 'closeIconButtonSize', value: '24' },
            { prop: 'fixedContentBeforeWidth', value: '24' },
            { prop: 'fixedContentBeforeHeight', value: '26' },
            { prop: 'titlePaddingRight', value: '28' },
            { prop: 'titleStyle', value: 'text.m.bold' },
            { prop: 'textStyle', value: 'text.m.normal' },
            { prop: 'borderRadius', value: '12' },
            { prop: 'padding', value: '24', adjust: [{ platform: 'web', param: 'padding', template: '1.5rem $1' }] },
        ],
    },
};
