import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'accordionGap', value: '2' },
            { prop: 'accordionItemBorderBottom', value: '0' },
            { prop: 'accordionItemIconColor', token: 'text.default.primary' },
            { prop: 'accordionItemPaddingHorizontalLeft', value: 'var(--plasma-accordion-item-padding-horizontal)' },
            { prop: 'accordionItemTitleColor', token: 'text.default.primary' },
            { prop: 'accordionBackground', token: 'surface.default.clear' },
            { prop: 'accordionItemBackground', token: 'surface.default.solid-card' },
            { prop: 'accordionItemFocus', token: 'surface.default.accent' },
            { prop: 'accordionItemPadding', value: 'var(--plasma-accordion-item-padding-vertical) var(--plasma-accordion-item-padding-horizontal)' },
            { prop: 'accordionItemTextColor', token: 'text.default.primary' },
            { prop: 'accordionWidth', value: '320' },
        ],
        clear: [
            { prop: 'accordionBackground', token: 'surface.default.clear' },
            { prop: 'accordionItemBackground', token: 'surface.default.clear' },
            { prop: 'accordionItemFocus', token: 'surface.default.accent' },
            { prop: 'accordionItemPadding', value: 'var(--plasma-accordion-item-padding-vertical) 0rem' },
            { prop: 'accordionItemTextColor', token: 'text.default.primary' },
            { prop: 'accordionItemViewBorderRadius', value: '0' },
            { prop: 'accordionGap', value: '0' },
            { prop: 'accordionItemBorderBottom', value: '0.063rem solid var(--surface-solid-tertiary)' },
            { prop: 'accordionItemIconColor', token: 'text.default.primary' },
            { prop: 'accordionItemPaddingHorizontalLeft', value: '0' },
            { prop: 'accordionItemTitleColor', token: 'text.default.primary' },
            { prop: 'accordionWidth', value: '320' },
        ],
    },
    size: {
        l: [
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingVertical', value: '17' },
            { prop: 'accordionItemTitleStyle', value: 'body.l.bold' },
            { prop: 'accordionItemBorderRadius', value: '14' },
            { prop: 'accordionItemPaddingHorizontal', value: '20' },
            { prop: 'accordionItemTextStyle', value: 'body.l.normal' },
        ],
        m: [
            { prop: 'accordionItemGap', value: '6' },
            { prop: 'accordionItemBorderRadius', value: '12' },
            { prop: 'accordionItemPaddingHorizontal', value: '18' },
            { prop: 'accordionItemTextStyle', value: 'body.m.normal' },
            { prop: 'accordionItemPaddingVertical', value: '14' },
            { prop: 'accordionItemTitleStyle', value: 'body.m.bold' },
        ],
        s: [
            { prop: 'accordionItemBorderRadius', value: '10' },
            { prop: 'accordionItemPaddingHorizontal', value: '14' },
            { prop: 'accordionItemTextStyle', value: 'body.s.normal' },
            { prop: 'accordionItemGap', value: '6' },
            { prop: 'accordionItemPaddingVertical', value: '11' },
            { prop: 'accordionItemTitleStyle', value: 'body.s.bold' },
        ],
        xs: [
            { prop: 'accordionItemBorderRadius', value: '8' },
            { prop: 'accordionItemPaddingHorizontal', value: '12' },
            { prop: 'accordionItemTextStyle', value: 'body.xs.normal' },
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingVertical', value: '8' },
            { prop: 'accordionItemTitleStyle', value: 'body.xs.bold' },
        ],
        h2: [
            { prop: 'accordionItemBorderRadius', value: '12' },
            { prop: 'accordionItemIconSize', value: '24' },
            { prop: 'accordionItemPaddingVertical', value: '16' },
            { prop: 'accordionItemTitleStyle', value: 'header.h2.bold' },
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingHorizontal', value: '20' },
            { prop: 'accordionItemTextStyle', value: 'body.l.normal' },
        ],
        h3: [
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingHorizontal', value: '18' },
            { prop: 'accordionItemTextStyle', value: 'body.l.normal' },
            { prop: 'accordionItemBorderRadius', value: '12' },
            { prop: 'accordionItemIconSize', value: '24' },
            { prop: 'accordionItemPaddingVertical', value: '14' },
            { prop: 'accordionItemTitleStyle', value: 'header.h3.bold' },
        ],
        h4: [
            { prop: 'accordionItemBorderRadius', value: '10' },
            { prop: 'accordionItemPaddingHorizontal', value: '14' },
            { prop: 'accordionItemTextStyle', value: 'body.m.normal' },
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingVertical', value: '11.008' },
            { prop: 'accordionItemTitleStyle', value: 'header.h4.bold' },
        ],
        h5: [
            { prop: 'accordionItemBorderRadius', value: '8' },
            { prop: 'accordionItemPaddingHorizontal', value: '12' },
            { prop: 'accordionItemTextStyle', value: 'body.m.normal' },
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingVertical', value: '8' },
            { prop: 'accordionItemTitleStyle', value: 'header.h5.bold' },
        ],
        h6: [
            { prop: 'accordionItemBorderRadius', value: '8' },
            { prop: 'accordionItemPaddingHorizontal', value: '12' },
            { prop: 'accordionItemTextStyle', value: 'body.m.normal' },
            { prop: 'accordionItemGap', value: '4' },
            { prop: 'accordionItemPaddingVertical', value: '8' },
            { prop: 'accordionItemTitleStyle', value: 'header.h6.bold' },
        ],
    },
};
