import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    size: {
        xl: [
            { prop: 'itemFontWeightBold', value: 'var(--plasma-typo-body-l-font-weight)' },
            { prop: 'itemPadding', value: '1.25rem 1.125rem' },
            { prop: 'padding', value: '2' },
            { prop: 'width', value: '280' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'dividerMarginTop', value: '10' },
            { prop: 'dividerMarginRight', value: '20' },
            { prop: 'dividerMarginBottom', value: '10' },
            { prop: 'dividerMarginLeft', value: '20' },
            { prop: 'dividerMarginTopTight', value: '8' },
            { prop: 'dividerMarginBottomTight', value: '8' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '8' },
            { prop: 'itemStyle', value: 'body.l.normal' },
            { prop: 'cellTitleStyle', value: 'body.l.normal' },
            { prop: 'borderRadius', value: '16' },
            { prop: 'itemBorderRadius', value: '16' },
            { prop: 'itemPaddingTight', value: '16', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.875rem' }] },
        ],
        l: [
            { prop: 'itemFontWeightBold', value: 'var(--plasma-typo-body-l-font-weight)' },
            { prop: 'itemPadding', value: '1rem 1.125rem' },
            { prop: 'padding', value: '2' },
            { prop: 'width', value: '280' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'dividerMarginTop', value: '8' },
            { prop: 'dividerMarginRight', value: '18' },
            { prop: 'dividerMarginBottom', value: '8' },
            { prop: 'dividerMarginLeft', value: '18' },
            { prop: 'dividerMarginTopTight', value: '6' },
            { prop: 'dividerMarginBottomTight', value: '6' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '6' },
            { prop: 'itemStyle', value: 'body.l.normal' },
            { prop: 'cellTitleStyle', value: 'body.l.normal' },
            { prop: 'borderRadius', value: '14' },
            { prop: 'itemBorderRadius', value: '12' },
            { prop: 'itemPaddingTight', value: '12', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.875rem' }] },
        ],
        m: [
            { prop: 'itemFontWeightBold', value: 'var(--plasma-typo-body-m-font-weight)' },
            { prop: 'itemPadding', value: '0.75rem 0.875rem' },
            { prop: 'padding', value: '2' },
            { prop: 'width', value: '240' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'dividerMarginTop', value: '6' },
            { prop: 'dividerMarginRight', value: '14' },
            { prop: 'dividerMarginBottom', value: '6' },
            { prop: 'dividerMarginLeft', value: '14' },
            { prop: 'dividerMarginTopTight', value: '6' },
            { prop: 'dividerMarginBottomTight', value: '6' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '6' },
            { prop: 'itemStyle', value: 'body.m.normal' },
            { prop: 'cellTitleStyle', value: 'body.m.normal' },
            { prop: 'borderRadius', value: '12' },
            { prop: 'itemBorderRadius', value: '10' },
            { prop: 'itemPaddingTight', value: '8', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.875rem' }] },
        ],
        s: [
            { prop: 'itemFontWeightBold', value: 'var(--plasma-typo-body-s-font-weight)' },
            { prop: 'itemPadding', value: '0.5rem 0.75rem' },
            { prop: 'padding', value: '2' },
            { prop: 'width', value: '200' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'dividerMarginTop', value: '6' },
            { prop: 'dividerMarginRight', value: '12' },
            { prop: 'dividerMarginBottom', value: '6' },
            { prop: 'dividerMarginLeft', value: '12' },
            { prop: 'dividerMarginTopTight', value: '4' },
            { prop: 'dividerMarginBottomTight', value: '4' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '6' },
            { prop: 'itemStyle', value: 'body.s.normal' },
            { prop: 'cellTitleStyle', value: 'body.s.normal' },
            { prop: 'borderRadius', value: '10' },
            { prop: 'itemBorderRadius', value: '8' },
            { prop: 'itemPaddingTight', value: '4', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.875rem' }] },
        ],
        xs: [
            { prop: 'itemFontWeightBold', value: 'var(--plasma-typo-body-xs-font-weight)' },
            { prop: 'itemPadding', value: '0.5rem' },
            { prop: 'padding', value: '2' },
            { prop: 'width', value: '160' },
            { prop: 'itemHeight', value: '16' },
            { prop: 'dividerMarginTop', value: '4' },
            { prop: 'dividerMarginRight', value: '8' },
            { prop: 'dividerMarginBottom', value: '4' },
            { prop: 'dividerMarginLeft', value: '8' },
            { prop: 'dividerMarginTopTight', value: '2' },
            { prop: 'dividerMarginBottomTight', value: '2' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '4' },
            { prop: 'itemStyle', value: 'body.xs.normal' },
            { prop: 'cellTitleStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '8' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'itemPaddingTight', value: '4', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.875rem' }] },
        ],
    },
    view: {
        default: [
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
        ],
    },
};
