import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';

import { generateTheme } from './generate-theme.ts';
import { CORE_VERSION, cliDirectory, writePackagePart } from './package-output.ts';
import { readThemeSource } from './theme-source.ts';
import { resolveLocalThemePaths } from './local-theme-source.ts';

/**
 * Генерирует тему дизайн-системы из .sdds, без компонентов.
 * Без `--package` в `output` заменяется только `src/theme`; с `--package` собирается пакет
 * из одной темы. Компоненты генерирует `generate:components`. К бэкенду CLI не обращается.
 */
async function main() {
    const { values } = parseArgs({
        options: {
            sdds: { type: 'string', default: join(cliDirectory, '.sdds') },
            tenant: { type: 'string' },
            out: { type: 'string', default: join(cliDirectory, 'output') },
            name: { type: 'string' },
            'ds-version': { type: 'string', default: '0.1.0' },
            'core-version': { type: 'string', default: CORE_VERSION },
            package: { type: 'boolean', default: false },
            help: { type: 'boolean', short: 'h' },
        },
    });

    if (values.help) {
        console.log(`Generate the theme of a local React design system package using services/generator.

Usage: npm run generate:theme -- [options]
  --sdds <directory>       Local data directory (default: js/cli/.sdds)
  --tenant <name>          Theme tenant (default: sole tenant in .sdds/config.json)
  --out <directory>        Output directory (default: js/cli/output)
  --name <name>            Package name; required with --package
  --ds-version <version>   Package version (default: 0.1.0)
  --core-version <version> Plasma core version (default: ${CORE_VERSION})
  --package                Build a theme-only package and write a .tgz instead of the sources

Reads config.json, tenants/<tenant> and the palette from .sdds.
Replaces only src/theme (and src/index.ts) in the output directory, or writes
<scope>-<name>-<version>-theme.tgz with --package. Components are generated by generate:components.`);
        return;
    }

    const source = await readThemeSource(await resolveLocalThemePaths(resolve(values.sdds), values.tenant));

    const result = await writePackagePart({
        parts: ['theme'],
        outputDirectory: resolve(values.out),
        packageName: values.name,
        packageVersion: values['ds-version'],
        coreVersion: values['core-version'],
        pack: values.package,
        fill: (pathToDir) => generateTheme(source, join(pathToDir, 'src', 'theme')),
    });
    console.log(`Generated ${result}`);
}

main().catch((error) => {
    console.error('Failed to generate theme:', error);
    process.exitCode = 1;
});
