export const PROJECT_ACCESS_KEY_SCOPES = [
    'projects:read',
    'members:read',
    'design-systems:read',
    'design-systems:write',
    'design-systems:delete',
    'tenants:read',
    'tenants:write',
    'tenants:delete',
    'tenants:subthemes:read',
    'tenants:subthemes:write',
    'tenants:subthemes:delete',
    'tokens:read',
    'tokens:write',
    'tokens:delete',
    'tokens:group:read',
    'tokens:group:write',
    'tokens:group:delete',
    'tokens:subgroup:read',
    'tokens:subgroup:write',
    'tokens:subgroup:delete',
    'components:read',
    'components:write',
    'components:delete',
    'components:variations:read',
    'components:variations:write',
    'components:variations:delete',
    'documentation:read',
    'documentation:write',
] as const;

export const PROJECT_ACCESS_KEY_EXPIRY_OPTIONS = [
    { value: 30 * 86400, label: '30 дней' },
    { value: 90 * 86400, label: '90 дней' },
    { value: 365 * 86400, label: '1 год' },
];
