import { useEffect, useMemo, useState } from 'react';

import { SelectButtonItem } from '../components';
import {
    IconButtonStories,
    LinkStories,
    ButtonStories,
    CheckboxStories,
    RadioboxStories,
    CounterStories,
    IndicatorStories,
    BadgeStories,
    SpinnerStories,
    ChipStories,
    SwitchStories,
    SkeletonStories,
    ListStories,
    LinkButtonStories,
    EmbedIconButtonDefaultStories,
    CellStories,
    DividerStories,
    EmptyStateStories,
    AccordionStories,
    SliderStories,
    NoteStories,
    TextFieldStories,
    RangeStories,
    TextAreaStories,
    TabsStories,
    TabItemStories,
    IconTabItemStories,
    ButtonGroupStories,
    BreadcrumbsStories,
    ChipGroupStories,
    CardStories,
    PopoverStories,
    TextFieldGroupStories,
    AvatarStories,
    PaginationStories,
    ProgressStories,
    SheetStories,
    LoaderStories,
    ProgressBarCircularStories,
    NumberInputStories,
    RatingStories,
    ImageStories,
    AvatarGroupStories,
    PriceStories,
    TooltipStories,
    ModalStories,
    PopupStories,
    DropzoneStories,
    SelectStories,
    ComboboxStories,
    DropdownStories,
    ToolbarStories,
    DrawerStories,
    ToastStories,
    NotificationStories,
    StepsStories,
    StepItemStories,
    SegmentGroupStories,
    SegmentItemStories,
    BodyStories,
    DsplStories,
    HeadingStories,
    TextStories,
} from '../stories';

interface Story {
    name: string;
    args: Record<string, any>[];
    render: (props: any) => JSX.Element;
}

// TODO: Подумать как сделать автоматически расширяемый список
const componentMapper: Record<string, Story[]> = {
    IconButton: IconButtonStories,
    Link: LinkStories,
    Button: ButtonStories,
    Checkbox: CheckboxStories,
    Radiobox: RadioboxStories,
    Counter: CounterStories,
    Indicator: IndicatorStories,
    Badge: BadgeStories,
    Spinner: SpinnerStories,
    Chip: ChipStories,
    Switch: SwitchStories,
    Skeleton: SkeletonStories,
    List: ListStories,
    LinkButton: LinkButtonStories,
    EmbedIconButton: EmbedIconButtonDefaultStories,
    Cell: CellStories,
    Divider: DividerStories,
    EmptyState: EmptyStateStories,
    Accordion: AccordionStories,
    Slider: SliderStories,
    Note: NoteStories,
    TextField: TextFieldStories,
    Range: RangeStories,
    TextArea: TextAreaStories,
    Tabs: TabsStories,
    TabItem: TabItemStories,
    IconTabItem: IconTabItemStories,
    ButtonGroup: ButtonGroupStories,
    Breadcrumbs: BreadcrumbsStories,
    ChipGroup: ChipGroupStories,
    Card: CardStories,
    Popover: PopoverStories,
    TextFieldGroup: TextFieldGroupStories,
    Avatar: AvatarStories,
    Pagination: PaginationStories,
    Progress: ProgressStories,
    Sheet: SheetStories,
    Loader: LoaderStories,
    ProgressBarCircular: ProgressBarCircularStories,
    NumberInput: NumberInputStories,
    Rating: RatingStories,
    Image: ImageStories,
    AvatarGroup: AvatarGroupStories,
    Price: PriceStories,
    Tooltip: TooltipStories,
    Modal: ModalStories,
    Popup: PopupStories,
    Dropzone: DropzoneStories,
    Select: SelectStories,
    Combobox: ComboboxStories,
    Dropdown: DropdownStories,
    Toolbar: ToolbarStories,
    Drawer: DrawerStories,
    Toast: ToastStories,
    Notification: NotificationStories,
    Steps: StepsStories,
    StepItem: StepItemStories,
    Body: BodyStories,
    Dspl: DsplStories,
    Heading: HeadingStories,
    Text: TextStories,
    SegmentGroup: SegmentGroupStories,
    SegmentItem: SegmentItemStories,
};

export const useStory = (componentName?: string) => {
    const [selectedStory, setSelectedStory] = useState<SelectButtonItem>({ value: 'Default', label: 'Default' });

    const stories = (componentName && componentMapper[componentName]) || [];
    const items: SelectButtonItem[] = stories.map(({ name }) => ({ value: name, label: name }));

    useEffect(() => {
        setSelectedStory({ value: 'Default', label: 'Default' });
    }, [componentName]);

    const story = useMemo(
        () => stories.find(({ name }) => name === selectedStory.value),
        [componentName, selectedStory],
    );

    return {
        storyArgs: story?.args ?? [],
        items,
        selectedStory,
        setSelectedStory,
        Story: story?.render,
    } as const;
};
