import { TokenType } from '../../../types';

export const shadowTokens: Array<TokenType> = [
    {
        type: 'shadow',
        name: 'down.soft.s',
        tags: ['down', 'soft', 's'],
        displayName: 'downSoftS',
        description: 'shadow down soft s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.soft.m',
        tags: ['down', 'soft', 'm'],
        displayName: 'downSoftM',
        description: 'shadow down soft m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.soft.l',
        tags: ['down', 'soft', 'l'],
        displayName: 'downSoftL',
        description: 'shadow down soft l',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.hard.s',
        tags: ['down', 'hard', 's'],
        displayName: 'downHardS',
        description: 'shadow down hard s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.hard.m',
        tags: ['down', 'hard', 'm'],
        displayName: 'downHardM',
        description: 'shadow down hard m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'down.hard.l',
        tags: ['down', 'hard', 'l'],
        displayName: 'downHardL',
        description: 'shadow down hard l',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.soft.s',
        tags: ['up', 'soft', 's'],
        displayName: 'upSoftS',
        description: 'shadow up soft s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.soft.m',
        tags: ['up', 'soft', 'm'],
        displayName: 'upSoftM',
        description: 'shadow up soft m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.soft.l',
        tags: ['up', 'soft', 'l'],
        displayName: 'upSoftL',
        description: 'shadow up soft l',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.hard.s',
        tags: ['up', 'hard', 's'],
        displayName: 'upHardS',
        description: 'shadow up hard s',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.hard.m',
        tags: ['up', 'hard', 'm'],
        displayName: 'upHardM',
        description: 'shadow up hard m',
        enabled: true,
    },
    {
        type: 'shadow',
        name: 'up.hard.l',
        tags: ['up', 'hard', 'l'],
        displayName: 'upHardL',
        description: 'shadow up hard l',
        enabled: true,
    },
];
