import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'trackBorderWidthOff', type: 'dimension', variations: ['view'], params: { web: ['trackBorderWidthOff'] } },
    { name: 'trackBorderRadius', type: 'shape', variations: ['toggleSize'], params: { web: ['trackBorderRadius'] } },
    { name: 'trackBackgroundColorOn', type: 'color', variations: ['view'], params: { web: ['trackBackgroundColorOn'] } },
    { name: 'trackBackgroundColorOff', type: 'color', variations: ['view'], params: { web: ['trackBackgroundColorOff'] } },
    { name: 'thumbSize', type: 'dimension', variations: ['toggleSize'], params: { web: ['thumbSize'] } },
    { name: 'thumbOffsetOn', type: 'dimension', variations: ['toggleSize'], params: { web: ['thumbOffsetOn'] } },
    { name: 'thumbOffsetOff', type: 'dimension', variations: ['toggleSize'], params: { web: ['thumbOffsetOff'] } },
    { name: 'thumbBorderRadius', type: 'shape', variations: ['toggleSize'], params: { web: ['thumbBorderRadius'] } },
    { name: 'thumbBorderColorOff', type: 'color', variations: ['view'], params: { web: ['thumbBorderColorOff'] } },
    { name: 'thumbBorderColorOn', type: 'color', variations: ['view'], params: { web: ['thumbBorderColorOn'] } },
    { name: 'thumbBorderWidth', type: 'dimension', variations: ['toggleSize'], params: { web: ['thumbBorderWidth'] } },
    { name: 'thumbBackgroundColorOn', type: 'color', variations: ['view'], params: { web: ['thumbBackgroundColorOn'] } },
    { name: 'thumbBackgroundColorOff', type: 'color', variations: ['view'], params: { web: ['thumbBackgroundColorOff'] } },
    { name: 'textStyle', type: 'typography', variations: ['size'], params: { web: ['fontFamily', 'fontStyle', 'fontSize', 'fontWeight', 'letterSpacing', 'lineHeight'] } },
    { name: 'trackBorderColorOn', type: 'color', variations: ['view'], params: { web: ['trackBorderColorOn'] } },
    { name: 'disableAlpha', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'trackBorderColorOff', type: 'color', variations: ['view'], params: { web: ['trackBorderColorOff'] } },
    { name: 'descriptionStyle', type: 'typography', variations: ['size'], params: { web: ['descriptionFontFamily', 'descriptionFontStyle', 'descriptionFontSize', 'descriptionFontWeight', 'descriptionLetterSpacing', 'descriptionLineHeight'] } },
    { name: 'thumbBoxShadow', type: 'shadow', variations: ['view'], params: { web: ['thumbBoxShadow'] } },
    { name: 'descriptionMaxLines', type: 'dimension', variations: ['view'], params: { web: ['descriptionMaxLines'] } },
    { name: 'thumbPressScale', type: 'float', variations: ['toggleSize'], params: { web: ['thumbPressScale'] } },
    { name: 'trackFocusColor', type: 'color', params: { web: ['trackFocusColor'] } },
    { name: 'labelColor', type: 'color', variations: ['view'], params: { web: ['labelColor'] } },
    { name: 'labelOffset', type: 'dimension', variations: ['size'], params: { web: ['labelOffset'] } },
    { name: 'descriptionColor', type: 'color', variations: ['view'], params: { web: ['descriptionColor'] } },
    { name: 'verticalGap', type: 'dimension', variations: ['size'], params: { web: ['verticalGap'] } },
    { name: 'trackWidth', type: 'dimension', variations: ['toggleSize'], params: { web: ['trackWidth'] } },
    { name: 'trackHeight', type: 'dimension', variations: ['toggleSize'], params: { web: ['trackHeight'] } },
    { name: 'trackBorderWidthOn', type: 'dimension', variations: ['view'], params: { web: ['trackBorderWidthOn'] } },
];
