import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'dividerColor', type: 'color', variations: ['view'], params: { web: ['dividerColor'] } },
    { name: 'activeTitleColor', type: 'color', variations: ['itemView'], params: { web: ['activeTitleColor'] } },
    { name: 'activeTitleColorHover', type: 'color', variations: ['itemView'], params: { web: ['activeTitleColorHover'] } },
    { name: 'activeIndicatorBorder', type: 'value', variations: ['itemView'], params: { web: ['activeIndicatorBorder'] } },
    { name: 'activeIndicatorColor', type: 'color', variations: ['itemView'], params: { web: ['activeIndicatorColor'] } },
    { name: 'activeIndicatorBackground', type: 'color', variations: ['itemView'], params: { web: ['activeIndicatorBackground'] } },
    { name: 'completedIndicatorColor', type: 'color', variations: ['itemView'], params: { web: ['completedIndicatorColor'] } },
    { name: 'completedIndicatorColorHover', type: 'color', variations: ['itemView'], params: { web: ['completedIndicatorColorHover'] } },
    { name: 'completedIndicatorBackground', type: 'color', variations: ['itemView'], params: { web: ['completedIndicatorBackground'] } },
    { name: 'completedTitleColor', type: 'color', variations: ['itemView'], params: { web: ['completedTitleColor'] } },
    { name: 'completedTitleColorHover', type: 'color', variations: ['itemView'], params: { web: ['completedTitleColorHover'] } },
    { name: 'titleStyle', type: 'typography', variations: ['size'], params: { web: ['titleFontFamily', 'titleFontSize', 'titleFontStyle', 'titleFontWeight', 'titleLetterSpacing', 'titleLineHeight'] } },
    { name: 'indicatorSize', type: 'dimension', variations: ['size'], params: { web: ['indicatorSize'] } },
    { name: 'completedIndicatorBackgroundHover', type: 'color', variations: ['itemView'], params: { web: ['completedIndicatorBackgroundHover'] } },
    { name: 'inactiveTitleColor', type: 'color', variations: ['itemView'], params: { web: ['inactiveTitleColor'] } },
    { name: 'inactiveTitleColorHover', type: 'color', variations: ['itemView'], params: { web: ['inactiveTitleColorHover'] } },
    { name: 'inactiveIndicatorColor', type: 'color', variations: ['itemView'], params: { web: ['inactiveIndicatorColor'] } },
    { name: 'inactiveIndicatorColorHover', type: 'color', variations: ['itemView'], params: { web: ['inactiveIndicatorColorHover'] } },
    { name: 'inactiveIndicatorBackground', type: 'color', variations: ['itemView'], params: { web: ['inactiveIndicatorBackground'] } },
    { name: 'inactiveIndicatorBackgroundHover', type: 'color', variations: ['itemView'], params: { web: ['inactiveIndicatorBackgroundHover'] } },
    { name: 'contentColor', type: 'color', variations: ['itemView'], params: { web: ['contentColor'] } },
    { name: 'focusColor', type: 'color', variations: ['itemView'], params: { web: ['focusColor'] } },
    { name: 'indicatorStyle', type: 'typography', variations: ['size'], params: { web: ['indicatorFontFamily', 'indicatorFontSize', 'indicatorFontStyle', 'indicatorFontWeight', 'indicatorLetterSpacing', 'indicatorLineHeight'] } },
    { name: 'activeIndicatorStyle', type: 'typography', variations: ['size'], params: { web: ['activeIndicatorFontFamily', 'activeIndicatorFontSize', 'activeIndicatorFontStyle', 'activeIndicatorFontWeight', 'activeIndicatorLetterSpacing', 'activeIndicatorLineHeight'] } },
    { name: 'contentStyle', type: 'typography', variations: ['size'], params: { web: ['contentFontFamily', 'contentFontSize', 'contentFontStyle', 'contentFontWeight', 'contentLetterSpacing', 'contentLineHeight'] } },
    { name: 'disabledOpacity', type: 'float', variations: ['itemView'], params: { web: ['disabledOpacity'] } },
    { name: 'activeIndicatorSize', type: 'dimension', variations: ['size'], params: { web: ['activeIndicatorSize'] } },
    { name: 'bulletSize', type: 'dimension', variations: ['size'], params: { web: ['bulletSize'] } },
    { name: 'activeBulletSize', type: 'dimension', variations: ['size'], params: { web: ['activeBulletSize'] } },
    { name: 'titlePaddingTop', type: 'dimension', variations: ['size'], params: { web: ['titlePaddingTop'] } },
    { name: 'contentPaddingTop', type: 'dimension', variations: ['size'], params: { web: ['contentPaddingTop'] } },
    { name: 'contentSidePadding', type: 'dimension', variations: ['size'], params: { web: ['contentSidePadding'] } },
    { name: 'contentVerticalPadding', type: 'dimension', variations: ['size'], params: { web: ['contentVerticalPadding'] } },
    { name: 'verticalContentPaddingLeft', type: 'dimension', variations: ['size'], params: { web: ['verticalContentPaddingLeft'] } },
    { name: 'dividerThickness', type: 'dimension', variations: ['size'], params: { web: ['dividerThickness'] } },
];
