import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'dividerColor', token: 'surface.default.solid-default' },
        ],
        accent: [
            { prop: 'dividerColor', token: 'surface.default.accent' },
        ],
    },
    itemView: {
        default: [
            { prop: 'activeIndicatorBackground', token: 'surface.default.clear' },
            { prop: 'activeIndicatorBorder', value: 'solid var(--surface-solid-default)' },
            { prop: 'activeTitleColor', token: 'text.default.primary' },
            { prop: 'completedIndicatorBackground', token: 'surface.default.solid-default' },
            { prop: 'completedIndicatorColor', token: 'text.inverse.primary' },
            { prop: 'completedTitleColor', token: 'text.default.primary' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'focusColor', token: 'surface.default.accent' },
            { prop: 'inactiveIndicatorBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'inactiveIndicatorColorHover', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColorHover', token: 'text.default.secondary-hover' },
            { prop: 'activeIndicatorColor', token: 'text.default.primary' },
            { prop: 'activeTitleColorHover', token: 'text.default.primary-hover' },
            { prop: 'completedIndicatorBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'completedIndicatorColorHover', token: 'text.inverse.primary' },
            { prop: 'completedTitleColorHover', token: 'text.default.primary-hover' },
            { prop: 'disabledOpacity', value: '0.4' },
            { prop: 'inactiveIndicatorBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'inactiveIndicatorColor', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColor', token: 'text.default.secondary' },
        ],
        negative: [
            { prop: 'activeIndicatorBorder', value: 'solid var(--surface-negative)' },
            { prop: 'activeTitleColor', token: 'surface.default.negative' },
            { prop: 'completedIndicatorBackground', token: 'surface.default.solid-default' },
            { prop: 'completedIndicatorColor', token: 'text.inverse.primary' },
            { prop: 'completedTitleColor', token: 'text.default.primary' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'focusColor', token: 'surface.default.accent' },
            { prop: 'inactiveIndicatorBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'inactiveIndicatorColorHover', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColorHover', token: 'text.default.secondary-hover' },
            { prop: 'activeIndicatorBackground', token: 'surface.default.clear' },
            { prop: 'activeIndicatorColor', token: 'text.default.negative' },
            { prop: 'activeTitleColorHover', token: 'surface.default.negative-hover' },
            { prop: 'completedIndicatorBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'completedIndicatorColorHover', token: 'text.inverse.primary' },
            { prop: 'completedTitleColorHover', token: 'text.default.primary-hover' },
            { prop: 'disabledOpacity', value: '0.4' },
            { prop: 'inactiveIndicatorBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'inactiveIndicatorColor', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColor', token: 'text.default.secondary' },
        ],
        warning: [
            { prop: 'activeIndicatorBorder', value: 'solid var(--surface-warning)' },
            { prop: 'activeTitleColor', token: 'surface.default.warning' },
            { prop: 'completedIndicatorBackground', token: 'surface.default.solid-default' },
            { prop: 'completedIndicatorColor', token: 'text.inverse.primary' },
            { prop: 'completedTitleColor', token: 'text.default.primary' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'focusColor', token: 'surface.default.accent' },
            { prop: 'inactiveIndicatorBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'inactiveIndicatorColorHover', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColorHover', token: 'text.default.secondary-hover' },
            { prop: 'activeIndicatorBackground', token: 'surface.default.clear' },
            { prop: 'activeIndicatorColor', token: 'text.default.warning' },
            { prop: 'activeTitleColorHover', token: 'surface.default.warning-hover' },
            { prop: 'completedIndicatorBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'completedIndicatorColorHover', token: 'text.inverse.primary' },
            { prop: 'completedTitleColorHover', token: 'text.default.primary-hover' },
            { prop: 'disabledOpacity', value: '0.4' },
            { prop: 'inactiveIndicatorBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'inactiveIndicatorColor', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColor', token: 'text.default.secondary' },
        ],
        positive: [
            { prop: 'activeIndicatorBorder', value: 'solid var(--surface-positive)' },
            { prop: 'activeTitleColor', token: 'surface.default.positive' },
            { prop: 'completedIndicatorBackground', token: 'surface.default.solid-default' },
            { prop: 'completedIndicatorColor', token: 'text.inverse.primary' },
            { prop: 'completedTitleColor', token: 'text.default.primary' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'focusColor', token: 'surface.default.accent' },
            { prop: 'activeIndicatorBackground', token: 'surface.default.clear' },
            { prop: 'activeIndicatorColor', token: 'text.default.positive' },
            { prop: 'activeTitleColorHover', token: 'surface.default.positive-hover' },
            { prop: 'completedIndicatorBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'completedIndicatorColorHover', token: 'text.inverse.primary' },
            { prop: 'completedTitleColorHover', token: 'text.default.primary-hover' },
            { prop: 'disabledOpacity', value: '0.4' },
            { prop: 'inactiveIndicatorBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'inactiveIndicatorColor', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColor', token: 'text.default.secondary' },
            { prop: 'inactiveIndicatorBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'inactiveIndicatorColorHover', token: 'text.default.secondary' },
            { prop: 'inactiveTitleColorHover', token: 'text.default.secondary-hover' },
        ],
    },
    size: {
        xs: [
            { prop: 'activeIndicatorSize', value: '24' },
            { prop: 'bulletSize', value: '8' },
            { prop: 'contentSidePadding', value: '24' },
            { prop: 'contentVerticalPadding', value: '9' },
            { prop: 'indicatorSize', value: '24' },
            { prop: 'titlePaddingTop', value: '8' },
            { prop: 'verticalContentPaddingLeft', value: '12' },
            { prop: 'activeBulletSize', value: '16' },
            { prop: 'activeIndicatorStyle', value: 'body.xs.normal' },
            { prop: 'contentPaddingTop', value: '4' },
            { prop: 'contentStyle', value: 'body.xs.normal' },
            { prop: 'dividerThickness', value: '2' },
            { prop: 'indicatorStyle', value: 'body.xs.normal' },
            { prop: 'titleStyle', value: 'body.xs.normal' },
        ],
        m: [
            { prop: 'activeBulletSize', value: '16' },
            { prop: 'activeIndicatorStyle', value: 'body.s.normal' },
            { prop: 'contentPaddingTop', value: '6' },
            { prop: 'contentStyle', value: 'body.s.normal' },
            { prop: 'dividerThickness', value: '2' },
            { prop: 'indicatorStyle', value: 'body.xs.normal' },
            { prop: 'activeIndicatorSize', value: '36' },
            { prop: 'bulletSize', value: '8' },
            { prop: 'contentSidePadding', value: '28' },
            { prop: 'contentVerticalPadding', value: '14' },
            { prop: 'indicatorSize', value: '24' },
            { prop: 'titlePaddingTop', value: '10' },
            { prop: 'verticalContentPaddingLeft', value: '12' },
            { prop: 'titleStyle', value: 'body.m.normal' },
        ],
        s: [
            { prop: 'activeIndicatorSize', value: '24' },
            { prop: 'bulletSize', value: '8' },
            { prop: 'contentSidePadding', value: '24' },
            { prop: 'contentVerticalPadding', value: '11' },
            { prop: 'indicatorSize', value: '24' },
            { prop: 'titlePaddingTop', value: '8' },
            { prop: 'verticalContentPaddingLeft', value: '12' },
            { prop: 'activeBulletSize', value: '16' },
            { prop: 'activeIndicatorStyle', value: 'body.xs.normal' },
            { prop: 'contentPaddingTop', value: '6' },
            { prop: 'contentStyle', value: 'body.xs.normal' },
            { prop: 'dividerThickness', value: '2' },
            { prop: 'indicatorStyle', value: 'body.xs.normal' },
            { prop: 'titleStyle', value: 'body.s.normal' },
        ],
        l: [
            { prop: 'activeBulletSize', value: '16' },
            { prop: 'activeIndicatorStyle', value: 'body.s.normal' },
            { prop: 'contentPaddingTop', value: '6' },
            { prop: 'contentStyle', value: 'body.m.normal' },
            { prop: 'dividerThickness', value: '2' },
            { prop: 'indicatorStyle', value: 'body.xs.normal' },
            { prop: 'titleStyle', value: 'body.l.normal' },
            { prop: 'activeIndicatorSize', value: '36' },
            { prop: 'bulletSize', value: '8' },
            { prop: 'contentSidePadding', value: '32' },
            { prop: 'contentVerticalPadding', value: '17' },
            { prop: 'indicatorSize', value: '24' },
            { prop: 'titlePaddingTop', value: '12' },
            { prop: 'verticalContentPaddingLeft', value: '12' },
        ],
    },
};
