import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.solid-default-hover' },
            { prop: 'buttonColorActive', token: 'text.inverse.primary' },
            { prop: 'buttonIconColor', token: 'text.inverse.primary' },
            { prop: 'buttonTextColor', token: 'text.inverse.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.solid-default-active' },
            { prop: 'buttonColor', token: 'text.inverse.primary' },
            { prop: 'buttonColorHover', token: 'text.inverse.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.inverse.secondary' },
        ],
        accent: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.accent' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.accent-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary' },
            { prop: 'buttonIconColor', token: 'text.on-dark.primary' },
            { prop: 'buttonTextColor', token: 'text.on-dark.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.accent-active' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-dark.secondary' },
        ],
        secondary: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'buttonColorActive', token: 'text.default.primary' },
            { prop: 'buttonIconColor', token: 'text.default.primary' },
            { prop: 'buttonTextColor', token: 'text.default.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.transparent-secondary-active' },
            { prop: 'buttonColor', token: 'text.default.primary' },
            { prop: 'buttonColorHover', token: 'text.default.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.default.secondary' },
        ],
        clear: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.clear' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.clear' },
            { prop: 'buttonColorActive', token: 'text.default.primary-active' },
            { prop: 'buttonIconColor', token: 'text.default.primary' },
            { prop: 'buttonTextColor', token: 'text.default.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.clear' },
            { prop: 'buttonColor', token: 'text.default.primary' },
            { prop: 'buttonColorHover', token: 'text.default.primary-hover' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.default.secondary' },
        ],
        success: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.positive' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.positive-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary' },
            { prop: 'buttonIconColor', token: 'text.on-dark.primary' },
            { prop: 'buttonTextColor', token: 'text.on-dark.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.positive-active' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-dark.secondary' },
        ],
        warning: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.warning' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.warning-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary' },
            { prop: 'buttonIconColor', token: 'text.on-dark.primary' },
            { prop: 'buttonTextColor', token: 'text.on-dark.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.warning-active' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-dark.secondary' },
        ],
        critical: [
            { prop: 'buttonBackgroundColor', token: 'surface.default.negative' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.negative-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary' },
            { prop: 'buttonIconColor', token: 'text.on-dark.primary' },
            { prop: 'buttonTextColor', token: 'text.on-dark.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.negative-active' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-dark.secondary' },
        ],
        dark: [
            { prop: 'buttonBackgroundColor', token: 'surface.on-light.transparent-deep' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.on-light.transparent-deep-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary' },
            { prop: 'buttonIconColor', token: 'text.on-dark.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.on-light.transparent-deep-active' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonTextColor', token: 'text.on-dark.primary' },
        ],
        black: [
            { prop: 'buttonBackgroundColorActive', token: 'surface.on-light.solid-default-active' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary' },
            { prop: 'buttonBackgroundColor', token: 'surface.on-light.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.on-light.solid-default-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary' },
            { prop: 'buttonIconColor', token: 'text.on-dark.primary' },
            { prop: 'buttonTextColor', token: 'text.on-dark.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-dark.secondary' },
        ],
        white: [
            { prop: 'buttonBackgroundColor', token: 'surface.on-dark.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.on-dark.solid-default-hover' },
            { prop: 'buttonColorActive', token: 'text.on-light.primary' },
            { prop: 'buttonIconColor', token: 'text.on-light.primary' },
            { prop: 'buttonTextColor', token: 'text.on-light.primary' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.on-dark.solid-default-active' },
            { prop: 'buttonColor', token: 'text.on-light.primary' },
            { prop: 'buttonColorHover', token: 'text.on-light.primary' },
            { prop: 'buttonLoadingBackgroundColor', value: 'var(${buttonGroupTokens.buttonBackgroundColor})' },
            { prop: 'buttonValueColor', token: 'text.on-light.secondary' },
        ],
    },
    size: {
        xl: [
            { prop: 'buttonDefaultRadius', value: '16' },
            { prop: 'buttonPadding', value: '28' },
            { prop: 'buttonSideRadius', value: '16' },
            { prop: 'buttonHeight', value: '64' },
            { prop: 'buttonSegmentedRadius', value: '8' },
            { prop: 'buttonStyle', value: 'body.l.bold' },
        ],
        l: [
            { prop: 'buttonDefaultRadius', value: '14' },
            { prop: 'buttonPadding', value: '24' },
            { prop: 'buttonSideRadius', value: '14' },
            { prop: 'buttonHeight', value: '56' },
            { prop: 'buttonSegmentedRadius', value: '6' },
            { prop: 'buttonStyle', value: 'body.l.bold' },
        ],
        m: [
            { prop: 'buttonDefaultRadius', value: '12' },
            { prop: 'buttonPadding', value: '20' },
            { prop: 'buttonSideRadius', value: '12' },
            { prop: 'buttonHeight', value: '48' },
            { prop: 'buttonSegmentedRadius', value: '4' },
            { prop: 'buttonStyle', value: 'body.m.bold' },
        ],
        s: [
            { prop: 'buttonDefaultRadius', value: '10' },
            { prop: 'buttonPadding', value: '16' },
            { prop: 'buttonHeight', value: '40' },
            { prop: 'buttonSegmentedRadius', value: '4' },
            { prop: 'buttonStyle', value: 'body.s.bold' },
            { prop: 'buttonSideRadius', value: '10' },
        ],
        xs: [
            { prop: 'buttonHeight', value: '32' },
            { prop: 'buttonSegmentedRadius', value: '2' },
            { prop: 'buttonDefaultRadius', value: '8' },
            { prop: 'buttonPadding', value: '12' },
            { prop: 'buttonSideRadius', value: '8' },
            { prop: 'buttonStyle', value: 'body.xs.bold' },
        ],
        xxs: [
            { prop: 'buttonDefaultRadius', value: '6' },
            { prop: 'buttonPadding', value: '10' },
            { prop: 'buttonSideRadius', value: '6' },
            { prop: 'buttonHeight', value: '24' },
            { prop: 'buttonSegmentedRadius', value: '2' },
            { prop: 'buttonStyle', value: 'body.xs.bold' },
        ],
    },
    orientation: {
        horizontal: [
            { prop: 'buttonGroupOrientation', value: 'row' },
        ],
        vertical: [
            { prop: 'buttonGroupOrientation', value: 'column' },
        ],
    },
    gap: {
        none: [
            { prop: 'buttonGroupItemsGap', value: '0' },
        ],
        dense: [
            { prop: 'buttonGroupItemsGap', value: '2' },
        ],
        wide: [
            { prop: 'buttonGroupItemsGap', value: '8' },
        ],
    },
};
