import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'captionColor', token: 'text.default.secondary' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        secondary: [
            { prop: 'captionColor', token: 'text.default.secondary' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        accent: [
            { prop: 'captionColor', token: 'text.default.secondary' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.accent' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        accentGradient: [
            { prop: 'captionColor', token: 'text.default.secondary' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.accent-gradient' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        info: [
            { prop: 'captionColor', token: 'text.default.secondary' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.info' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        positive: [
            { prop: 'captionColor', token: 'text.default.positive' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.positive' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        warning: [
            { prop: 'captionColor', token: 'text.default.warning' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.warning' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        negative: [
            { prop: 'captionColor', token: 'text.default.negative' },
            { prop: 'labelIconColor', token: 'text.default.primary' },
            { prop: 'trackBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'progressFilledBackgroundColor', token: 'surface.default.negative' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
    },
    size: {
        l: [
            { prop: 'captionMarginTop', value: '8' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'labelWrapperMarginRight', value: '24' },
            { prop: 'valueMarginLeft', value: '24' },
            { prop: 'captionStyle', value: 'body.xs.normal' },
            { prop: 'labelWrapperGap', value: '6' },
            { prop: 'topRowMarginBottom', value: '20' },
            { prop: 'valueStyle', value: 'body.l.normal' },
        ],
        m: [
            { prop: 'captionMarginTop', value: '8' },
            { prop: 'labelStyle', value: 'body.m.normal' },
            { prop: 'labelWrapperMarginRight', value: '20' },
            { prop: 'valueMarginLeft', value: '20' },
            { prop: 'captionStyle', value: 'body.xs.normal' },
            { prop: 'labelWrapperGap', value: '6' },
            { prop: 'topRowMarginBottom', value: '16' },
            { prop: 'valueStyle', value: 'body.m.normal' },
        ],
        s: [
            { prop: 'captionMarginTop', value: '8' },
            { prop: 'labelStyle', value: 'body.s.normal' },
            { prop: 'captionStyle', value: 'body.xs.normal' },
            { prop: 'labelWrapperGap', value: '6' },
            { prop: 'topRowMarginBottom', value: '14' },
            { prop: 'labelWrapperMarginRight', value: '16' },
            { prop: 'valueMarginLeft', value: '16' },
            { prop: 'valueStyle', value: 'body.s.normal' },
        ],
    },
    progressSize: {
        '2': [
            { prop: 'progressFilledBorderRadius', token: 'round.circle' },
            { prop: 'trackBorderRadius', token: 'round.circle' },
            { prop: 'progressFilledHeight', value: '2' },
            { prop: 'trackHeight', value: '2' },
        ],
        '4': [
            { prop: 'progressFilledBorderRadius', token: 'round.circle' },
            { prop: 'trackBorderRadius', token: 'round.circle' },
            { prop: 'progressFilledHeight', value: '4' },
            { prop: 'trackHeight', value: '4' },
        ],
        '6': [
            { prop: 'progressFilledBorderRadius', token: 'round.circle' },
            { prop: 'trackBorderRadius', token: 'round.circle' },
            { prop: 'progressFilledHeight', value: '6' },
            { prop: 'trackHeight', value: '6' },
        ],
        '8': [
            { prop: 'progressFilledBorderRadius', token: 'round.circle' },
            { prop: 'trackBorderRadius', token: 'round.circle' },
            { prop: 'progressFilledHeight', value: '8' },
            { prop: 'trackHeight', value: '8' },
        ],
    },
};
