import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'horizontalLayoutGap', type: 'dimension', variations: ['size'], params: { web: ['horizontalLayoutGap'] } },
    { name: 'horizontalLayoutLeftIconMargin', type: 'dimension', variations: ['size'], params: { web: ['horizontalLayoutLeftIconMargin'] } },
    { name: 'closeIconTop', type: 'dimension', variations: ['size'], params: { web: ['closeIconTop'] } },
    { name: 'contentStyle', type: 'typography', variations: ['size'], params: { web: ['contentFontFamily', 'contentFontSize', 'contentFontStyle', 'contentFontWeight', 'contentFontLetterSpacing', 'contentFontLineHeight'] } },
    { name: 'titleStyle', type: 'typography', variations: ['size'], params: { web: ['titleFontFamily', 'titleFontSize', 'titleFontStyle', 'titleFontWeight', 'titleFontLetterSpacing', 'titleFontLineHeight'] } },
    { name: 'padding', type: 'value', variations: ['layout', 'size'], params: { web: ['padding'] } },
    { name: 'width', type: 'dimension', variations: ['layout'], params: { web: ['width'] } },
    { name: 'closeIconButtonSize', type: 'dimension', variations: ['closeIconType'], params: { web: ['closeIconButtonSize'] } },
    { name: 'closeIconSize', type: 'dimension', variations: ['closeIconType'], params: { web: ['closeIconSize'] } },
    { name: 'contentPaddingTopWithoutIcon', type: 'dimension', variations: ['size'], params: { web: ['contentPaddingTopWithoutIcon'] } },
    { name: 'horizontalLayoutRightPaddingWithoutCloseIcon', type: 'dimension', variations: ['size'], params: { web: ['horizontalLayoutRightPaddingWithoutCloseIcon'] } },
    { name: 'textboxPaddingTop', type: 'dimension', variations: ['size'], params: { web: ['textboxPaddingTop'] } },
    { name: 'textboxPaddingRight', type: 'dimension', variations: ['size'], params: { web: ['textboxPaddingRight'] } },
    { name: 'textboxPaddingBottom', type: 'dimension', variations: ['size'], params: { web: ['textboxPaddingBottom'] } },
    { name: 'titleColor', type: 'color', variations: ['view'], params: { web: ['titleColor'] } },
    { name: 'contentLeftIconColor', type: 'color', variations: ['view'], params: { web: ['contentLeftIconColor'] } },
    { name: 'contentColor', type: 'color', variations: ['view'], params: { web: ['contentColor'] } },
    { name: 'background', type: 'color', variations: ['view'], params: { web: ['background'] } },
    { name: 'closeIconColor', type: 'color', variations: ['view'], params: { web: ['closeIconColor'] } },
    { name: 'contentLeftIconMargin', type: 'dimension', variations: ['size'], params: { web: ['contentLeftIconMargin'] } },
    { name: 'contentTopIconMargin', type: 'dimension', variations: ['size'], params: { web: ['contentTopIconMargin'] } },
    { name: 'closeIconColorOnHover', type: 'color', variations: ['view'], params: { web: ['closeIconColorOnHover'] } },
    { name: 'textboxPaddingLeft', type: 'dimension', variations: ['size'], params: { web: ['textboxPaddingLeft'] } },
    { name: 'textboxPaddingRightWithCloseIcon', type: 'dimension', variations: ['size'], params: { web: ['textboxPaddingRightWithCloseIcon'] } },
    { name: 'textboxGap', type: 'dimension', variations: ['size'], params: { web: ['textboxGap'] } },
    { name: 'buttonsMarginTop', type: 'dimension', variations: ['size'], params: { web: ['buttonsMarginTop'] } },
    { name: 'contentLeftIconSize', type: 'dimension', variations: ['size'], params: { web: ['contentLeftIconSize'] } },
    { name: 'closeIconRight', type: 'dimension', variations: ['size'], params: { web: ['closeIconRight'] } },
    { name: 'paddingOneLineTextbox', type: 'dimension', variations: ['size'], params: { web: ['paddingOneLineTextbox'] } },
    { name: 'textboxPaddingTopWithTopIcon', type: 'dimension', variations: ['size'], params: { web: ['textboxPaddingTopWithTopIcon'] } },
    { name: 'contentPaddingTop', type: 'dimension', variations: ['size'], params: { web: ['contentPaddingTop'] } },
    { name: 'contentPaddingRight', type: 'dimension', variations: ['size'], params: { web: ['contentPaddingRight'] } },
    { name: 'contentPaddingBottom', type: 'dimension', variations: ['size'], params: { web: ['contentPaddingBottom'] } },
    { name: 'contentPaddingLeft', type: 'dimension', variations: ['size'], params: { web: ['contentPaddingLeft'] } },
    { name: 'buttonsMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['buttonsMarginLeft'] } },
    { name: 'borderRadius', type: 'shape', variations: ['size'], params: { web: ['borderRadius'] } },
    { name: 'horizontalLayoutPadding', type: 'dimension', variations: ['layout'], params: { web: ['horizontalLayoutPadding'] } },
];
