import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        warning: [
            { prop: 'titleColor', token: 'text.default.warning' },
            { prop: 'contentLeftIconColor', token: 'text.default.warning' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'background', token: 'surface.default.transparent-card' },
            { prop: 'closeIconColor', token: 'text.default.tertiary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.primary' },
        ],
        default: [
            { prop: 'titleColor', token: 'text.default.primary' },
            { prop: 'contentLeftIconColor', token: 'text.default.primary' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'background', token: 'surface.default.transparent-card' },
            { prop: 'closeIconColor', token: 'text.default.tertiary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.primary' },
        ],
        negative: [
            { prop: 'titleColor', token: 'text.default.negative' },
            { prop: 'contentLeftIconColor', token: 'text.default.negative' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'background', token: 'surface.default.transparent-card' },
            { prop: 'closeIconColor', token: 'text.default.tertiary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.primary' },
        ],
        positive: [
            { prop: 'titleColor', token: 'text.default.positive' },
            { prop: 'contentLeftIconColor', token: 'text.default.positive' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'background', token: 'surface.default.transparent-card' },
            { prop: 'closeIconColor', token: 'text.default.tertiary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.primary' },
        ],
        info: [
            { prop: 'titleColor', token: 'text.default.info' },
            { prop: 'contentLeftIconColor', token: 'text.default.info' },
            { prop: 'contentColor', token: 'text.default.secondary' },
            { prop: 'background', token: 'surface.default.transparent-card' },
            { prop: 'closeIconColor', token: 'text.default.tertiary' },
            { prop: 'closeIconColorOnHover', token: 'text.default.primary' },
        ],
    },
    layout: {
        horizontal: [
            { prop: 'width', value: '400' },
            { prop: 'horizontalLayoutPadding', value: '16', adjust: [{ platform: 'web', param: 'horizontalLayoutPadding', template: '$1 0.5rem 1rem 0.875rem' }] },
        ],
        vertical: [
            { prop: 'padding', value: '0.375rem' },
            { prop: 'width', value: '240' },
        ],
    },
    closeIconType: {
        default: [
            { prop: 'closeIconButtonSize', value: '24' },
            { prop: 'closeIconSize', value: '24' },
        ],
    },
    size: {
        xs: [
            { prop: 'padding', value: '0.375rem' },
            { prop: 'contentPaddingTopWithoutIcon', value: '4' },
            { prop: 'horizontalLayoutRightPaddingWithoutCloseIcon', value: '16' },
            { prop: 'textboxPaddingTop', value: '3' },
            { prop: 'textboxPaddingRight', value: '2' },
            { prop: 'textboxPaddingBottom', value: '6' },
            { prop: 'textboxPaddingLeft', value: '2' },
            { prop: 'textboxPaddingRightWithCloseIcon', value: '26' },
            { prop: 'textboxGap', value: '4' },
            { prop: 'buttonsMarginTop', value: '6' },
            { prop: 'contentLeftIconSize', value: '24' },
            { prop: 'contentLeftIconMargin', value: '6' },
            { prop: 'contentTopIconMargin', value: '8' },
            { prop: 'horizontalLayoutGap', value: '6' },
            { prop: 'horizontalLayoutLeftIconMargin', value: '12' },
            { prop: 'closeIconTop', value: '8' },
            { prop: 'closeIconRight', value: '8' },
            { prop: 'textboxPaddingTopWithTopIcon', value: '0' },
            { prop: 'contentPaddingTop', value: '2' },
            { prop: 'contentPaddingRight', value: '4' },
            { prop: 'contentPaddingBottom', value: '0' },
            { prop: 'contentPaddingLeft', value: '4' },
            { prop: 'buttonsMarginLeft', value: '0' },
            { prop: 'contentStyle', value: 'body.s.normal' },
            { prop: 'titleStyle', value: 'body.s.bold' },
            { prop: 'borderRadius', token: 'round.m' },
            { prop: 'paddingOneLineTextbox', value: '13', adjust: [{ platform: 'web', param: 'paddingOneLineTextbox', template: '$1 0.5rem 0.8125rem 0.875rem' }] },
        ],
        xxs: [
            { prop: 'padding', value: '0.5625rem 1rem 1rem 1rem' },
            { prop: 'contentPaddingTopWithoutIcon', value: '4' },
            { prop: 'horizontalLayoutRightPaddingWithoutCloseIcon', value: '16' },
            { prop: 'textboxPaddingTop', value: '3' },
            { prop: 'textboxPaddingRight', value: '2' },
            { prop: 'textboxPaddingBottom', value: '6' },
            { prop: 'textboxPaddingLeft', value: '2' },
            { prop: 'textboxPaddingRightWithCloseIcon', value: '26' },
            { prop: 'textboxGap', value: '4' },
            { prop: 'buttonsMarginTop', value: '6' },
            { prop: 'contentLeftIconSize', value: '24' },
            { prop: 'contentLeftIconMargin', value: '6' },
            { prop: 'contentTopIconMargin', value: '8' },
            { prop: 'horizontalLayoutGap', value: '6' },
            { prop: 'horizontalLayoutLeftIconMargin', value: '12' },
            { prop: 'closeIconTop', value: '13' },
            { prop: 'closeIconRight', value: '16' },
            { prop: 'textboxPaddingTopWithTopIcon', value: '3' },
            { prop: 'contentPaddingTop', value: '4' },
            { prop: 'contentPaddingRight', value: '0' },
            { prop: 'contentPaddingBottom', value: '0' },
            { prop: 'contentPaddingLeft', value: '0' },
            { prop: 'buttonsMarginLeft', value: '32' },
            { prop: 'contentStyle', value: 'body.s.normal' },
            { prop: 'titleStyle', value: 'body.s.bold' },
            { prop: 'borderRadius', token: 'round.m' },
            { prop: 'paddingOneLineTextbox', value: '13', adjust: [{ platform: 'web', param: 'paddingOneLineTextbox', template: '$1 0.5rem 0.8125rem 0.875rem' }] },
        ],
    },
};
