import type { ComponentPreviewDraft } from './draft';

export const createPreviewDraftFixture = (): ComponentPreviewDraft => ({
    componentId: 'BasicButton',
    storyId: 'BasicButton',
    rendererPlatform: 'COMPOSE',
    themeValuePlatform: 'web',
    themeMode: 'light',
    componentRevision: 1,
    themeRevision: 1,
    variationSelections: { customAxis: 'rounded' },
    invariantProperties: [
        {
            id: 'background',
            name: 'backgroundColor',
            type: 'color',
            composeParameters: ['backgroundColor'],
            value: 'color.background',
            states: [{ names: ['pressed'], value: 'color.pressed' }],
        },
        {
            id: 'alpha',
            name: 'disabledAlpha',
            type: 'float',
            composeParameters: ['disabledAlpha'],
            value: 0.3,
            states: [],
            adjustment: 0.1,
        },
        {
            id: 'shape',
            name: 'shape',
            type: 'shape',
            composeParameters: ['shape'],
            value: 'shape.button',
            states: [],
        },
        {
            id: 'height',
            name: 'height',
            type: 'dimension',
            composeParameters: ['height'],
            value: 'size.height',
            states: [],
        },
        {
            id: 'padding-start',
            name: 'paddingStart',
            type: 'dimension',
            composeParameters: ['paddings'],
            value: 'size.padding',
            states: [],
        },
        {
            id: 'padding-end',
            name: 'paddingEnd',
            type: 'dimension',
            composeParameters: ['paddings'],
            value: 'size.padding',
            states: [],
        },
        {
            id: 'content',
            name: 'contentColor',
            type: 'color',
            composeParameters: ['contentColor'],
            value: 'color.content',
            states: [],
        },
    ],
    selectedStyleProperties: [
        {
            id: 'label',
            name: 'labelStyle',
            type: 'typography',
            composeParameters: ['labelStyle'],
            value: 'typography.button',
            states: [],
        },
    ],
    themeTokens: [
        { id: 'light.color.background', type: 'color', enabled: true, values: { web: '#123456' } },
        { id: 'light.color.pressed', type: 'color', enabled: true, values: { web: '#000000FF' } },
        { id: 'light.color.content', type: 'color', enabled: true, values: { web: '#FFFFFFFF' } },
        { id: 'size.height', type: 'dimension', enabled: true, values: { web: 48 } },
        { id: 'size.padding', type: 'dimension', enabled: true, values: { web: 20 } },
        { id: 'shape.button', type: 'shape', enabled: true, values: { web: 12 } },
        {
            id: 'screen-s.typography.button',
            type: 'typography',
            enabled: true,
            values: {
                web: {
                    fontFamilyRef: 'font.body',
                    fontSize: 16,
                    lineHeight: 20,
                    letterSpacing: 0,
                    fontWeight: 400,
                },
            },
        },
        {
            id: 'font.body',
            type: 'fontFamily',
            enabled: true,
            values: {
                web: {
                    name: 'Body',
                    fonts: [{ src: ['https://cdn.example/body.ttf'], fontWeight: '400', fontStyle: 'normal' }],
                },
            },
        },
    ],
    assets: [],
    example: { id: 'BasicButton', props: { label: 'Hello', loading: false, enabled: true } },
    surface: { width: 360, height: 160, background: '#FFFFFFFF' },
});
