import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'chipBackground', token: 'surface.default.solid-default' },
            { prop: 'chipBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'chipColorActive', token: 'text.inverse.primary' },
            { prop: 'chipFocusColor', token: 'surface.default.accent' },
            { prop: 'chipBackgroundActive', token: 'surface.default.solid-default-active' },
            { prop: 'chipColor', token: 'text.inverse.primary' },
            { prop: 'chipColorHover', token: 'text.inverse.primary' },
        ],
        secondary: [
            { prop: 'chipBackgroundActive', token: 'surface.default.transparent-secondary-active' },
            { prop: 'chipColor', token: 'text.default.primary' },
            { prop: 'chipColorHover', token: 'text.default.primary' },
            { prop: 'chipBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'chipColorActive', token: 'text.default.primary' },
            { prop: 'chipFocusColor', token: 'surface.default.accent' },
        ],
        accent: [
            { prop: 'chipBackground', token: 'surface.default.accent' },
            { prop: 'chipBackgroundHover', token: 'surface.default.accent-hover' },
            { prop: 'chipColorActive', token: 'text.on-dark.primary' },
            { prop: 'chipFocusColor', token: 'surface.default.accent' },
            { prop: 'chipBackgroundActive', token: 'surface.default.accent-active' },
            { prop: 'chipColor', token: 'text.on-dark.primary' },
            { prop: 'chipColorHover', token: 'text.on-dark.primary' },
        ],
    },
    size: {
        l: [
            { prop: 'chipClearContentMarginLeft', value: '10' },
            { prop: 'chipCloseIconSize', value: '24' },
            { prop: 'chipHeight', value: '48' },
            { prop: 'chipLeftContentMarginRight', value: '8' },
            { prop: 'chipRightContentMarginRight', value: '-2' },
            { prop: 'chipSideRadius', value: '12' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'chipBorderRadius', value: '12' },
            { prop: 'chipClearContentMarginRight', value: '-4' },
            { prop: 'chipDefaultRadius', value: '12' },
            { prop: 'chipLeftContentMarginLeft', value: '-2' },
            { prop: 'chipPadding', value: '16', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1' }] },
            { prop: 'chipRightContentMarginLeft', value: '8' },
            { prop: 'chipSegmentedRadius', value: '6' },
            { prop: 'chipStyle', value: 'body.l.normal' },
        ],
        m: [
            { prop: 'chipClearContentMarginLeft', value: '8' },
            { prop: 'chipCloseIconSize', value: '16' },
            { prop: 'chipHeight', value: '40' },
            { prop: 'chipLeftContentMarginRight', value: '6' },
            { prop: 'chipRightContentMarginRight', value: '-2' },
            { prop: 'chipSideRadius', value: '10' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'chipBorderRadius', value: '10' },
            { prop: 'chipClearContentMarginRight', value: '-4' },
            { prop: 'chipDefaultRadius', value: '10' },
            { prop: 'chipLeftContentMarginLeft', value: '-2' },
            { prop: 'chipPadding', value: '14', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1' }] },
            { prop: 'chipRightContentMarginLeft', value: '6' },
            { prop: 'chipSegmentedRadius', value: '4' },
            { prop: 'chipStyle', value: 'body.m.normal' },
        ],
        s: [
            { prop: 'chipClearContentMarginLeft', value: '6' },
            { prop: 'chipCloseIconSize', value: '16' },
            { prop: 'chipHeight', value: '32' },
            { prop: 'chipLeftContentMarginRight', value: '4' },
            { prop: 'chipRightContentMarginRight', value: '-2' },
            { prop: 'chipSideRadius', value: '8' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'chipBorderRadius', value: '8' },
            { prop: 'chipClearContentMarginRight', value: '-4' },
            { prop: 'chipDefaultRadius', value: '8' },
            { prop: 'chipLeftContentMarginLeft', value: '-2' },
            { prop: 'chipPadding', value: '14', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1' }] },
            { prop: 'chipRightContentMarginLeft', value: '4' },
            { prop: 'chipSegmentedRadius', value: '4' },
            { prop: 'chipStyle', value: 'body.s.normal' },
        ],
        xs: [
            { prop: 'chipClearContentMarginLeft', value: '4' },
            { prop: 'chipCloseIconSize', value: '16' },
            { prop: 'chipHeight', value: '24' },
            { prop: 'chipLeftContentMarginRight', value: '4' },
            { prop: 'chipRightContentMarginRight', value: '-2' },
            { prop: 'chipSideRadius', value: '6' },
            { prop: 'chipBorderRadius', value: '6' },
            { prop: 'chipClearContentMarginRight', value: '-4' },
            { prop: 'chipDefaultRadius', value: '6' },
            { prop: 'chipLeftContentMarginLeft', value: '-2' },
            { prop: 'chipPadding', value: '10', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1' }] },
            { prop: 'chipRightContentMarginLeft', value: '4' },
            { prop: 'chipSegmentedRadius', value: '2' },
            { prop: 'chipStyle', value: 'body.xs.normal' },
            { prop: 'chipWidth', value: 'auto' },
        ],
    },
    gap: {
        dense: [
            { prop: 'chipGroupItemsGap', value: '2' },
        ],
        wide: [
            { prop: 'chipGroupItemsGap', value: '8' },
        ],
    },
};
