import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'textStyle', type: 'typography', variations: ['size'], params: { web: ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'letterSpacing', 'lineHeight'] } },
    { name: 'labelStyle', type: 'typography', variations: ['size'], params: { web: ['labelFontFamily', 'labelFontSize', 'labelFontStyle', 'labelFontWeight', 'labelLetterSpacing', 'labelLineHeight'] } },
    { name: 'leftHelperStyle', type: 'typography', variations: ['size'], params: { web: ['leftHelperFontFamily', 'leftHelperFontSize', 'leftHelperFontStyle', 'leftHelperFontWeight', 'leftHelperLetterSpacing', 'leftHelperLineHeight'] } },
    { name: 'chipWidth', type: 'value', variations: ['size'], params: { web: ['chipWidth'] } },
    { name: 'chipStyle', type: 'typography', variations: ['size'], params: { web: ['chipFontFamily', 'chipFontSize', 'chipFontStyle', 'chipFontWeight', 'chipLetterSpacing', 'chipLineHeight'] } },
    { name: 'textFieldGroupOrientation', type: 'value', variations: ['orientation'], params: { web: ['textFieldGroupOrientation'] } },
    { name: 'height', type: 'dimension', variations: ['size'], params: { web: ['height'] } },
    { name: 'paddingWithChips', type: 'dimension', variations: ['size'], params: { web: ['paddingWithChips'] } },
    { name: 'labelOffset', type: 'dimension', variations: ['size'], params: { web: ['labelOffset'] } },
    { name: 'chipGap', type: 'dimension', variations: ['size'], params: { web: ['chipGap'] } },
    { name: 'padding', type: 'dimension', variations: ['size'], params: { web: ['padding'] } },
    { name: 'leftContentMargin', type: 'dimension', variations: ['size'], params: { web: ['leftContentMargin'] } },
    { name: 'rightContentMargin', type: 'dimension', variations: ['size'], params: { web: ['rightContentMargin'] } },
    { name: 'textBeforeMargin', type: 'dimension', variations: ['size'], params: { web: ['textBeforeMargin'] } },
    { name: 'textAfterMargin', type: 'dimension', variations: ['size'], params: { web: ['textAfterMargin'] } },
    { name: 'leftHelperOffset', type: 'dimension', variations: ['size'], params: { web: ['leftHelperOffset'] } },
    { name: 'labelInnerPadding', type: 'dimension', variations: ['size'], params: { web: ['labelInnerPadding'] } },
    { name: 'contentLabelInnerPadding', type: 'dimension', variations: ['size'], params: { web: ['contentLabelInnerPadding'] } },
    { name: 'chipPadding', type: 'dimension', variations: ['size'], params: { web: ['chipPadding'] } },
    { name: 'chipHeight', type: 'dimension', variations: ['size'], params: { web: ['chipHeight'] } },
    { name: 'chipClearContentMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['chipClearContentMarginLeft'] } },
    { name: 'chipClearContentMarginRight', type: 'dimension', variations: ['size'], params: { web: ['chipClearContentMarginRight'] } },
    { name: 'chipCloseIconSize', type: 'dimension', variations: ['size'], params: { web: ['chipCloseIconSize'] } },
    { name: 'textFieldGroupItemsGap', type: 'dimension', variations: ['gap'], params: { web: ['textFieldGroupItemsGap'] } },
    { name: 'textFieldDefaultRadius', type: 'dimension', variations: ['size'], params: { web: ['textFieldDefaultRadius'] } },
    { name: 'textFieldSegmentedRadius', type: 'dimension', variations: ['size'], params: { web: ['textFieldSegmentedRadius'] } },
    { name: 'textFieldSideRadius', type: 'dimension', variations: ['size'], params: { web: ['textFieldSideRadius'] } },
    { name: 'chipBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['chipBorderRadius'] } },
];
