import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    size: {
        l: [
            { prop: 'chipBorderRadius', value: '8' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipPadding', value: '12', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'chipStyle', value: 'body.l.normal' },
            { prop: 'contentLabelInnerPadding', value: '25', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'height', value: '56' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'padding', value: '17', adjust: [{ platform: 'web', param: 'padding', template: '$1 1rem $1 1rem' }] },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'textFieldSegmentedRadius', value: '6' },
            { prop: 'textStyle', value: 'body.l.normal' },
            { prop: 'chipClearContentMarginLeft', value: '10' },
            { prop: 'chipCloseIconSize', value: '24' },
            { prop: 'chipHeight', value: '44' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'labelInnerPadding', value: '9', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'labelOffset', value: '12' },
            { prop: 'leftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldDefaultRadius', value: '14' },
            { prop: 'textFieldSideRadius', value: '14' },
        ],
        m: [
            { prop: 'chipClearContentMarginLeft', value: '8' },
            { prop: 'chipCloseIconSize', value: '20' },
            { prop: 'chipHeight', value: '36' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'labelInnerPadding', value: '6', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'labelOffset', value: '10' },
            { prop: 'leftContentMargin', value: '6', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightContentMargin', value: '-2', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldDefaultRadius', value: '12' },
            { prop: 'textFieldSideRadius', value: '12' },
            { prop: 'chipBorderRadius', value: '6' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipPadding', value: '10', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'chipStyle', value: 'body.m.normal' },
            { prop: 'contentLabelInnerPadding', value: '22', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'height', value: '48' },
            { prop: 'labelStyle', value: 'body.m.normal' },
            { prop: 'padding', value: '14', adjust: [{ platform: 'web', param: 'padding', template: '$1 1rem $1 1rem' }] },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'textFieldSegmentedRadius', value: '4' },
            { prop: 'textStyle', value: 'body.m.normal' },
        ],
        s: [
            { prop: 'chipBorderRadius', value: '4' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipPadding', value: '8', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'chipStyle', value: 'body.s.normal' },
            { prop: 'contentLabelInnerPadding', value: '17', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'height', value: '40' },
            { prop: 'labelStyle', value: 'body.s.normal' },
            { prop: 'padding', value: '11', adjust: [{ platform: 'web', param: 'padding', template: '$1 1rem $1 1rem' }] },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'textFieldSegmentedRadius', value: '4' },
            { prop: 'textStyle', value: 'body.s.normal' },
            { prop: 'chipClearContentMarginLeft', value: '6' },
            { prop: 'chipCloseIconSize', value: '16' },
            { prop: 'chipHeight', value: '28' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'labelInnerPadding', value: '5', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'labelOffset', value: '8' },
            { prop: 'leftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightContentMargin', value: '-3', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldDefaultRadius', value: '10' },
            { prop: 'textFieldSideRadius', value: '10' },
        ],
        xs: [
            { prop: 'chipClearContentMarginLeft', value: '4' },
            { prop: 'chipBorderRadius', value: '2' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipCloseIconSize', value: '12' },
            { prop: 'chipHeight', value: '20' },
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'labelInnerPadding', value: '5', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'labelOffset', value: '6' },
            { prop: 'leftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldDefaultRadius', value: '8' },
            { prop: 'textFieldSideRadius', value: '8' },
            { prop: 'chipPadding', value: '6', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'chipStyle', value: 'body.xs.normal' },
            { prop: 'contentLabelInnerPadding', value: '17', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'height', value: '32' },
            { prop: 'labelStyle', value: 'body.xs.normal' },
            { prop: 'padding', value: '9', adjust: [{ platform: 'web', param: 'padding', template: '$1 1rem $1 1rem' }] },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'textFieldSegmentedRadius', value: '2' },
            { prop: 'textStyle', value: 'body.xs.normal' },
        ],
    },
    orientation: {
        horizontal: [
            { prop: 'textFieldGroupOrientation', value: 'row' },
        ],
        vertical: [
            { prop: 'textFieldGroupOrientation', value: 'column' },
        ],
    },
    gap: {
        none: [
            { prop: 'textFieldGroupItemsGap', value: '1.008' },
        ],
        dense: [
            { prop: 'textFieldGroupItemsGap', value: '2' },
        ],
        wide: [
            { prop: 'textFieldGroupItemsGap', value: '8' },
        ],
    },
};
