import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'textFieldPlaceholderColor', type: 'color', variations: ['view', 'labelPlacement'], params: { web: ['textFieldPlaceholderColor'] } },
    { name: 'textFieldPlaceholderColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldPlaceholderColorFocus'] } },
    { name: 'textFieldClearPlaceholderColor', type: 'color', variations: ['view'], params: { web: ['textFieldClearPlaceholderColor'] } },
    { name: 'textFieldClearPlaceholderColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldClearPlaceholderColorFocus'] } },
    { name: 'textFieldBackgroundColor', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundColor'] } },
    { name: 'textFieldBackgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundColorFocus'] } },
    { name: 'textFieldCaretColor', type: 'color', variations: ['view'], params: { web: ['textFieldCaretColor'] } },
    { name: 'textFieldTextAfterColor', type: 'color', variations: ['view'], params: { web: ['textFieldTextAfterColor'] } },
    { name: 'textFieldLabelColor', type: 'color', variations: ['view'], params: { web: ['textFieldLabelColor'] } },
    { name: 'textFieldLeftHelperColor', type: 'color', variations: ['view'], params: { web: ['textFieldLeftHelperColor'] } },
    { name: 'checkboxFillColor', type: 'color', variations: ['view'], params: { web: ['checkboxFillColor'] } },
    { name: 'cellTitleStyle', type: 'typography', variations: ['size'], params: { web: ['cellTitleFontFamily', 'cellTitleFontSize', 'cellTitleFontStyle', 'cellTitleFontWeight', 'cellTitleLetterSpacing', 'cellTitleLineHeight'] } },
    { name: 'emptyStatePadding', type: 'value', variations: ['size'], params: { web: ['emptyStatePadding'] } },
    { name: 'textFieldHintTargetSize', type: 'dimension', variations: ['size'], params: { web: ['textFieldHintTargetSize'] } },
    { name: 'textFieldIndicatorSizeInner', type: 'dimension', variations: ['size'], params: { web: ['textFieldIndicatorSizeInner'] } },
    { name: 'textFieldIndicatorSizeOuter', type: 'dimension', variations: ['size'], params: { web: ['textFieldIndicatorSizeOuter'] } },
    { name: 'textFieldChipHeight', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipHeight'] } },
    { name: 'textFieldChipClearContentMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipClearContentMarginLeft'] } },
    { name: 'textFieldChipClearContentMarginRight', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipClearContentMarginRight'] } },
    { name: 'textFieldChipCloseIconSize', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipCloseIconSize'] } },
    { name: 'itemIconSize', type: 'dimension', variations: ['size'], params: { web: ['itemIconSize'] } },
    { name: 'itemBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['itemBorderRadius'] } },
    { name: 'checkboxTriggerBorderRadius', type: 'shape', variations: ['size'], params: { web: ['checkboxTriggerBorderRadius'] } },
    { name: 'textFieldTooltipBorderRadius', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipBorderRadius'] } },
    { name: 'textFieldPadding', type: 'dimension', variations: ['size'], params: { web: ['textFieldPadding'] } },
    { name: 'textFieldLeftContentMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldLeftContentMargin'] } },
    { name: 'textFieldRightContentMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldRightContentMargin'] } },
    { name: 'textFieldRightContentWithHintMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldRightContentWithHintMargin'] } },
    { name: 'textFieldContentRightWrapperMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldContentRightWrapperMargin'] } },
    { name: 'textFieldTextBeforeMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldTextBeforeMargin'] } },
    { name: 'textFieldTextAfterMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldTextAfterMargin'] } },
    { name: 'textFieldHintInnerLabelPlacementOffset', type: 'dimension', variations: ['size'], params: { web: ['textFieldHintInnerLabelPlacementOffset'] } },
    { name: 'textFieldClearHintInnerLabelPlacementOffset', type: 'dimension', variations: ['size'], params: { web: ['textFieldClearHintInnerLabelPlacementOffset'] } },
    { name: 'textFieldLeftHelperOffset', type: 'dimension', variations: ['size'], params: { web: ['textFieldLeftHelperOffset'] } },
    { name: 'textFieldIndicatorLabelPlacementOuterRight', type: 'dimension', variations: ['size'], params: { web: ['textFieldIndicatorLabelPlacementOuterRight'] } },
    { name: 'textFieldClearIndicatorLabelPlacementInner', type: 'dimension', variations: ['size'], params: { web: ['textFieldClearIndicatorLabelPlacementInner'] } },
    { name: 'textFieldClearIndicatorLabelPlacementInnerRight', type: 'dimension', variations: ['size'], params: { web: ['textFieldClearIndicatorLabelPlacementInnerRight'] } },
    { name: 'textFieldClearIndicatorHintInnerRight', type: 'dimension', variations: ['size'], params: { web: ['textFieldClearIndicatorHintInnerRight'] } },
    { name: 'textStyle', type: 'typography', variations: ['size'], params: { web: ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'fontLetterSpacing', 'fontLineHeight'] } },
    { name: 'textFieldLabelInnerStyle', type: 'typography', variations: ['labelPlacement'], params: { web: ['textFieldLabelInnerFontFamily', 'textFieldLabelInnerFontSize', 'textFieldLabelInnerFontStyle', 'textFieldLabelInnerFontWeight', 'textFieldLabelInnerLetterSpacing', 'textFieldLabelInnerLineHeight'] } },
    { name: 'textFieldPlaceholderColorReadOnly', type: 'color', params: { web: ['textFieldPlaceholderColorReadOnly'] } },
    { name: 'textFieldLeftHelperColorReadOnly', type: 'color', params: { web: ['textFieldLeftHelperColorReadOnly'] } },
    { name: 'textFieldLabelColorReadOnly', type: 'color', params: { web: ['textFieldLabelColorReadOnly'] } },
    { name: 'textFieldChipOpacityReadonly', type: 'float', variations: ['view', 'chipView'], params: { web: ['textFieldChipOpacityReadonly'] } },
    { name: 'textFieldHeight', type: 'dimension', variations: ['size'], params: { web: ['textFieldHeight'] } },
    { name: 'textFieldPaddingWithChips', type: 'dimension', variations: ['size'], params: { web: ['textFieldPaddingWithChips'] } },
    { name: 'textFieldContentRightWrapperGap', type: 'dimension', variations: ['size'], params: { web: ['textFieldContentRightWrapperGap'] } },
    { name: 'textFieldLabelOffset', type: 'dimension', variations: ['size'], params: { web: ['textFieldLabelOffset'] } },
    { name: 'itemHeight', type: 'dimension', variations: ['size'], params: { web: ['itemHeight'] } },
    { name: 'textFieldColor', type: 'color', variations: ['view'], params: { web: ['textFieldColor'] } },
    { name: 'textFieldClearColor', type: 'color', variations: ['view'], params: { web: ['textFieldClearColor'] } },
    { name: 'disclosureIconColorHover', type: 'color', variations: ['view'], params: { web: ['disclosureIconColorHover'] } },
    { name: 'itemIconColor', type: 'color', variations: ['view'], params: { web: ['itemIconColor'] } },
    { name: 'checkboxIconColor', type: 'color', variations: ['view'], params: { web: ['checkboxIconColor'] } },
    { name: 'checkboxTriggerBorderCheckedColor', type: 'color', variations: ['view'], params: { web: ['checkboxTriggerBorderCheckedColor'] } },
    { name: 'checkboxTriggerBorderColor', type: 'color', variations: ['view'], params: { web: ['checkboxTriggerBorderColor'] } },
    { name: 'textFieldHintMargin', type: 'value', variations: ['size'], params: { web: ['textFieldHintMargin'] } },
    { name: 'textFieldTooltipContentLeftMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipContentLeftMargin'] } },
    { name: 'textFieldTooltipArrowMaskWidth', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipArrowMaskWidth'] } },
    { name: 'textFieldTooltipArrowMaskHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipArrowMaskHeight'] } },
    { name: 'textFieldTooltipBackgroundColor', type: 'color', variations: ['hintView'], params: { web: ['textFieldTooltipBackgroundColor'] } },
    { name: 'textFieldTooltipBoxShadow', type: 'shadow', variations: ['hintView'], params: { web: ['textFieldTooltipBoxShadow'] } },
    { name: 'textFieldTooltipColor', type: 'color', variations: ['hintView'], params: { web: ['textFieldTooltipColor'] } },
    { name: 'textFieldTooltipArrowBackground', type: 'color', variations: ['hintView'], params: { web: ['textFieldTooltipArrowBackground'] } },
    { name: 'textFieldTooltipTextStyle', type: 'typography', variations: ['hintSize'], params: { web: ['textFieldTooltipTextFontFamily', 'textFieldTooltipTextFontSize', 'textFieldTooltipTextFontStyle', 'textFieldTooltipTextFontWeight', 'textFieldTooltipTextFontLetterSpacing', 'textFieldTooltipTextFontLineHeight'] } },
    { name: 'textFieldTooltipArrowMaskImage', type: 'value', variations: ['hintSize'], params: { web: ['textFieldTooltipArrowMaskImage'] } },
    { name: 'textFieldColorReadOnly', type: 'color', params: { web: ['textFieldColorReadOnly'] } },
    { name: 'textFieldBackgroundColorReadOnly', type: 'color', params: { web: ['textFieldBackgroundColorReadOnly'] } },
    { name: 'textFieldTextBeforeColor', type: 'color', variations: ['view'], params: { web: ['textFieldTextBeforeColor'] } },
    { name: 'borderRadius', type: 'dimension', variations: ['size'], params: { web: ['borderRadius'] } },
    { name: 'textFieldContentSlotColorActive', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotColorActive'] } },
    { name: 'textFieldIndicatorColor', type: 'color', variations: ['view'], params: { web: ['textFieldIndicatorColor'] } },
    { name: 'textFieldOptionalColor', type: 'color', variations: ['view'], params: { web: ['textFieldOptionalColor'] } },
    { name: 'textFieldChipCloseIconColor', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipCloseIconColor'] } },
    { name: 'textFieldChipCloseIconColorHover', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipCloseIconColorHover'] } },
    { name: 'textFieldChipCloseIconColorReadonly', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipCloseIconColorReadonly'] } },
    { name: 'textFieldChipColor', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipColor'] } },
    { name: 'textFieldChipBackground', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipBackground'] } },
    { name: 'textFieldChipGap', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipGap'] } },
    { name: 'textFieldStyle', type: 'typography', variations: ['size'], params: { web: ['textFieldFontFamily', 'textFieldFontSize', 'textFieldFontStyle', 'textFieldFontWeight', 'textFieldLetterSpacing', 'textFieldLineHeight'] } },
    { name: 'textFieldLabelStyle', type: 'typography', variations: ['size'], params: { web: ['textFieldLabelFontFamily', 'textFieldLabelFontSize', 'textFieldLabelFontStyle', 'textFieldLabelFontWeight', 'textFieldLabelLetterSpacing', 'textFieldLabelLineHeight'] } },
    { name: 'textFieldLeftHelperStyle', type: 'typography', variations: ['size'], params: { web: ['textFieldLeftHelperFontFamily', 'textFieldLeftHelperFontSize', 'textFieldLeftHelperFontStyle', 'textFieldLeftHelperFontWeight', 'textFieldLeftHelperLetterSpacing', 'textFieldLeftHelperLineHeight'] } },
    { name: 'textFieldChipWidth', type: 'value', variations: ['size'], params: { web: ['textFieldChipWidth'] } },
    { name: 'textFieldChipStyle', type: 'typography', variations: ['size'], params: { web: ['textFieldChipFontFamily', 'textFieldChipFontSize', 'textFieldChipFontStyle', 'textFieldChipFontWeight', 'textFieldChipLetterSpacing', 'textFieldChipLineHeight'] } },
    { name: 'dividerMarginTop', type: 'dimension', variations: ['size'], params: { web: ['dividerMarginTop'] } },
    { name: 'dividerMarginRight', type: 'dimension', variations: ['size'], params: { web: ['dividerMarginRight'] } },
    { name: 'textFieldDisabledOpacity', type: 'float', params: { web: ['textFieldDisabledOpacity'] } },
    { name: 'textFieldReadOnlyOpacity', type: 'float', params: { web: ['textFieldReadOnlyOpacity'] } },
    { name: 'textFieldChipBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipBorderRadius'] } },
    { name: 'textFieldChipPadding', type: 'dimension', variations: ['size'], params: { web: ['textFieldChipPadding'] } },
    { name: 'itemPadding', type: 'dimension', variations: ['size'], params: { web: ['itemPadding'] } },
    { name: 'itemPaddingTight', type: 'dimension', variations: ['size'], params: { web: ['itemPaddingTight'] } },
    { name: 'itemIconMargin', type: 'dimension', variations: ['size'], params: { web: ['itemIconMargin'] } },
    { name: 'textFieldTooltipArrowHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipArrowHeight'] } },
    { name: 'textFieldTooltipArrowEdgeMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipArrowEdgeMargin'] } },
    { name: 'dividerColor', type: 'color', variations: ['view'], params: { web: ['dividerColor'] } },
    { name: 'textFieldLabelInnerPadding', type: 'dimension', variations: ['size'], params: { web: ['textFieldLabelInnerPadding'] } },
    { name: 'textFieldIndicatorLabelPlacementOuter', type: 'dimension', variations: ['size'], params: { web: ['textFieldIndicatorLabelPlacementOuter'] } },
    { name: 'textFieldIndicatorLabelPlacementInnerRight', type: 'dimension', variations: ['size'], params: { web: ['textFieldIndicatorLabelPlacementInnerRight'] } },
    { name: 'itemBackgroundHover', type: 'color', variations: ['view'], params: { web: ['itemBackgroundHover'] } },
    { name: 'textFieldFocusColor', type: 'color', variations: ['view'], params: { web: ['textFieldFocusColor'] } },
    { name: 'textFieldContentSlotColor', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotColor'] } },
    { name: 'textFieldContentSlotColorHover', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotColorHover'] } },
    { name: 'textFieldChipColorHover', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipColorHover'] } },
    { name: 'textFieldChipBackgroundHover', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipBackgroundHover'] } },
    { name: 'textFieldChipColorActive', type: 'color', variations: ['view'], params: { web: ['textFieldChipColorActive'] } },
    { name: 'textFieldChipBackgroundActive', type: 'color', variations: ['view'], params: { web: ['textFieldChipBackgroundActive'] } },
    { name: 'textFieldChipBackgroundReadOnly', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipBackgroundReadOnly'] } },
    { name: 'textFieldChipColorReadOnly', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipColorReadOnly'] } },
    { name: 'textFieldChipBackgroundReadOnlyHover', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipBackgroundReadOnlyHover'] } },
    { name: 'textFieldChipColorReadOnlyHover', type: 'color', variations: ['view', 'chipView'], params: { web: ['textFieldChipColorReadOnlyHover'] } },
    { name: 'itemIconSizeTight', type: 'dimension', variations: ['size'], params: { web: ['itemIconSizeTight'] } },
    { name: 'itemTreeOffsetWidth', type: 'dimension', variations: ['size'], params: { web: ['itemTreeOffsetWidth'] } },
    { name: 'cellPadding', type: 'dimension', variations: ['size'], params: { web: ['cellPadding'] } },
    { name: 'cellPaddingLeftContent', type: 'dimension', variations: ['size'], params: { web: ['cellPaddingLeftContent'] } },
    { name: 'cellPaddingContent', type: 'dimension', variations: ['size'], params: { web: ['cellPaddingContent'] } },
    { name: 'cellPaddingRightContent', type: 'dimension', variations: ['size'], params: { web: ['cellPaddingRightContent'] } },
    { name: 'cellTextboxGap', type: 'dimension', variations: ['size'], params: { web: ['cellTextboxGap'] } },
    { name: 'checkboxTriggerSize', type: 'dimension', variations: ['size'], params: { web: ['checkboxTriggerSize'] } },
    { name: 'checkboxTriggerSizeTight', type: 'dimension', variations: ['size'], params: { web: ['checkboxTriggerSizeTight'] } },
    { name: 'checkboxTriggerBorderRadiusTight', type: 'dimension', variations: ['size'], params: { web: ['checkboxTriggerBorderRadiusTight'] } },
    { name: 'checkboxTriggerBorderWidth', type: 'dimension', variations: ['size'], params: { web: ['checkboxTriggerBorderWidth'] } },
    { name: 'indicatorSize', type: 'dimension', variations: ['size'], params: { web: ['indicatorSize'] } },
    { name: 'dividerMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['dividerMarginLeft'] } },
    { name: 'dividerMarginTopTight', type: 'dimension', variations: ['size'], params: { web: ['dividerMarginTopTight'] } },
    { name: 'dividerMarginBottomTight', type: 'dimension', variations: ['size'], params: { web: ['dividerMarginBottomTight'] } },
    { name: 'textFieldTooltipPaddingLeft', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipPaddingLeft'] } },
    { name: 'textFieldTooltipMinHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipMinHeight'] } },
    { name: 'textFieldContentLabelInnerPadding', type: 'dimension', variations: ['size'], params: { web: ['textFieldContentLabelInnerPadding'] } },
    { name: 'textFieldIndicatorLabelPlacementInner', type: 'dimension', variations: ['size'], params: { web: ['textFieldIndicatorLabelPlacementInner'] } },
    { name: 'textFieldHintIconColor', type: 'color', variations: ['view'], params: { web: ['textFieldHintIconColor'] } },
    { name: 'dividerMarginBottom', type: 'dimension', variations: ['size'], params: { web: ['dividerMarginBottom'] } },
    { name: 'textFieldContentSlotRightOpacityReadOnly', type: 'float', params: { web: ['textFieldContentSlotRightOpacityReadOnly'] } },
    { name: 'textFieldBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['textFieldBorderRadius'] } },
    { name: 'itemGap', type: 'dimension', variations: ['size'], params: { web: ['itemGap'] } },
    { name: 'textFieldTooltipPaddingTop', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipPaddingTop'] } },
    { name: 'textFieldTooltipPaddingRight', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipPaddingRight'] } },
    { name: 'textFieldTooltipPaddingBottom', type: 'dimension', variations: ['hintSize'], params: { web: ['textFieldTooltipPaddingBottom'] } },
    { name: 'cellGap', type: 'dimension', variations: ['size'], params: { web: ['cellGap'] } },
    { name: 'disclosureIconColor', type: 'color', variations: ['view'], params: { web: ['disclosureIconColor'] } },
    { name: 'padding', type: 'dimension', variations: ['size'], params: { web: ['padding'] } },
];
