import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        accent: [
            { prop: 'linkButtonIconColor', token: 'text.default.accent-active', state: 'pressed' },
            { prop: 'linkButtonTextColor', token: 'text.default.accent-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.accent-active', state: 'pressed' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.accent' },
            { prop: 'linkButtonColor', token: 'text.default.accent-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.accent' },
            { prop: 'linkButtonIconColor', token: 'text.default.accent' },
            { prop: 'linkButtonTextColor', token: 'text.default.accent-active', state: 'pressed' },
            { prop: 'linkButtonColor', token: 'text.default.accent' },
            { prop: 'linkButtonIconColor', token: 'text.default.accent-hover', state: 'hovered' },
        ],
        positive: [
            { prop: 'linkButtonIconColor', token: 'text.default.positive-active', state: 'pressed' },
            { prop: 'linkButtonTextColor', token: 'text.default.positive-active', state: 'pressed' },
            { prop: 'linkButtonColor', token: 'text.default.positive-active', state: 'pressed' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.positive' },
            { prop: 'linkButtonColor', token: 'text.default.positive-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.positive' },
            { prop: 'linkButtonIconColor', token: 'text.default.positive' },
            { prop: 'linkButtonTextColor', token: 'text.default.positive-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.positive' },
            { prop: 'linkButtonIconColor', token: 'text.default.positive-hover', state: 'hovered' },
        ],
        negative: [
            { prop: 'linkButtonIconColor', token: 'text.default.negative-active', state: 'pressed' },
            { prop: 'linkButtonTextColor', token: 'text.default.negative-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.negative-active', state: 'pressed' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.negative' },
            { prop: 'linkButtonColor', token: 'text.default.negative-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.negative' },
            { prop: 'linkButtonIconColor', token: 'text.default.negative' },
            { prop: 'linkButtonTextColor', token: 'text.default.negative-active', state: 'pressed' },
            { prop: 'linkButtonColor', token: 'text.default.negative' },
            { prop: 'linkButtonIconColor', token: 'text.default.negative-hover', state: 'hovered' },
        ],
        secondary: [
            { prop: 'linkButtonIconColor', token: 'text.default.secondary-active', state: 'pressed' },
            { prop: 'linkButtonTextColor', token: 'text.default.secondary-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.secondary-hover', state: 'hovered' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.secondary' },
            { prop: 'linkButtonColor', token: 'text.default.secondary-active', state: 'pressed' },
            { prop: 'linkButtonTextColor', token: 'text.default.secondary' },
            { prop: 'linkButtonIconColor', token: 'text.default.secondary' },
            { prop: 'linkButtonTextColor', token: 'text.default.secondary-active', state: 'pressed' },
            { prop: 'linkButtonColor', token: 'text.default.secondary' },
            { prop: 'linkButtonIconColor', token: 'text.default.secondary-hover', state: 'hovered' },
        ],
        warning: [
            { prop: 'linkButtonIconColor', token: 'text.default.warning-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.warning-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.warning-active', state: 'pressed' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.warning' },
            { prop: 'linkButtonColor', token: 'text.default.warning-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.warning' },
            { prop: 'linkButtonIconColor', token: 'text.default.warning' },
            { prop: 'linkButtonTextColor', token: 'text.default.warning-active', state: 'pressed' },
            { prop: 'linkButtonColor', token: 'text.default.warning' },
            { prop: 'linkButtonIconColor', token: 'text.default.warning-active', state: 'pressed' },
        ],
        info: [
            { prop: 'linkButtonIconColor', token: 'text.default.info-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.info-active', state: 'pressed' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.info' },
            { prop: 'linkButtonColor', token: 'text.default.info-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.info' },
            { prop: 'linkButtonIconColor', token: 'text.default.info' },
            { prop: 'linkButtonTextColor', token: 'text.default.info-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.info' },
            { prop: 'linkButtonIconColor', token: 'text.default.info-active', state: 'pressed' },
            { prop: 'linkButtonTextColor', token: 'text.default.info-active', state: 'pressed' },
        ],
        default: [
            { prop: 'linkButtonIconColor', token: 'text.default.primary-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.primary-hover', state: 'hovered' },
            { prop: 'linkButtonColor', token: 'text.default.primary-active', state: 'pressed' },
            { prop: 'linkButtonSpinnerColor', token: 'text.default.primary' },
            { prop: 'linkButtonColor', token: 'text.default.primary-hover', state: 'hovered' },
            { prop: 'linkButtonTextColor', token: 'text.default.primary' },
            { prop: 'linkButtonIconColor', token: 'text.default.primary' },
            { prop: 'linkButtonTextColor', token: 'text.default.primary-active', state: 'pressed' },
            { prop: 'linkButtonColor', token: 'text.default.primary' },
            { prop: 'linkButtonIconColor', token: 'text.default.primary-active', state: 'pressed' },
        ],
    },
    size: {
        m: [
            { prop: 'linkButtonLeftContentMargin', value: '6' },
            { prop: 'linkButtonTextPadding', value: '2' },
            { prop: 'linkButtonPadding', value: '12' },
            { prop: 'textStyle', value: 'body.m.bold' },
            { prop: 'linkButtonRadius', token: 'round.m' },
            { prop: 'linkButtonHeight', value: '48' },
            { prop: 'linkButtonSpinnerSize', value: '22' },
            { prop: 'linkButtonAdditionalContentMargin', value: '6' },
            { prop: 'linkButtonRightContentMargin', value: '6' },
        ],
        xxs: [
            { prop: 'linkButtonRadius', token: 'round.xs' },
            { prop: 'linkButtonAdditionalContentMargin', value: '4' },
            { prop: 'linkButtonRightContentMargin', value: '1.008' },
            { prop: 'linkButtonHeight', value: '24' },
            { prop: 'linkButtonSpinnerSize', value: '12' },
            { prop: 'linkButtonPadding', value: '6' },
            { prop: 'linkButtonLeftContentMargin', value: '1.008' },
            { prop: 'textStyle', value: 'body.xs.bold' },
        ],
        xl: [
            { prop: 'linkButtonPadding', value: '20' },
            { prop: 'textStyle', value: 'body.l.bold' },
            { prop: 'linkButtonRadius', token: 'round.l' },
            { prop: 'linkButtonAdditionalContentMargin', value: '8' },
            { prop: 'linkButtonRightContentMargin', value: '8' },
            { prop: 'linkButtonLeftContentMargin', value: '8' },
            { prop: 'linkButtonTextPadding', value: '1' },
            { prop: 'linkButtonHeight', value: '64' },
            { prop: 'linkButtonSpinnerSize', value: '24' },
        ],
        l: [
            { prop: 'linkButtonHeight', value: '56' },
            { prop: 'linkButtonSpinnerSize', value: '22' },
            { prop: 'linkButtonLeftContentMargin', value: '8' },
            { prop: 'linkButtonTextPadding', value: '1' },
            { prop: 'linkButtonPadding', value: '16' },
            { prop: 'textStyle', value: 'body.l.bold' },
            { prop: 'linkButtonAdditionalContentMargin', value: '8' },
            { prop: 'linkButtonRightContentMargin', value: '8' },
            { prop: 'linkButtonRadius', token: 'round.m' },
        ],
        xs: [
            { prop: 'linkButtonHeight', value: '32' },
            { prop: 'linkButtonSpinnerSize', value: '16' },
            { prop: 'linkButtonLeftContentMargin', value: '4' },
            { prop: 'linkButtonTextPadding', value: '1' },
            { prop: 'linkButtonPadding', value: '8' },
            { prop: 'textStyle', value: 'body.xs.bold' },
            { prop: 'linkButtonAdditionalContentMargin', value: '4' },
            { prop: 'linkButtonRightContentMargin', value: '4' },
            { prop: 'linkButtonRadius', token: 'round.s' },
        ],
        s: [
            { prop: 'linkButtonLeftContentMargin', value: '4' },
            { prop: 'linkButtonTextPadding', value: '1' },
            { prop: 'linkButtonPadding', value: '8' },
            { prop: 'textStyle', value: 'body.s.bold' },
            { prop: 'linkButtonRadius', token: 'round.s' },
            { prop: 'linkButtonHeight', value: '40' },
            { prop: 'linkButtonSpinnerSize', value: '22' },
            { prop: 'linkButtonAdditionalContentMargin', value: '4' },
            { prop: 'linkButtonRightContentMargin', value: '4' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'linkButtonDisabledAlpha', value: '0.4' },
    { prop: 'linkButtonFocusColor', token: 'text.default.accent' },
];
