FROM node:22

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN npm ci

COPY --chown=node:node . .

EXPOSE 3005

CMD ["npm", "run", "dev"]

## Билд образа
# docker build -t ds-generator:latest .

## Запуск
# docker run -d \
#   --name my_node_app \
#   -p 3005:3005 \
#   -v $(pwd):/home/node/app \
#   -v /home/node/app/node_modules \
#   ds-generator