import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'outlineColor', type: 'color', variations: ['focused'], params: { web: ['outlineColor'] } },
    { name: 'statusLeft', type: 'value', variations: ['shape'], params: { web: ['statusLeft'] } },
    { name: 'statusTop', type: 'value', variations: ['shape'], params: { web: ['statusTop'] } },
    { name: 'badgeColor', type: 'color', variations: ['badgeView'], params: { web: ['badgeColor'] } },
    { name: 'badgeBackground', type: 'color', variations: ['badgeView'], params: { web: ['badgeBackground'] } },
    { name: 'badgeColorTransparent', type: 'color', variations: ['badgeView'], params: { web: ['badgeColorTransparent'] } },
    { name: 'badgeBackgroundTransparent', type: 'color', variations: ['badgeView'], params: { web: ['badgeBackgroundTransparent'] } },
    { name: 'badgeColorClear', type: 'color', variations: ['badgeView'], params: { web: ['badgeColorClear'] } },
    { name: 'badgeBackgroundClear', type: 'color', variations: ['badgeView'], params: { web: ['badgeBackgroundClear'] } },
    { name: 'counterColor', type: 'color', variations: ['counterView'], params: { web: ['counterColor'] } },
    { name: 'counterBackground', type: 'color', variations: ['counterView'], params: { web: ['counterBackground'] } },
    { name: 'scaleHover', type: 'float', variations: ['view'], params: { web: ['scaleHover'] } },
    { name: 'fontSize', type: 'dimension', variations: ['size'], params: { web: ['fontSize'] } },
    { name: 'fontWeight', type: 'float', variations: ['size'], params: { web: ['fontWeight'] } },
    { name: 'lineHeight', type: 'dimension', variations: ['size'], params: { web: ['lineHeight'] } },
    { name: 'statusIconSize', type: 'dimension', variations: ['size'], params: { web: ['statusIconSize'] } },
    { name: 'badgeHeight', type: 'dimension', variations: ['size'], params: { web: ['badgeHeight'] } },
    { name: 'badgeLeftContentMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['badgeLeftContentMarginLeft'] } },
    { name: 'badgeLeftContentMarginRight', type: 'dimension', variations: ['size'], params: { web: ['badgeLeftContentMarginRight'] } },
    { name: 'badgeRightContentMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['badgeRightContentMarginLeft'] } },
    { name: 'badgeRightContentMarginRight', type: 'dimension', variations: ['size'], params: { web: ['badgeRightContentMarginRight'] } },
    { name: 'counterHeight', type: 'dimension', variations: ['size'], params: { web: ['counterHeight'] } },
    { name: 'outlineSize', type: 'dimension', variations: ['focused'], params: { web: ['outlineSize'] } },
    { name: 'outlineOffset', type: 'dimension', variations: ['focused'], params: { web: ['outlineOffset'] } },
    { name: 'badgeBorderRadius', type: 'shape', variations: ['size'], params: { web: ['badgeBorderRadius'] } },
    { name: 'badgePilledBorderRadius', type: 'shape', variations: ['size'], params: { web: ['badgePilledBorderRadius'] } },
    { name: 'counterBorderRadius', type: 'shape', variations: ['size'], params: { web: ['counterBorderRadius'] } },
    { name: 'badgePadding', type: 'dimension', variations: ['size'], params: { web: ['badgePadding'] } },
    { name: 'badgePaddingIconOnly', type: 'dimension', variations: ['size'], params: { web: ['badgePaddingIconOnly'] } },
    { name: 'counterPadding', type: 'dimension', variations: ['size'], params: { web: ['counterPadding'] } },
    { name: 'color', type: 'color', variations: ['view'], params: { web: ['color'] } },
    { name: 'backgroundColor', type: 'value', variations: ['view'], params: { web: ['backgroundColor'] } },
    { name: 'statusOnlineColor', type: 'color', variations: ['view'], params: { web: ['statusOnlineColor'] } },
    { name: 'statusOfflineColor', type: 'color', variations: ['view'], params: { web: ['statusOfflineColor'] } },
    { name: 'fontFamily', type: 'value', variations: ['view'], params: { web: ['fontFamily'] } },
    { name: 'avatarSize', type: 'value', variations: ['size'], params: { web: ['avatarSize'] } },
    { name: 'borderRadius', type: 'value', variations: ['size', 'shape'], params: { web: ['borderRadius'] } },
    { name: 'badgeStyle', type: 'typography', variations: ['size'], params: { web: ['badgeFontFamily', 'badgeFontSize', 'badgeFontStyle', 'badgeFontWeight', 'badgeLetterSpacing', 'badgeLineHeight'] } },
    { name: 'counterStyle', type: 'typography', variations: ['size'], params: { web: ['counterFontFamily', 'counterFontSize', 'counterFontStyle', 'counterFontWeight', 'counterLetterSpacing', 'counterLineHeight'] } },
    { name: 'extraPlacementFactor', type: 'float', variations: ['size'], params: { web: ['extraPlacementFactor'] } },
];
