import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'color', token: 'text.default.accent-gradient' },
            { prop: 'scaleHover', value: '1.02' },
            { prop: 'statusOnlineColor', token: 'surface.default.positive' },
            { prop: 'backgroundColor', value: 'linear-gradient(94deg, rgba(62, 121, 240, 0.2) 6.49%, rgba(39, 198, 229, 0.2) 93.51%)' },
            { prop: 'fontFamily', value: 'var(--plasma-typo-text-font-family)' },
            { prop: 'statusOfflineColor', token: 'surface.default.solid-tertiary' },
        ],
    },
    size: {
        xxl: [
            { prop: 'badgeBorderRadius', token: 'round.s' },
            { prop: 'badgeLeftContentMarginLeft', value: '-1.008' },
            { prop: 'badgePadding', value: '11.008', adjust: [{ platform: 'web', param: 'badgePadding', template: '0 $1' }] },
            { prop: 'badgePaddingIconOnly', value: '6', adjust: [{ platform: 'web', param: 'badgePaddingIconOnly', template: '0 $1' }] },
            { prop: 'badgePilledBorderRadius', token: 'round.xl' },
            { prop: 'badgeRightContentMarginRight', value: '-1.008' },
            { prop: 'borderRadius', value: '1.125rem' },
            { prop: 'counterHeight', value: '28' },
            { prop: 'fontSize', value: '32' },
            { prop: 'lineHeight', value: '32' },
            { prop: 'avatarSize', value: '6.25rem' },
            { prop: 'badgeHeight', value: '28' },
            { prop: 'badgeLeftContentMarginRight', value: '4' },
            { prop: 'badgeRightContentMarginLeft', value: '4' },
            { prop: 'badgeStyle', value: 'body.s.normal' },
            { prop: 'counterBorderRadius', token: 'round.l' },
            { prop: 'counterPadding', value: '10', adjust: [{ platform: 'web', param: 'counterPadding', template: '0 $1' }] },
            { prop: 'counterStyle', value: 'body.s.normal' },
            { prop: 'fontWeight', value: '600' },
            { prop: 'statusIconSize', value: '12' },
        ],
        l: [
            { prop: 'avatarSize', value: '3rem' },
            { prop: 'badgeHeight', value: '20' },
            { prop: 'badgeLeftContentMarginRight', value: '2' },
            { prop: 'badgeRightContentMarginLeft', value: '2' },
            { prop: 'badgeStyle', value: 'body.xxs.normal' },
            { prop: 'counterBorderRadius', token: 'round.l' },
            { prop: 'counterPadding', value: '6', adjust: [{ platform: 'web', param: 'counterPadding', template: '0 $1' }] },
            { prop: 'counterStyle', value: 'body.xxs.normal' },
            { prop: 'fontSize', value: '20' },
            { prop: 'lineHeight', value: '20' },
            { prop: 'badgeBorderRadius', token: 'round.xs' },
            { prop: 'badgeLeftContentMarginLeft', value: '-1.008' },
            { prop: 'badgePadding', value: '7.008', adjust: [{ platform: 'web', param: 'badgePadding', template: '0 $1' }] },
            { prop: 'badgePaddingIconOnly', value: '4', adjust: [{ platform: 'web', param: 'badgePaddingIconOnly', template: '0 $1' }] },
            { prop: 'badgePilledBorderRadius', token: 'round.xl' },
            { prop: 'badgeRightContentMarginRight', value: '-1.008' },
            { prop: 'borderRadius', value: '0.75rem' },
            { prop: 'counterHeight', value: '20' },
            { prop: 'extraPlacementFactor', value: '2' },
            { prop: 'fontWeight', value: '600' },
            { prop: 'statusIconSize', value: '8' },
        ],
        m: [
            { prop: 'avatarSize', value: '2.25rem' },
            { prop: 'badgeHeight', value: '16' },
            { prop: 'badgeLeftContentMarginRight', value: '2' },
            { prop: 'badgeRightContentMarginLeft', value: '2' },
            { prop: 'badgeStyle', value: 'body.xxs.normal' },
            { prop: 'counterBorderRadius', token: 'round.l' },
            { prop: 'counterPadding', value: '4', adjust: [{ platform: 'web', param: 'counterPadding', template: '0 $1' }] },
            { prop: 'counterStyle', value: 'body.xxs.normal' },
            { prop: 'fontSize', value: '14' },
            { prop: 'lineHeight', value: '14' },
            { prop: 'badgeBorderRadius', token: 'round.xxs' },
            { prop: 'badgeLeftContentMarginLeft', value: '-1.008' },
            { prop: 'badgePadding', value: '4', adjust: [{ platform: 'web', param: 'badgePadding', template: '0 $1' }] },
            { prop: 'badgePaddingIconOnly', value: '3.008', adjust: [{ platform: 'web', param: 'badgePaddingIconOnly', template: '0 $1' }] },
            { prop: 'badgePilledBorderRadius', token: 'round.xl' },
            { prop: 'badgeRightContentMarginRight', value: '-1.008' },
            { prop: 'borderRadius', value: '0.625rem' },
            { prop: 'counterHeight', value: '16' },
            { prop: 'extraPlacementFactor', value: '2' },
            { prop: 'fontWeight', value: '600' },
            { prop: 'statusIconSize', value: '8' },
        ],
        s: [
            { prop: 'avatarSize', value: '1.5rem' },
            { prop: 'counterBorderRadius', token: 'round.l' },
            { prop: 'counterPadding', value: '2', adjust: [{ platform: 'web', param: 'counterPadding', template: '0 $1' }] },
            { prop: 'counterStyle', value: 'body.xxs.normal' },
            { prop: 'fontSize', value: '8' },
            { prop: 'borderRadius', value: '0.5rem' },
            { prop: 'counterHeight', value: '12' },
            { prop: 'extraPlacementFactor', value: '1' },
            { prop: 'fontWeight', value: '600' },
            { prop: 'statusIconSize', value: '6' },
            { prop: 'lineHeight', value: '8' },
        ],
        fit: [
            { prop: 'borderRadius', value: '50%' },
            { prop: 'fontWeight', value: '0' },
            { prop: 'avatarSize', value: '100%' },
            { prop: 'fontSize', value: '0' },
            { prop: 'lineHeight', value: '0' },
            { prop: 'statusIconSize', value: '0' },
        ],
    },
    focused: {
        true: [
            { prop: 'outlineColor', token: 'surface.default.accent' },
            { prop: 'outlineSize', value: '1.6' },
            { prop: 'outlineOffset', value: '-3.2' },
        ],
    },
    shape: {
        circled: [
            { prop: 'statusLeft', value: 'calc(0.867 * var(${avatarTokens.avatarSize}) - var(${avatarTokens.statusIconSize}) / 2)' },
            { prop: 'borderRadius', value: '50%' },
            { prop: 'statusTop', value: 'calc(0.867 * var(${avatarTokens.avatarSize}) - var(${avatarTokens.statusIconSize}) / 2)' },
        ],
        rounded: [
            { prop: 'statusLeft', value: 'calc(var(${avatarTokens.avatarSize}) - var(${avatarTokens.statusIconSize}))' },
            { prop: 'statusTop', value: 'calc(var(${avatarTokens.avatarSize}) - var(${avatarTokens.statusIconSize}))' },
        ],
    },
    badgeView: {
        default: [
            { prop: 'badgeBackground', token: 'surface.default.solid-default' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.default.transparent-secondary' },
            { prop: 'badgeColorClear', token: 'text.default.primary' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.inverse.primary' },
            { prop: 'badgeColorTransparent', token: 'text.default.primary' },
        ],
        accent: [
            { prop: 'badgeBackground', token: 'surface.default.accent' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.default.transparent-accent' },
            { prop: 'badgeColorClear', token: 'text.default.accent' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.on-dark.primary' },
            { prop: 'badgeColorTransparent', token: 'text.default.accent' },
        ],
        positive: [
            { prop: 'badgeBackground', token: 'surface.default.positive' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.default.transparent-positive' },
            { prop: 'badgeColorClear', token: 'text.default.positive' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.on-dark.primary' },
            { prop: 'badgeColorTransparent', token: 'text.default.positive' },
        ],
        warning: [
            { prop: 'badgeBackground', token: 'surface.default.warning' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.default.transparent-warning' },
            { prop: 'badgeColorClear', token: 'text.default.warning' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.on-dark.primary' },
            { prop: 'badgeColorTransparent', token: 'text.default.warning' },
        ],
        negative: [
            { prop: 'badgeBackground', token: 'surface.default.negative' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.default.transparent-negative' },
            { prop: 'badgeColorClear', token: 'text.default.negative' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.on-dark.primary' },
            { prop: 'badgeColorTransparent', token: 'text.default.negative' },
        ],
        dark: [
            { prop: 'badgeBackground', token: 'surface.on-light.solid-default' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.on-light.transparent-deep' },
            { prop: 'badgeColorClear', token: 'text.on-light.primary' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.on-dark.primary' },
            { prop: 'badgeColorTransparent', token: 'text.on-dark.primary' },
        ],
        light: [
            { prop: 'badgeBackground', token: 'surface.on-dark.solid-default' },
            { prop: 'badgeBackgroundTransparent', token: 'surface.on-dark.transparent-card' },
            { prop: 'badgeColorClear', token: 'text.on-dark.primary' },
            { prop: 'badgeBackgroundClear', token: 'surface.default.clear' },
            { prop: 'badgeColor', token: 'text.on-light.primary' },
            { prop: 'badgeColorTransparent', token: 'text.on-dark.primary' },
        ],
    },
    counterView: {
        negative: [
            { prop: 'counterBackground', token: 'surface.default.negative' },
            { prop: 'counterColor', token: 'text.on-dark.primary' },
        ],
        dark: [
            { prop: 'counterBackground', token: 'surface.on-light.solid-default' },
            { prop: 'counterColor', token: 'text.on-dark.primary' },
        ],
        light: [
            { prop: 'counterBackground', token: 'surface.on-dark.solid-default' },
            { prop: 'counterColor', token: 'text.on-light.primary' },
        ],
        positive: [
            { prop: 'counterBackground', token: 'surface.default.positive' },
            { prop: 'counterColor', token: 'text.on-dark.primary' },
        ],
        default: [
            { prop: 'counterBackground', token: 'surface.default.solid-default' },
            { prop: 'counterColor', token: 'text.inverse.primary' },
        ],
        accent: [
            { prop: 'counterBackground', token: 'surface.default.accent' },
            { prop: 'counterColor', token: 'text.on-dark.primary' },
        ],
        warning: [
            { prop: 'counterBackground', token: 'surface.default.warning' },
            { prop: 'counterColor', token: 'text.on-dark.primary' },
        ],
    },
};
