import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'verticalPadding', type: 'dimension', description: 'Отступ лейбла и описания от верхнего края', variations: ['size'], params: { web: ['contentTopOffset'] } },
    { name: 'toggleIndeterminateIconColor', type: 'color', description: 'Цвет фона indeterminate иконки тоггла', variations: ['view'], params: { xml: ['sd_buttonMarkColor'], compose: ['baseColor'] } },
    { name: 'disableAlpha', type: 'float', description: 'Значение прозрачности в отключенном варианте', params: { xml: ['disableAlpha'], compose: ['disableAlpha'], ios: ['disableAlpha'], web: ['disabledOpacity'] } },
    { name: 'margin', type: 'dimension', description: 'Внешний отступ', variations: ['size'], params: { web: ['margin'] } },
    { name: 'togglePadding', type: 'dimension', description: 'Внутренний отступ тоггла', variations: ['size'], params: { xml: ['sd_buttonPadding'], compose: ['innerCheckBoxPadding'], web: ['triggerPadding'] } },
    { name: 'toggleShape', type: 'shape', description: 'Скругление тоггла', variations: ['size'], params: { compose: ['controlRadius'], web: ['triggerBorderRadius'] } },
    { name: 'toggleBorderWidth', type: 'dimension', description: 'Толщина бордера тоггла', variations: ['size'], params: { compose: ['strokeWidth'], web: ['triggerBorderWidth'] } },
    { name: 'toggleCheckedBorderWidth', type: 'dimension', description: 'Толщина бордера в состоянии checked/indeterminate', variations: ['size'], params: { compose: ['checkedStrokeWidth'] } },
    { name: 'focusColor', type: 'color', description: 'Цвет обводки компонента', params: { web: ['focusColor'] } },
    { name: 'descriptionColor', type: 'color', description: 'Цвет описания', variations: ['view'], params: { xml: ['sd_descriptionTextColor'], compose: ['descriptionColor'], ios: ['subtitleColor'], web: ['descriptionColor'] } },
    { name: 'toggleWidth', type: 'dimension', description: 'Ширина тоггла', variations: ['size'], params: { xml: ['sd_buttonSize'], compose: ['toggleWidth'], ios: ['imageSize'] } },
    { name: 'toggleHeight', type: 'dimension', description: 'Высота тоггла', variations: ['size'], params: { xml: ['sd_buttonSize'], compose: ['toggleHeight'], ios: ['imageSize'], web: ['triggerSize'] } },
    { name: 'descriptionPadding', type: 'dimension', description: 'Отступ между лейблом и описанием', variations: ['size'], params: { xml: ['sd_descriptionPadding'], compose: ['verticalSpacing'], ios: ['verticalGap'], web: ['descriptionMarginTop'] } },
    { name: 'labelStyle', type: 'typography', description: 'Стиль подписи', variations: ['size'], params: { xml: ['android:textAppearance'], compose: ['labelStyle'], ios: ['titleTypography'], web: ['labelFontFamily', 'labelFontSize', 'labelFontStyle', 'labelFontWeight', 'labelLetterSpacing', 'labelLineHeight'] } },
    { name: 'descriptionStyle', type: 'typography', description: 'Стиль описания', variations: ['size'], params: { xml: ['sd_descriptionTextAppearance'], compose: ['descriptionStyle'], ios: ['subtitleTypography'], web: ['descriptionFontFamily', 'descriptionFontSize', 'descriptionFontStyle', 'descriptionFontWeight', 'descriptionLetterSpacing', 'descriptionLineHeight'] } },
    { name: 'toggleCheckedBackgroundColor', type: 'color', description: 'Цвет фона тоггла', variations: ['view'], params: { xml: ['sd_buttonBoxColor'], compose: ['checkedColor'], ios: ['imageTintColor'], web: ['fillColor'] } },
    { name: 'toggleCheckedIconWidth', type: 'dimension', description: 'Ширина checked иконки тоггла', variations: ['size'] },
    { name: 'toggleCheckedIconHeight', type: 'dimension', description: 'Высота checked иконки тоггла', variations: ['size'] },
    { name: 'toggleIndeterminateIconWidth', type: 'dimension', description: 'Ширина indeterminate иконки тоггла', variations: ['size'] },
    { name: 'toggleIndeterminateIconHeight', type: 'dimension', description: 'Высота indeterminate иконки тоггла', variations: ['size'] },
    { name: 'horizontalPadding', type: 'dimension', description: 'Горизонтальный отступ между тогглом и текстом', variations: ['size'], params: { xml: ['android:drawablePadding'], compose: ['horizontalSpacing'], ios: ['horizontalGap'], web: ['contentLeftOffset'] } },
    { name: 'iconColor', type: 'color', description: 'Цвет иконки', variations: ['view'], params: { web: ['iconColor'] } },
    { name: 'labelColor', type: 'color', description: 'Цвет подписи', variations: ['view'], params: { xml: ['android:textColor'], compose: ['labelColor'], ios: ['titleColor'], web: ['labelColor'] } },
    { name: 'toggleBackgroundColor', type: 'color', description: 'Цвет фона тоггла в невыбранном варианте', variations: ['view'], params: { web: ['triggerBackgroundColor'] } },
    { name: 'toggleCheckedBorderColor', type: 'color', description: 'Цвет бордера тоггла', variations: ['view'], params: { web: ['triggerBorderCheckedColor'] } },
    { name: 'toggleBorderColor', type: 'color', description: 'Цвет бордера тоггла в невыбранном варианте', variations: ['view'], params: { xml: ['sd_buttonBorderColor'], compose: ['idleColor'], web: ['triggerBorderColor'] } },
];
