import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'textFieldPlaceholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldTextBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textFieldTextAfterColor', token: 'text.default.tertiary' },
            { prop: 'textFieldLabelColor', token: 'text.default.primary' },
            { prop: 'textFieldLeftHelperColor', token: 'text.default.secondary' },
            { prop: 'textFieldFocusColor', token: 'text.default.accent' },
            { prop: 'textFieldContentSlotColor', token: 'text.default.secondary' },
            { prop: 'textFieldContentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldContentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'textFieldIndicatorColor', token: 'surface.default.negative' },
            { prop: 'textFieldOptionalColor', token: 'text.default.tertiary' },
            { prop: 'buttonColor', token: 'text.inverse.primary' },
            { prop: 'buttonColorHover', token: 'text.inverse.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.inverse.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.inverse.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.inverse.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.inverse.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.solid-default-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.solid-default-hover' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'textFieldHintIconColor', token: 'text.default.secondary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        positive: [
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'textFieldPlaceholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-positive' },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-positive-active' },
            { prop: 'textFieldTextBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textFieldTextAfterColor', token: 'text.default.tertiary' },
            { prop: 'textFieldLabelColor', token: 'text.default.primary' },
            { prop: 'textFieldLeftHelperColor', token: 'text.default.positive' },
            { prop: 'textFieldFocusColor', token: 'text.default.accent' },
            { prop: 'textFieldContentSlotColor', token: 'text.default.secondary' },
            { prop: 'textFieldContentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldContentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'textFieldIndicatorColor', token: 'surface.default.negative' },
            { prop: 'textFieldOptionalColor', token: 'text.default.tertiary' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.positive' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.positive-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.positive-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'textFieldHintIconColor', token: 'text.default.secondary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        warning: [
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'textFieldPlaceholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-warning' },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-warning-active' },
            { prop: 'textFieldTextBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textFieldTextAfterColor', token: 'text.default.tertiary' },
            { prop: 'textFieldLabelColor', token: 'text.default.primary' },
            { prop: 'textFieldLeftHelperColor', token: 'text.default.warning' },
            { prop: 'textFieldFocusColor', token: 'text.default.accent' },
            { prop: 'textFieldContentSlotColor', token: 'text.default.secondary' },
            { prop: 'textFieldContentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldContentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'textFieldIndicatorColor', token: 'surface.default.negative' },
            { prop: 'textFieldOptionalColor', token: 'text.default.tertiary' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.warning' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.warning-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.warning-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'textFieldHintIconColor', token: 'text.default.secondary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        negative: [
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'textFieldPlaceholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-negative' },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-negative-active' },
            { prop: 'textFieldTextBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textFieldTextAfterColor', token: 'text.default.tertiary' },
            { prop: 'textFieldLabelColor', token: 'text.default.primary' },
            { prop: 'textFieldLeftHelperColor', token: 'text.default.negative' },
            { prop: 'textFieldFocusColor', token: 'text.default.accent' },
            { prop: 'textFieldContentSlotColor', token: 'text.default.secondary' },
            { prop: 'textFieldContentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldContentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'textFieldIndicatorColor', token: 'surface.default.negative' },
            { prop: 'textFieldOptionalColor', token: 'text.default.tertiary' },
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.negative' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.negative-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.negative-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'textFieldHintIconColor', token: 'text.default.secondary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        accent: [
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.accent' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.accent-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.accent-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        secondary: [
            { prop: 'buttonColor', token: 'text.default.primary' },
            { prop: 'buttonColorHover', token: 'text.default.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.default.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.default.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.default.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.default.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.transparent-secondary-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        clear: [
            { prop: 'buttonColor', token: 'text.default.primary' },
            { prop: 'buttonColorHover', token: 'text.default.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.default.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.default.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.default.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.default.secondary-active' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.clear' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.clear' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.clear' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        dark: [
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-dark.secondary-active' },
            { prop: 'buttonBackgroundColor', token: 'surface.on-light.transparent-deep' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.on-light.transparent-deep-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.on-light.transparent-deep-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        black: [
            { prop: 'buttonColor', token: 'text.on-dark.primary' },
            { prop: 'buttonColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-dark.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-dark.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-dark.secondary-active' },
            { prop: 'buttonBackgroundColor', token: 'surface.on-light.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.on-light.solid-default-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.on-light.solid-default-active' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
        white: [
            { prop: 'buttonColor', token: 'text.on-light.primary' },
            { prop: 'buttonColorHover', token: 'text.on-light.primary-hover' },
            { prop: 'buttonColorActive', token: 'text.on-light.primary-active' },
            { prop: 'buttonArrowColor', token: 'text.on-light.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.on-light.secondary-hover' },
            { prop: 'buttonArrowColorActive', token: 'text.on-light.secondary-active' },
            { prop: 'buttonBackgroundColor', token: 'surface.on-dark.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.on-dark.solid-default-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.on-dark.solid-default-active' },
            { prop: 'itemBackgroundHover', token: 'surface.default.transparent-secondary' },
            { prop: 'disclosureIconColor', token: 'text.default.secondary' },
            { prop: 'disclosureIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemDisabledColor', token: 'text.default.primary' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'itemIconColor', token: 'text.default.accent' },
            { prop: 'checkboxFillColor', token: 'text.default.accent' },
            { prop: 'checkboxIconColor', token: 'text.on-dark.primary' },
            { prop: 'checkboxTriggerBorderCheckedColor', value: 'transparent' },
            { prop: 'checkboxTriggerBorderColor', token: 'text.default.secondary' },
            { prop: 'itemDisabledOpacity', value: '0.4' },
        ],
    },
    size: {
        s: [
            { prop: 'textFieldChipWidth', value: 'auto' },
            { prop: 'textFieldHintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'emptyStatePadding', value: '0.625rem 0.875rem 0.625rem 0.875rem' },
            { prop: 'textFieldHeight', value: '40' },
            { prop: 'textFieldPaddingWithChips', value: '6' },
            { prop: 'textFieldContentRightWrapperGap', value: '4' },
            { prop: 'textFieldLabelOffset', value: '8' },
            { prop: 'textFieldHintTargetSize', value: '38' },
            { prop: 'textFieldIndicatorSizeInner', value: '6' },
            { prop: 'textFieldIndicatorSizeOuter', value: '6' },
            { prop: 'textFieldChipGap', value: '4' },
            { prop: 'textFieldChipHeight', value: '28' },
            { prop: 'textFieldChipClearContentMarginLeft', value: '6' },
            { prop: 'textFieldChipClearContentMarginRight', value: '0' },
            { prop: 'textFieldChipCloseIconSize', value: '16' },
            { prop: 'targetHeight', value: '40' },
            { prop: 'padding', value: '2' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'itemIconSize', value: '24' },
            { prop: 'itemIconSizeTight', value: '16' },
            { prop: 'itemGap', value: '6' },
            { prop: 'itemTreeOffsetWidth', value: '30' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '6' },
            { prop: 'checkboxTriggerSize', value: '20' },
            { prop: 'checkboxTriggerSizeTight', value: '14' },
            { prop: 'checkboxTriggerBorderRadiusTight', value: '4' },
            { prop: 'checkboxTriggerBorderWidth', value: '2' },
            { prop: 'indicatorSize', value: '6' },
            { prop: 'dividerMarginTop', value: '6' },
            { prop: 'dividerMarginRight', value: '12' },
            { prop: 'dividerMarginBottom', value: '6' },
            { prop: 'dividerMarginLeft', value: '12' },
            { prop: 'dividerMarginTopTight', value: '4' },
            { prop: 'dividerMarginBottomTight', value: '4' },
            { prop: 'textFieldStyle', value: 'body.s.normal' },
            { prop: 'textFieldLabelStyle', value: 'body.s.normal' },
            { prop: 'textFieldLeftHelperStyle', value: 'body.xs.normal' },
            { prop: 'textFieldChipStyle', value: 'body.s.normal' },
            { prop: 'cellTitleStyle', value: 'body.s.normal' },
            { prop: 'textStyle', value: 'body.s.normal' },
            { prop: 'textFieldBorderRadius', value: '10' },
            { prop: 'textFieldChipBorderRadius', value: '4' },
            { prop: 'borderRadius', value: '10' },
            { prop: 'itemBorderRadius', value: '8' },
            { prop: 'checkboxTriggerBorderRadius', token: 'round.xs' },
            { prop: 'textFieldPadding', value: '11', adjust: [{ platform: 'web', param: 'textFieldPadding', template: '$1 1rem $1 1rem' }] },
            { prop: 'textFieldLeftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-3', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldRightContentWithHintMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'textFieldRightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'textFieldContentRightWrapperMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'textFieldContentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldHintInnerLabelPlacementOffset', value: '0.992', adjust: [{ platform: 'web', param: 'textFieldHintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'textFieldClearHintInnerLabelPlacementOffset', value: '0.992', adjust: [{ platform: 'web', param: 'textFieldClearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
            { prop: 'textFieldLeftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'textFieldLabelInnerPadding', value: '5', adjust: [{ platform: 'web', param: 'textFieldLabelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'textFieldContentLabelInnerPadding', value: '17', adjust: [{ platform: 'web', param: 'textFieldContentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuter', value: '5', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'textFieldIndicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInner', value: '17.008', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInner', template: '$1 auto auto -0.875rem' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInnerRight', value: '17.008', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInnerRight', template: '$1 -0.875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorHintInnerRight', value: '17.008', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorHintInnerRight', template: '$1 -2.488rem auto auto' }] },
            { prop: 'textFieldChipPadding', value: '8', adjust: [{ platform: 'web', param: 'textFieldChipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'buttonArrowMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonPadding', value: '16', adjust: [{ platform: 'web', param: 'buttonPadding', template: '$1 0 $1' }] },
            { prop: 'itemPadding', value: '8', adjust: [{ platform: 'web', param: 'itemPadding', template: '$1 0.75rem' }] },
            { prop: 'itemPaddingTight', value: '4', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.75rem' }] },
            { prop: 'itemIconMargin', value: '6', adjust: [{ platform: 'web', param: 'itemIconMargin', template: '0 $1 0 0' }] },
        ],
        xs: [
            { prop: 'textFieldChipWidth', value: 'auto' },
            { prop: 'textFieldHintMargin', value: '-0.75rem -0.625rem -0.75rem -0.5rem' },
            { prop: 'emptyStatePadding', value: '0.5rem 0.625rem 0.5rem 0.625rem' },
            { prop: 'textFieldHeight', value: '32' },
            { prop: 'textFieldPaddingWithChips', value: '6' },
            { prop: 'textFieldContentRightWrapperGap', value: '4' },
            { prop: 'textFieldLabelOffset', value: '6' },
            { prop: 'textFieldHintTargetSize', value: '38' },
            { prop: 'textFieldIndicatorSizeInner', value: '6' },
            { prop: 'textFieldIndicatorSizeOuter', value: '6' },
            { prop: 'textFieldChipGap', value: '4' },
            { prop: 'textFieldChipHeight', value: '20' },
            { prop: 'textFieldChipClearContentMarginLeft', value: '4' },
            { prop: 'textFieldChipClearContentMarginRight', value: '0' },
            { prop: 'textFieldChipCloseIconSize', value: '12' },
            { prop: 'targetHeight', value: '32' },
            { prop: 'padding', value: '2' },
            { prop: 'itemHeight', value: '16' },
            { prop: 'itemIconSize', value: '16' },
            { prop: 'itemIconSizeTight', value: '16' },
            { prop: 'itemGap', value: '4' },
            { prop: 'itemTreeOffsetWidth', value: '20' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '4' },
            { prop: 'checkboxTriggerSize', value: '14' },
            { prop: 'checkboxTriggerSizeTight', value: '14' },
            { prop: 'checkboxTriggerBorderRadiusTight', value: '4' },
            { prop: 'checkboxTriggerBorderWidth', value: '2' },
            { prop: 'indicatorSize', value: '6' },
            { prop: 'dividerMarginTop', value: '4' },
            { prop: 'dividerMarginRight', value: '8' },
            { prop: 'dividerMarginBottom', value: '3.6' },
            { prop: 'dividerMarginLeft', value: '8' },
            { prop: 'dividerMarginTopTight', value: '2' },
            { prop: 'dividerMarginBottomTight', value: '2' },
            { prop: 'textFieldStyle', value: 'body.xs.normal' },
            { prop: 'textFieldLabelStyle', value: 'body.xs.normal' },
            { prop: 'textFieldLeftHelperStyle', value: 'body.xs.normal' },
            { prop: 'textFieldChipStyle', value: 'body.xs.normal' },
            { prop: 'cellTitleStyle', value: 'body.xs.normal' },
            { prop: 'textStyle', value: 'body.xs.normal' },
            { prop: 'textFieldBorderRadius', value: '8' },
            { prop: 'textFieldChipBorderRadius', value: '2' },
            { prop: 'borderRadius', value: '8' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'checkboxTriggerBorderRadius', token: 'round.xxs' },
            { prop: 'textFieldPadding', value: '9', adjust: [{ platform: 'web', param: 'textFieldPadding', template: '$1 1rem $1 1rem' }] },
            { prop: 'textFieldLeftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldRightContentWithHintMargin', value: '-11.008', adjust: [{ platform: 'web', param: 'textFieldRightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'textFieldContentRightWrapperMargin', value: '-11.008', adjust: [{ platform: 'web', param: 'textFieldContentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldHintInnerLabelPlacementOffset', value: '-3.008', adjust: [{ platform: 'web', param: 'textFieldHintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'textFieldClearHintInnerLabelPlacementOffset', value: '-3.008', adjust: [{ platform: 'web', param: 'textFieldClearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
            { prop: 'textFieldLeftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'textFieldLabelInnerPadding', value: '5', adjust: [{ platform: 'web', param: 'textFieldLabelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'textFieldContentLabelInnerPadding', value: '17', adjust: [{ platform: 'web', param: 'textFieldContentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuter', value: '4', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'textFieldIndicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuterRight', value: '2', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInner', value: '13.008', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInner', template: '$1 auto auto -0.875rem' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInnerRight', value: '13.008', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInnerRight', template: '$1 -0.875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorHintInnerRight', value: '13.008', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorHintInnerRight', template: '$1 -2.488rem auto auto' }] },
            { prop: 'textFieldChipPadding', value: '6', adjust: [{ platform: 'web', param: 'textFieldChipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'buttonArrowMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonPadding', value: '12', adjust: [{ platform: 'web', param: 'buttonPadding', template: '$1 0 $1' }] },
            { prop: 'itemPadding', value: '8', adjust: [{ platform: 'web', param: 'itemPadding', template: '$1 0.75rem' }] },
            { prop: 'itemPaddingTight', value: '4', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.75rem' }] },
            { prop: 'itemIconMargin', value: '4', adjust: [{ platform: 'web', param: 'itemIconMargin', template: '0 $1 0 0' }] },
        ],
        l: [
            { prop: 'textFieldChipWidth', value: 'auto' },
            { prop: 'emptyStatePadding', value: '1rem' },
            { prop: 'textFieldHintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'textFieldHeight', value: '56' },
            { prop: 'textFieldPaddingWithChips', value: '6' },
            { prop: 'textFieldContentRightWrapperGap', value: '4' },
            { prop: 'textFieldLabelOffset', value: '12' },
            { prop: 'textFieldHintTargetSize', value: '38' },
            { prop: 'textFieldIndicatorSizeInner', value: '8' },
            { prop: 'textFieldIndicatorSizeOuter', value: '6' },
            { prop: 'textFieldChipGap', value: '4' },
            { prop: 'textFieldChipHeight', value: '44' },
            { prop: 'textFieldChipClearContentMarginLeft', value: '10' },
            { prop: 'textFieldChipClearContentMarginRight', value: '0' },
            { prop: 'textFieldChipCloseIconSize', value: '24' },
            { prop: 'targetHeight', value: '56' },
            { prop: 'padding', value: '2' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'itemIconSize', value: '24' },
            { prop: 'itemIconSizeTight', value: '24' },
            { prop: 'itemGap', value: '8' },
            { prop: 'itemTreeOffsetWidth', value: '32' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '6' },
            { prop: 'checkboxTriggerSize', value: '20' },
            { prop: 'checkboxTriggerSizeTight', value: '20' },
            { prop: 'checkboxTriggerBorderRadiusTight', value: '6' },
            { prop: 'checkboxTriggerBorderWidth', value: '2' },
            { prop: 'indicatorSize', value: '6' },
            { prop: 'dividerMarginTop', value: '8' },
            { prop: 'dividerMarginRight', value: '16' },
            { prop: 'dividerMarginBottom', value: '8' },
            { prop: 'dividerMarginLeft', value: '16' },
            { prop: 'dividerMarginTopTight', value: '6' },
            { prop: 'dividerMarginBottomTight', value: '6' },
            { prop: 'textFieldStyle', value: 'body.l.normal' },
            { prop: 'textFieldLabelStyle', value: 'body.l.normal' },
            { prop: 'textFieldLeftHelperStyle', value: 'body.xs.normal' },
            { prop: 'textFieldChipStyle', value: 'body.l.normal' },
            { prop: 'cellTitleStyle', value: 'body.l.normal' },
            { prop: 'textStyle', value: 'body.l.normal' },
            { prop: 'textFieldBorderRadius', value: '14' },
            { prop: 'textFieldChipBorderRadius', value: '8' },
            { prop: 'borderRadius', value: '14' },
            { prop: 'itemBorderRadius', value: '12' },
            { prop: 'checkboxTriggerBorderRadius', token: 'round.xs' },
            { prop: 'textFieldPadding', value: '17', adjust: [{ platform: 'web', param: 'textFieldPadding', template: '$1 1rem $1 1rem' }] },
            { prop: 'textFieldLeftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldRightContentWithHintMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'textFieldRightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'textFieldContentRightWrapperMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'textFieldContentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldHintInnerLabelPlacementOffset', value: '9.008', adjust: [{ platform: 'web', param: 'textFieldHintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'textFieldClearHintInnerLabelPlacementOffset', value: '9.008', adjust: [{ platform: 'web', param: 'textFieldClearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
            { prop: 'textFieldLeftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'textFieldLabelInnerPadding', value: '9', adjust: [{ platform: 'web', param: 'textFieldLabelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'textFieldContentLabelInnerPadding', value: '25', adjust: [{ platform: 'web', param: 'textFieldContentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuter', value: '8', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'textFieldIndicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInner', value: '24', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInner', template: '$1 auto auto -0.875rem' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInnerRight', value: '24', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInnerRight', template: '$1 -0.875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorHintInnerRight', value: '24', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorHintInnerRight', template: '$1 -2.488rem auto auto' }] },
            { prop: 'textFieldChipPadding', value: '12', adjust: [{ platform: 'web', param: 'textFieldChipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'buttonArrowMargin', value: '8', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonPadding', value: '24', adjust: [{ platform: 'web', param: 'buttonPadding', template: '$1 0 $1' }] },
            { prop: 'itemPadding', value: '16', adjust: [{ platform: 'web', param: 'itemPadding', template: '$1 0.75rem' }] },
            { prop: 'itemPaddingTight', value: '12', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.75rem' }] },
            { prop: 'itemIconMargin', value: '8', adjust: [{ platform: 'web', param: 'itemIconMargin', template: '0 $1 0 0' }] },
        ],
        m: [
            { prop: 'textFieldChipWidth', value: 'auto' },
            { prop: 'textFieldHintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'emptyStatePadding', value: '0.875rem 1rem 0.875rem 1rem' },
            { prop: 'textFieldHeight', value: '48' },
            { prop: 'textFieldPaddingWithChips', value: '6' },
            { prop: 'textFieldContentRightWrapperGap', value: '4' },
            { prop: 'textFieldLabelOffset', value: '10' },
            { prop: 'textFieldHintTargetSize', value: '38' },
            { prop: 'textFieldIndicatorSizeInner', value: '8' },
            { prop: 'textFieldIndicatorSizeOuter', value: '6' },
            { prop: 'textFieldChipGap', value: '4' },
            { prop: 'textFieldChipHeight', value: '36' },
            { prop: 'textFieldChipClearContentMarginLeft', value: '8' },
            { prop: 'textFieldChipClearContentMarginRight', value: '0' },
            { prop: 'textFieldChipCloseIconSize', value: '20' },
            { prop: 'targetHeight', value: '48' },
            { prop: 'padding', value: '2' },
            { prop: 'itemHeight', value: '24' },
            { prop: 'itemIconSize', value: '24' },
            { prop: 'itemIconSizeTight', value: '24' },
            { prop: 'itemGap', value: '6' },
            { prop: 'itemTreeOffsetWidth', value: '32' },
            { prop: 'cellPadding', value: '0' },
            { prop: 'cellPaddingLeftContent', value: '0' },
            { prop: 'cellPaddingContent', value: '0' },
            { prop: 'cellPaddingRightContent', value: '0' },
            { prop: 'cellTextboxGap', value: '2' },
            { prop: 'cellGap', value: '6' },
            { prop: 'checkboxTriggerSize', value: '20' },
            { prop: 'checkboxTriggerSizeTight', value: '20' },
            { prop: 'checkboxTriggerBorderRadiusTight', value: '6' },
            { prop: 'checkboxTriggerBorderWidth', value: '2' },
            { prop: 'indicatorSize', value: '6' },
            { prop: 'dividerMarginTop', value: '6' },
            { prop: 'dividerMarginRight', value: '14' },
            { prop: 'dividerMarginBottom', value: '6' },
            { prop: 'dividerMarginLeft', value: '14' },
            { prop: 'dividerMarginTopTight', value: '6' },
            { prop: 'dividerMarginBottomTight', value: '6' },
            { prop: 'textFieldStyle', value: 'body.m.normal' },
            { prop: 'textFieldLabelStyle', value: 'body.m.normal' },
            { prop: 'textFieldLeftHelperStyle', value: 'body.xs.normal' },
            { prop: 'textFieldChipStyle', value: 'body.m.normal' },
            { prop: 'cellTitleStyle', value: 'body.m.normal' },
            { prop: 'textStyle', value: 'body.m.normal' },
            { prop: 'textFieldBorderRadius', value: '12' },
            { prop: 'textFieldChipBorderRadius', value: '6' },
            { prop: 'borderRadius', value: '12' },
            { prop: 'itemBorderRadius', value: '10' },
            { prop: 'checkboxTriggerBorderRadius', token: 'round.xs' },
            { prop: 'textFieldPadding', value: '14', adjust: [{ platform: 'web', param: 'textFieldPadding', template: '$1 1rem $1 1rem' }] },
            { prop: 'textFieldLeftContentMargin', value: '6', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-2', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldRightContentWithHintMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'textFieldRightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'textFieldContentRightWrapperMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'textFieldContentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldHintInnerLabelPlacementOffset', value: '4.992', adjust: [{ platform: 'web', param: 'textFieldHintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'textFieldClearHintInnerLabelPlacementOffset', value: '4.992', adjust: [{ platform: 'web', param: 'textFieldClearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
            { prop: 'textFieldLeftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'textFieldLabelInnerPadding', value: '6', adjust: [{ platform: 'web', param: 'textFieldLabelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'textFieldContentLabelInnerPadding', value: '22', adjust: [{ platform: 'web', param: 'textFieldContentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuter', value: '6', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'textFieldIndicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'textFieldIndicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'textFieldIndicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInner', value: '20', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInner', template: '$1 auto auto -0.875rem' }] },
            { prop: 'textFieldClearIndicatorLabelPlacementInnerRight', value: '20', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorLabelPlacementInnerRight', template: '$1 -0.875rem auto auto' }] },
            { prop: 'textFieldClearIndicatorHintInnerRight', value: '20', adjust: [{ platform: 'web', param: 'textFieldClearIndicatorHintInnerRight', template: '$1 -2.488rem auto auto' }] },
            { prop: 'textFieldChipPadding', value: '10', adjust: [{ platform: 'web', param: 'textFieldChipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'buttonArrowMargin', value: '6', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonPadding', value: '20', adjust: [{ platform: 'web', param: 'buttonPadding', template: '$1 0 $1' }] },
            { prop: 'itemPadding', value: '12', adjust: [{ platform: 'web', param: 'itemPadding', template: '$1 0.75rem' }] },
            { prop: 'itemPaddingTight', value: '8', adjust: [{ platform: 'web', param: 'itemPaddingTight', template: '$1 0.75rem' }] },
            { prop: 'itemIconMargin', value: '6', adjust: [{ platform: 'web', param: 'itemIconMargin', template: '0 $1 0 0' }] },
        ],
    },
    labelPlacement: {
        inner: [
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'textFieldLabelInnerStyle', value: 'body.xs.normal' },
        ],
    },
    chipView: {
        default: [
            { prop: 'textFieldChipColor', token: 'text.inverse.primary' },
            { prop: 'textFieldChipColorHover', token: 'text.inverse.primary' },
            { prop: 'textFieldChipBackground', token: 'surface.default.solid-default' },
            { prop: 'textFieldChipBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'textFieldChipCloseIconColor', token: 'text.inverse.secondary' },
            { prop: 'textFieldChipCloseIconColorReadonly', token: 'text.inverse.secondary' },
            { prop: 'textFieldChipCloseIconColorHover', token: 'text.inverse.primary' },
            { prop: 'textFieldChipBackgroundReadOnly', token: 'surface.default.solid-default' },
            { prop: 'textFieldChipColorReadOnly', token: 'text.inverse.primary' },
            { prop: 'textFieldChipBackgroundReadOnlyHover', token: 'surface.default.solid-default' },
            { prop: 'textFieldChipColorReadOnlyHover', token: 'text.inverse.primary' },
            { prop: 'textFieldChipOpacityReadonly', value: '1' },
        ],
        secondary: [
            { prop: 'textFieldChipColor', token: 'text.default.primary' },
            { prop: 'textFieldChipColorHover', token: 'text.default.primary' },
            { prop: 'textFieldChipBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldChipBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'textFieldChipCloseIconColor', token: 'text.default.secondary' },
            { prop: 'textFieldChipCloseIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldChipCloseIconColorReadonly', token: 'text.default.secondary' },
            { prop: 'textFieldChipBackgroundReadOnly', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldChipColorReadOnly', token: 'text.default.primary' },
            { prop: 'textFieldChipBackgroundReadOnlyHover', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldChipColorReadOnlyHover', token: 'text.default.primary' },
            { prop: 'textFieldChipOpacityReadonly', value: '1' },
        ],
        accent: [
            { prop: 'textFieldChipColor', token: 'text.on-dark.primary' },
            { prop: 'textFieldChipColorHover', token: 'text.on-dark.primary' },
            { prop: 'textFieldChipBackground', token: 'surface.default.accent' },
            { prop: 'textFieldChipBackgroundHover', token: 'surface.default.accent-hover' },
            { prop: 'textFieldChipCloseIconColor', token: 'text.on-dark.secondary' },
            { prop: 'textFieldChipCloseIconColorReadonly', token: 'text.on-dark.secondary' },
            { prop: 'textFieldChipCloseIconColorHover', token: 'text.on-dark.primary' },
            { prop: 'textFieldChipBackgroundReadOnly', token: 'surface.default.accent' },
            { prop: 'textFieldChipColorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'textFieldChipBackgroundReadOnlyHover', token: 'surface.default.accent' },
            { prop: 'textFieldChipColorReadOnlyHover', token: 'text.on-dark.primary' },
            { prop: 'textFieldChipOpacityReadonly', value: '1' },
        ],
    },
    hintView: {
        default: [
            { prop: 'textFieldTooltipBackgroundColor', token: 'surface.default.solid-card-brightness' },
            { prop: 'textFieldTooltipBoxShadow', value: 'down.hard.m' },
            { prop: 'textFieldTooltipColor', token: 'text.default.primary' },
            { prop: 'textFieldTooltipArrowBackground', token: 'surface.default.solid-card' },
        ],
    },
    hintSize: {
        m: [
            { prop: 'textFieldTooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMC4xNywxMS44M2wyMCwwYy01LjUyLDAgLTEwLDMuNTkgLTEwLDhjMCwtNC40MSAtNC40OCwtOCAtMTAsLTh6IiBmaWxsPSIjMTcxNzE3IiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGlkPSJUYWlsIi8+Cjwvc3ZnPg==")' },
            { prop: 'textFieldTooltipPaddingTop', value: '11' },
            { prop: 'textFieldTooltipPaddingRight', value: '14' },
            { prop: 'textFieldTooltipPaddingBottom', value: '11' },
            { prop: 'textFieldTooltipPaddingLeft', value: '14' },
            { prop: 'textFieldTooltipMinHeight', value: '40' },
            { prop: 'textFieldTooltipContentLeftMargin', value: '6' },
            { prop: 'textFieldTooltipArrowMaskWidth', value: '20' },
            { prop: 'textFieldTooltipArrowMaskHeight', value: '20' },
            { prop: 'textFieldTooltipArrowHeight', value: '8' },
            { prop: 'textFieldTooltipArrowEdgeMargin', value: '10' },
            { prop: 'textFieldTooltipTextStyle', value: 'body.s.normal' },
            { prop: 'textFieldTooltipBorderRadius', value: '10' },
        ],
        s: [
            { prop: 'textFieldTooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMCw5Ljg1bDE2LDBjLTQuNDEsMCAtOCwyLjY5IC04LDZjMCwtMy4zMSAtMy41OSwtNiAtOCwtNnoiIGZpbGw9IiMxNzE3MTciIGZpbGwtcnVsZT0iZXZlbm9kZCIgaWQ9IlRhaWwiLz4KPC9zdmc+")' },
            { prop: 'textFieldTooltipPaddingTop', value: '8' },
            { prop: 'textFieldTooltipPaddingRight', value: '12' },
            { prop: 'textFieldTooltipPaddingBottom', value: '8' },
            { prop: 'textFieldTooltipPaddingLeft', value: '12' },
            { prop: 'textFieldTooltipMinHeight', value: '32' },
            { prop: 'textFieldTooltipContentLeftMargin', value: '4' },
            { prop: 'textFieldTooltipArrowMaskWidth', value: '16' },
            { prop: 'textFieldTooltipArrowMaskHeight', value: '16' },
            { prop: 'textFieldTooltipArrowHeight', value: '6' },
            { prop: 'textFieldTooltipArrowEdgeMargin', value: '9' },
            { prop: 'textFieldTooltipTextStyle', value: 'body.xs.normal' },
            { prop: 'textFieldTooltipBorderRadius', value: '8' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'textFieldDisabledOpacity', value: '0.4' },
    { prop: 'textFieldColorReadOnly', token: 'text.default.primary' },
    { prop: 'textFieldBackgroundColorReadOnly', token: 'surface.default.transparent-primary' },
    { prop: 'textFieldPlaceholderColorReadOnly', token: 'text.default.secondary' },
    { prop: 'textFieldLeftHelperColorReadOnly', token: 'text.default.secondary' },
    { prop: 'textFieldTitleCaptionColorReadOnly', token: 'text.default.secondary' },
    { prop: 'textFieldLabelColorReadOnly', token: 'text.default.primary' },
    { prop: 'disclosureIconOpacityReadOnly', value: '0.4' },
    { prop: 'textFieldReadOnlyOpacity', value: '0.1' },
];
