export const ROBO_COMMENT = '// Generated by robots, do not change this manually!\n\n';
export const CSS_ROBO_COMMENT = '/* Generated by robots, do not change this manually! */\n';

export const WEB_BREAKPOINTS = {
    screenS: { from: 559, to: undefined },
    screenM: { from: 560, to: 959 },
    screenL: { from: undefined, to: 960 },
};
