import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'iconButtonSegmentationRadius', type: 'dimension', variations: ['size', 'segmentation'], params: { web: ['iconButtonSegmentationRadius'] } },
    { name: 'inputWrapperBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['inputWrapperBorderRadius'] } },
    { name: 'inputWrapperMargin', type: 'dimension', variations: ['size'], params: { web: ['inputWrapperMargin'] } },
    { name: 'color', type: 'color', variations: ['view'], params: { web: ['color'] } },
    { name: 'textWrapperPadding', type: 'dimension', variations: ['size'], params: { web: ['textWrapperPadding'] } },
    { name: 'iconButtonBackgroundColorActive', type: 'color', variations: ['view'], params: { web: ['iconButtonBackgroundColorActive'] } },
    { name: 'loaderSpinnerColor', type: 'color', variations: ['view'], params: { web: ['loaderSpinnerColor'] } },
    { name: 'loaderSpinnerColorSolid', type: 'color', variations: ['view'], params: { web: ['loaderSpinnerColorSolid'] } },
    { name: 'caretColorSolid', type: 'color', variations: ['view'], params: { web: ['caretColorSolid'] } },
    { name: 'iconButtonStyle', type: 'typography', variations: ['size'], params: { web: ['iconButtonFontFamily', 'iconButtonFontSize', 'iconButtonFontStyle', 'iconButtonFontWeight', 'iconButtonLetterSpacing', 'iconButtonLineHeight'] } },
    { name: 'iconButtonRadius', type: 'value', variations: ['size', 'shape'], params: { web: ['iconButtonRadius'] } },
    { name: 'textStyle', type: 'typography', variations: ['size'], params: { web: ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'letterSpacing', 'lineHeight'] } },
    { name: 'backgroundColor', type: 'color', variations: ['inputBackgroundType'], params: { web: ['backgroundColor'] } },
    { name: 'backgroundColorHover', type: 'color', variations: ['inputBackgroundType'], params: { web: ['backgroundColorHover'] } },
    { name: 'caretColor', type: 'color', variations: ['view'], params: { web: ['caretColor'] } },
    { name: 'errorColor', type: 'color', variations: ['view'], params: { web: ['errorColor'] } },
    { name: 'backgroundErrorColor', type: 'color', variations: ['view'], params: { web: ['backgroundErrorColor'] } },
    { name: 'colorSolid', type: 'color', variations: ['view'], params: { web: ['colorSolid'] } },
    { name: 'additionalTextColor', type: 'color', variations: ['view'], params: { web: ['additionalTextColor'] } },
    { name: 'additionalTextColorSolid', type: 'color', variations: ['view'], params: { web: ['additionalTextColorSolid'] } },
    { name: 'backgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['backgroundColorFocus'] } },
    { name: 'backgroundColorSolidFocus', type: 'color', variations: ['view'], params: { web: ['backgroundColorSolidFocus'] } },
    { name: 'iconButtonColor', type: 'color', variations: ['view'], params: { web: ['iconButtonColor'] } },
    { name: 'iconButtonBackgroundColor', type: 'color', variations: ['view'], params: { web: ['iconButtonBackgroundColor'] } },
    { name: 'iconButtonColorHover', type: 'color', variations: ['view'], params: { web: ['iconButtonColorHover'] } },
    { name: 'iconButtonColorSolidHover', type: 'color', variations: ['view'], params: { web: ['iconButtonColorSolidHover'] } },
    { name: 'iconButtonBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['iconButtonBackgroundColorHover'] } },
    { name: 'iconButtonColorActive', type: 'color', variations: ['view'], params: { web: ['iconButtonColorActive'] } },
    { name: 'iconButtonColorSolidActive', type: 'color', variations: ['view'], params: { web: ['iconButtonColorSolidActive'] } },
    { name: 'actionButtonDisabledOpacity', type: 'float', variations: ['view'], params: { web: ['actionButtonDisabledOpacity'] } },
    { name: 'rootMinWidth', type: 'dimension', variations: ['size'], params: { web: ['rootMinWidth'] } },
    { name: 'iconButtonHeight', type: 'dimension', variations: ['size'], params: { web: ['iconButtonHeight'] } },
    { name: 'iconButtonWidth', type: 'dimension', variations: ['size'], params: { web: ['iconButtonWidth'] } },
    { name: 'iconButtonPadding', type: 'dimension', variations: ['size'], params: { web: ['iconButtonPadding'] } },
    { name: 'textWrapperHeight', type: 'dimension', variations: ['size'], params: { web: ['textWrapperHeight'] } },
    { name: 'textBeforeMarginRight', type: 'dimension', variations: ['size'], params: { web: ['textBeforeMarginRight'] } },
    { name: 'textAfterMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['textAfterMarginLeft'] } },
    { name: 'loaderSpinnerSize', type: 'dimension', variations: ['size'], params: { web: ['loaderSpinnerSize'] } },
    { name: 'disabledOpacity', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'backgroundColorSolid', type: 'color', variations: ['view'], params: { web: ['backgroundColorSolid'] } },
];
