import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'actionButtonDisabledOpacity', value: '0.4' },
            { prop: 'additionalTextColorSolid', token: 'text.inverse.tertiary' },
            { prop: 'backgroundColorSolid', token: 'surface.default.solid-default' },
            { prop: 'backgroundErrorColor', token: 'surface.default.transparent-negative' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'errorColor', token: 'text.default.negative' },
            { prop: 'iconButtonBackgroundColorActive', token: 'surface.default.solid-default-active' },
            { prop: 'iconButtonColor', token: 'text.inverse.primary' },
            { prop: 'iconButtonColorHover', token: 'text.inverse.primary' },
            { prop: 'iconButtonColorSolidHover', token: 'text.inverse.primary-hover' },
            { prop: 'loaderSpinnerColorSolid', value: 'inherit' },
            { prop: 'additionalTextColor', token: 'text.default.tertiary' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundColorSolidFocus', token: 'surface.inverse.transparent-secondary' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'colorSolid', token: 'text.inverse.primary' },
            { prop: 'iconButtonBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'iconButtonBackgroundColorHover', token: 'surface.default.solid-default-hover' },
            { prop: 'iconButtonColorActive', token: 'text.inverse.primary' },
            { prop: 'iconButtonColorSolidActive', token: 'text.inverse.primary-active' },
            { prop: 'loaderSpinnerColor', value: 'inherit' },
        ],
        secondary: [
            { prop: 'additionalTextColor', token: 'text.default.tertiary' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundColorSolidFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'colorSolid', token: 'text.default.primary' },
            { prop: 'iconButtonBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'iconButtonBackgroundColorHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'iconButtonColorActive', token: 'text.default.primary' },
            { prop: 'iconButtonColorSolidActive', token: 'text.default.primary-active' },
            { prop: 'loaderSpinnerColor', value: 'inherit' },
            { prop: 'actionButtonDisabledOpacity', value: '0.4' },
            { prop: 'additionalTextColorSolid', token: 'text.default.tertiary' },
            { prop: 'backgroundColorSolid', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundErrorColor', token: 'surface.default.transparent-negative' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'errorColor', token: 'text.default.negative' },
            { prop: 'iconButtonBackgroundColorActive', token: 'surface.default.transparent-secondary-active' },
            { prop: 'iconButtonColor', token: 'text.default.primary' },
            { prop: 'iconButtonColorHover', token: 'text.default.primary' },
            { prop: 'iconButtonColorSolidHover', token: 'text.default.primary-hover' },
            { prop: 'loaderSpinnerColorSolid', value: 'inherit' },
        ],
        accent: [
            { prop: 'actionButtonDisabledOpacity', value: '0.4' },
            { prop: 'additionalTextColorSolid', token: 'text.on-dark.tertiary' },
            { prop: 'backgroundColorSolid', token: 'surface.default.accent' },
            { prop: 'backgroundErrorColor', token: 'surface.default.transparent-negative' },
            { prop: 'caretColorSolid', token: 'text.inverse.primary' },
            { prop: 'colorSolid', token: 'text.on-dark.primary' },
            { prop: 'iconButtonBackgroundColor', token: 'surface.default.accent' },
            { prop: 'iconButtonBackgroundColorHover', token: 'surface.default.accent-hover' },
            { prop: 'iconButtonColorActive', token: 'text.inverse.primary' },
            { prop: 'iconButtonColorSolidActive', token: 'text.on-dark.primary-active' },
            { prop: 'loaderSpinnerColor', value: 'inherit' },
            { prop: 'additionalTextColor', token: 'text.default.tertiary' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundColorSolidFocus', token: 'surface.on-dark.transparent-secondary' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'errorColor', token: 'text.default.negative' },
            { prop: 'iconButtonBackgroundColorActive', token: 'surface.default.accent-active' },
            { prop: 'iconButtonColor', token: 'text.on-dark.primary' },
            { prop: 'iconButtonColorHover', token: 'text.inverse.primary' },
            { prop: 'iconButtonColorSolidHover', token: 'text.on-dark.primary-hover' },
            { prop: 'loaderSpinnerColorSolid', value: 'inherit' },
        ],
        clear: [
            { prop: 'additionalTextColor', token: 'text.default.tertiary' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundColorSolidFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'errorColor', token: 'text.default.negative' },
            { prop: 'iconButtonBackgroundColorActive', value: 'transparent' },
            { prop: 'iconButtonColor', token: 'text.default.primary' },
            { prop: 'iconButtonColorHover', token: 'text.default.primary-hover' },
            { prop: 'loaderSpinnerColor', value: 'inherit' },
            { prop: 'actionButtonDisabledOpacity', value: '0.4' },
            { prop: 'additionalTextColorSolid', token: 'text.default.tertiary' },
            { prop: 'backgroundColorSolid', value: 'transparent' },
            { prop: 'backgroundErrorColor', token: 'surface.default.transparent-negative' },
            { prop: 'caretColorSolid', token: 'text.default.accent' },
            { prop: 'colorSolid', token: 'text.default.primary' },
            { prop: 'iconButtonBackgroundColor', value: 'transparent' },
            { prop: 'iconButtonBackgroundColorHover', value: 'transparent' },
            { prop: 'iconButtonColorActive', token: 'text.default.primary-active' },
            { prop: 'iconButtonColorSolidHover', token: 'text.default.primary-hover' },
            { prop: 'loaderSpinnerColorSolid', value: 'inherit' },
        ],
    },
    size: {
        l: [
            { prop: 'iconButtonHeight', value: '56' },
            { prop: 'iconButtonRadius', value: '0.875rem' },
            { prop: 'iconButtonStyle', value: 'body.l.bold' },
            { prop: 'inputWrapperBorderRadius', value: '14' },
            { prop: 'rootMinWidth', value: '188' },
            { prop: 'textBeforeMarginRight', value: '4' },
            { prop: 'textWrapperHeight', value: '56' },
            { prop: 'iconButtonPadding', value: '24' },
            { prop: 'iconButtonSegmentationRadius', value: '6' },
            { prop: 'iconButtonWidth', value: '56' },
            { prop: 'inputWrapperMargin', value: '2', adjust: [{ platform: 'web', param: 'inputWrapperMargin', template: '0 $1' }] },
            { prop: 'loaderSpinnerSize', value: '22' },
            { prop: 'textAfterMarginLeft', value: '4' },
            { prop: 'textStyle', value: 'body.l.normal' },
            { prop: 'textWrapperPadding', value: '17.008', adjust: [{ platform: 'web', param: 'textWrapperPadding', template: '$1 1.125rem' }] },
        ],
        m: [
            { prop: 'iconButtonHeight', value: '48' },
            { prop: 'iconButtonRadius', value: '0.75rem' },
            { prop: 'iconButtonStyle', value: 'body.m.bold' },
            { prop: 'inputWrapperBorderRadius', value: '12' },
            { prop: 'rootMinWidth', value: '164' },
            { prop: 'textBeforeMarginRight', value: '4' },
            { prop: 'textWrapperHeight', value: '48' },
            { prop: 'iconButtonPadding', value: '20' },
            { prop: 'iconButtonSegmentationRadius', value: '4' },
            { prop: 'iconButtonWidth', value: '48' },
            { prop: 'inputWrapperMargin', value: '2', adjust: [{ platform: 'web', param: 'inputWrapperMargin', template: '0 $1' }] },
            { prop: 'loaderSpinnerSize', value: '22' },
            { prop: 'textAfterMarginLeft', value: '4' },
            { prop: 'textStyle', value: 'body.m.normal' },
            { prop: 'textWrapperPadding', value: '14', adjust: [{ platform: 'web', param: 'textWrapperPadding', template: '$1 1.125rem' }] },
        ],
        s: [
            { prop: 'iconButtonPadding', value: '16' },
            { prop: 'iconButtonSegmentationRadius', value: '4' },
            { prop: 'iconButtonWidth', value: '40' },
            { prop: 'inputWrapperMargin', value: '2', adjust: [{ platform: 'web', param: 'inputWrapperMargin', template: '0 $1' }] },
            { prop: 'loaderSpinnerSize', value: '22' },
            { prop: 'textAfterMarginLeft', value: '4' },
            { prop: 'textStyle', value: 'body.s.normal' },
            { prop: 'textWrapperPadding', value: '11.008', adjust: [{ platform: 'web', param: 'textWrapperPadding', template: '$1 1.125rem' }] },
            { prop: 'iconButtonHeight', value: '40' },
            { prop: 'iconButtonRadius', value: '0.625rem' },
            { prop: 'iconButtonStyle', value: 'body.s.bold' },
            { prop: 'inputWrapperBorderRadius', value: '10' },
            { prop: 'rootMinWidth', value: '140' },
            { prop: 'textBeforeMarginRight', value: '4' },
            { prop: 'textWrapperHeight', value: '40' },
        ],
        xs: [
            { prop: 'iconButtonHeight', value: '32' },
            { prop: 'iconButtonRadius', value: '0.5rem' },
            { prop: 'iconButtonStyle', value: 'body.xs.bold' },
            { prop: 'inputWrapperBorderRadius', value: '8' },
            { prop: 'rootMinWidth', value: '110' },
            { prop: 'textBeforeMarginRight', value: '4' },
            { prop: 'textWrapperHeight', value: '32' },
            { prop: 'iconButtonPadding', value: '12' },
            { prop: 'iconButtonSegmentationRadius', value: '2' },
            { prop: 'iconButtonWidth', value: '32' },
            { prop: 'inputWrapperMargin', value: '2', adjust: [{ platform: 'web', param: 'inputWrapperMargin', template: '0 $1' }] },
            { prop: 'loaderSpinnerSize', value: '16' },
            { prop: 'textAfterMarginLeft', value: '4' },
            { prop: 'textStyle', value: 'body.xs.normal' },
            { prop: 'textWrapperPadding', value: '9.008', adjust: [{ platform: 'web', param: 'textWrapperPadding', template: '$1 1.125rem' }] },
        ],
    },
    shape: {
        pilled: [
            { prop: 'iconButtonRadius', value: '50%' },
        ],
    },
    inputBackgroundType: {
        fill: [
            { prop: 'backgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'backgroundColorHover', token: 'surface.default.transparent-primary' },
        ],
        clear: [
            { prop: 'backgroundColorHover', value: 'transparent' },
            { prop: 'backgroundColor', value: 'transparent' },
        ],
    },
    segmentation: {
        solid: [
            { prop: 'iconButtonSegmentationRadius', value: '0' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
];
