import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'itemColor', type: 'color', variations: ['view'], params: { web: ['itemColor'] } },
    { name: 'itemValueColor', type: 'color', variations: ['view'], params: { web: ['itemValueColor'] } },
    { name: 'itemBackgroundColor', type: 'color', variations: ['view'], params: { web: ['itemBackgroundColor'] } },
    { name: 'itemColorHover', type: 'color', variations: ['view'], params: { web: ['itemColorHover'] } },
    { name: 'itemValueColorHover', type: 'color', variations: ['view'], params: { web: ['itemValueColorHover'] } },
    { name: 'itemColorActive', type: 'color', variations: ['view'], params: { web: ['itemColorActive'] } },
    { name: 'itemValueColorActive', type: 'color', variations: ['view'], params: { web: ['itemValueColorActive'] } },
    { name: 'itemBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['itemBackgroundColorHover'] } },
    { name: 'itemSelectedColor', type: 'color', variations: ['view'], params: { web: ['itemSelectedColor'] } },
    { name: 'itemSelectedValueColor', type: 'color', variations: ['view'], params: { web: ['itemSelectedValueColor'] } },
    { name: 'itemSelectedBackgroundColor', type: 'color', variations: ['view'], params: { web: ['itemSelectedBackgroundColor'] } },
    { name: 'itemSelectedColorHover', type: 'color', variations: ['view'], params: { web: ['itemSelectedColorHover'] } },
    { name: 'itemSelectedValueColorHover', type: 'color', variations: ['view'], params: { web: ['itemSelectedValueColorHover'] } },
    { name: 'itemSelectedBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['itemSelectedBackgroundColorHover'] } },
    { name: 'itemBackgroundTransition', type: 'value', variations: ['view'], params: { web: ['itemBackgroundTransition'] } },
    { name: 'outlineFocusColor', type: 'color', variations: ['view'], params: { web: ['outlineFocusColor'] } },
    { name: 'itemSelectedDividerColor', type: 'color', variations: ['view'], params: { web: ['itemSelectedDividerColor'] } },
    { name: 'itemSelectedDividerColorHover', type: 'color', variations: ['view'], params: { web: ['itemSelectedDividerColorHover'] } },
    { name: 'itemCursor', type: 'value', variations: ['view'], params: { web: ['itemCursor'] } },
    { name: 'itemWidth', type: 'value', variations: ['size'], params: { web: ['itemWidth'] } },
    { name: 'textStyle', type: 'typography', variations: ['size'], params: { web: ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'letterSpacing', 'lineHeight'] } },
    { name: 'itemSelectedDividerHeight', type: 'dimension', variations: ['view'], params: { web: ['itemSelectedDividerHeight'] } },
    { name: 'itemMarginLeftFilled', type: 'dimension', variations: ['view'], params: { web: ['itemMarginLeftFilled'] } },
    { name: 'itemHeight', type: 'dimension', variations: ['size'], params: { web: ['itemHeight'] } },
    { name: 'itemMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['itemMarginLeft'] } },
    { name: 'itemContentGap', type: 'dimension', variations: ['size'], params: { web: ['itemContentGap'] } },
    { name: 'itemContentPadding', type: 'dimension', variations: ['size'], params: { web: ['itemContentPadding'] } },
    { name: 'actionContentMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['actionContentMarginLeft'] } },
    { name: 'disabledOpacity', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'itemBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['itemBorderRadius'] } },
    { name: 'itemPilledBorderRadius', type: 'dimension', variations: ['pilled'], params: { web: ['itemPilledBorderRadius'] } },
    { name: 'itemPadding', type: 'dimension', variations: ['size'], params: { web: ['itemPadding'] } },
    { name: 'itemPaddingPilled', type: 'dimension', variations: ['size'], params: { web: ['itemPaddingPilled'] } },
    { name: 'itemPaddingClear', type: 'float', variations: ['view'], params: { web: ['itemPaddingClear'] } },
    { name: 'itemContentPaddingClear', type: 'float', variations: ['view'], params: { web: ['itemContentPaddingClear'] } },
    { name: 'itemSelectedDividerWidth', type: 'dimension', variations: ['view'], params: { web: ['itemSelectedDividerWidth'] } },
    { name: 'itemPaddingOrientationVertical', type: 'dimension', variations: ['size'], params: { web: ['itemPaddingOrientationVertical'] } },
];
