import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        clear: [
            { prop: 'itemColor', token: 'text.default.secondary' },
            { prop: 'itemValueColor', token: 'text.default.tertiary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemValueColorActive', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColor', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColor', value: 'transparent' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColorHover', value: 'transparent' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedDividerColor', token: 'text.default.primary' },
            { prop: 'itemSelectedDividerColorHover', token: 'text.default.primary' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '0' },
        ],
        secondary: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemValueColor', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemValueColorActive', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColor', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.solid-card' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.solid-card' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedDividerColor', token: 'text.default.primary' },
            { prop: 'itemSelectedDividerColorHover', token: 'text.default.primary' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '0' },
            { prop: 'itemMarginLeftFilled', value: '2' },
        ],
        divider: [
            { prop: 'itemColor', token: 'text.default.secondary' },
            { prop: 'itemValueColor', token: 'text.default.tertiary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemValueColorActive', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColor', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColor', value: 'transparent' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColorHover', value: 'transparent' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedDividerColor', token: 'text.default.primary' },
            { prop: 'itemSelectedDividerColorHover', token: 'text.default.primary' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '2' },
        ],
        default: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemValueColor', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemValueColorActive', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.inverse.primary' },
            { prop: 'itemSelectedValueColor', token: 'text.inverse.secondary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'itemSelectedColorHover', token: 'text.inverse.primary' },
            { prop: 'itemSelectedValueColorHover', token: 'text.inverse.secondary' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.solid-default' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedDividerColor', token: 'text.default.primary' },
            { prop: 'itemSelectedDividerColorHover', token: 'text.default.primary' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '0' },
            { prop: 'itemMarginLeftFilled', value: '2' },
        ],
    },
    size: {
        xs: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '32' },
            { prop: 'itemMarginLeft', value: '24' },
            { prop: 'itemContentGap', value: '4' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.xs.bold' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '6', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
        ],
        s: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '40' },
            { prop: 'itemMarginLeft', value: '24' },
            { prop: 'itemContentGap', value: '4' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '2' },
            { prop: 'textStyle', value: 'body.s.bold' },
            { prop: 'itemBorderRadius', value: '8' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '8', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
        ],
        m: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '48' },
            { prop: 'itemMarginLeft', value: '24' },
            { prop: 'itemContentGap', value: '6' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '4' },
            { prop: 'textStyle', value: 'body.m.bold' },
            { prop: 'itemBorderRadius', value: '10' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '8', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
        ],
        l: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '56' },
            { prop: 'itemMarginLeft', value: '24' },
            { prop: 'itemContentGap', value: '8' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '2' },
            { prop: 'textStyle', value: 'body.l.bold' },
            { prop: 'itemBorderRadius', value: '12' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '12', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
        ],
        h6: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '48' },
            { prop: 'itemMarginLeft', value: '24' },
            { prop: 'itemContentGap', value: '10' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'textStyle', value: 'header.h6.normal' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
        ],
        h5: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '48' },
            { prop: 'itemMarginLeft', value: '24' },
            { prop: 'itemContentGap', value: '10' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'textStyle', value: 'header.h5.normal' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
        ],
        h4: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '52' },
            { prop: 'itemMarginLeft', value: '28' },
            { prop: 'itemContentGap', value: '10' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'textStyle', value: 'header.h4.normal' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
        ],
        h3: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '62' },
            { prop: 'itemMarginLeft', value: '32' },
            { prop: 'itemContentGap', value: '12' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'textStyle', value: 'header.h3.normal' },
            { prop: 'itemBorderRadius', value: '8' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
        ],
        h2: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '72' },
            { prop: 'itemMarginLeft', value: '36' },
            { prop: 'itemContentGap', value: '14' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'textStyle', value: 'header.h2.normal' },
            { prop: 'itemBorderRadius', value: '10' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
        ],
        h1: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '92' },
            { prop: 'itemMarginLeft', value: '52' },
            { prop: 'itemContentGap', value: '16' },
            { prop: 'actionContentMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'header.h1.normal' },
            { prop: 'itemBorderRadius', value: '12' },
            { prop: 'itemPadding', value: '2', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
        ],
    },
    pilled: {
        true: [
            { prop: 'itemPilledBorderRadius', value: '24' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
];
