import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        divider: [
            { prop: 'itemColor', token: 'text.default.secondary' },
            { prop: 'itemValueColor', token: 'text.default.tertiary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemValueColorActive', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColor', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColor', value: 'transparent' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedValueColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedBackgroundColorHover', value: 'transparent' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedDividerColor', token: 'text.default.primary' },
            { prop: 'itemSelectedDividerColorHover', token: 'text.default.primary' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemPaddingClear', value: '0' },
            { prop: 'itemContentPaddingClear', value: '0' },
            { prop: 'itemSelectedDividerWidth', value: '2' },
            { prop: 'itemSelectedDividerHeight', value: '2' },
        ],
    },
    size: {
        xs: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '32' },
            { prop: 'itemMarginLeft', value: '10' },
            { prop: 'itemContentGap', value: '4' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.xs.bold' },
            { prop: 'itemBorderRadius', value: '6' },
            { prop: 'itemPadding', value: '8', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '6', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
            { prop: 'itemPaddingOrientationVertical', value: '10', adjust: [{ platform: 'web', param: 'itemPaddingOrientationVertical', template: '1rem $1' }] },
        ],
        s: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '40' },
            { prop: 'itemMarginLeft', value: '12' },
            { prop: 'itemContentGap', value: '4' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '4' },
            { prop: 'textStyle', value: 'body.s.bold' },
            { prop: 'itemBorderRadius', value: '8' },
            { prop: 'itemPadding', value: '10', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '8', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
            { prop: 'itemPaddingOrientationVertical', value: '16', adjust: [{ platform: 'web', param: 'itemPaddingOrientationVertical', template: '1rem $1' }] },
        ],
        m: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '48' },
            { prop: 'itemMarginLeft', value: '18' },
            { prop: 'itemContentGap', value: '6' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '2' },
            { prop: 'textStyle', value: 'body.m.bold' },
            { prop: 'itemBorderRadius', value: '10' },
            { prop: 'itemPadding', value: '10', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '8', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
            { prop: 'itemPaddingOrientationVertical', value: '20', adjust: [{ platform: 'web', param: 'itemPaddingOrientationVertical', template: '1rem $1' }] },
        ],
        l: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemHeight', value: '56' },
            { prop: 'itemMarginLeft', value: '20' },
            { prop: 'itemContentGap', value: '8' },
            { prop: 'itemContentPadding', value: '2' },
            { prop: 'actionContentMarginLeft', value: '2' },
            { prop: 'textStyle', value: 'body.l.bold' },
            { prop: 'itemBorderRadius', value: '12' },
            { prop: 'itemPadding', value: '14', adjust: [{ platform: 'web', param: 'itemPadding', template: '0 $1' }] },
            { prop: 'itemPaddingPilled', value: '12', adjust: [{ platform: 'web', param: 'itemPaddingPilled', template: '0 $1' }] },
            { prop: 'itemPaddingOrientationVertical', value: '24', adjust: [{ platform: 'web', param: 'itemPaddingOrientationVertical', template: '1rem $1' }] },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
];
