import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        clear: [
            { prop: 'itemColor', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColor', value: 'transparent' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColorHover', value: 'transparent' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '0' },
        ],
        secondary: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.solid-card' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.solid-card' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '0' },
            { prop: 'itemMarginLeftFilled', value: '2' },
        ],
        divider: [
            { prop: 'itemColor', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColor', value: 'transparent' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColorHover', value: 'transparent' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedDividerColor', token: 'text.default.primary' },
            { prop: 'itemSelectedDividerColorHover', token: 'text.default.primary' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '2' },
        ],
        default: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.secondary-hover' },
            { prop: 'itemColorActive', token: 'text.default.secondary-active' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedColor', token: 'text.inverse.primary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'itemSelectedColorHover', token: 'text.inverse.primary' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.solid-default' },
            { prop: 'itemBackgroundTransition', value: 'background-color 0.3s ease-in-out' },
            { prop: 'outlineFocusColor', token: 'surface.default.accent' },
            { prop: 'itemCursor', value: 'pointer' },
            { prop: 'itemSelectedDividerHeight', value: '0' },
            { prop: 'itemMarginLeftFilled', value: '2' },
        ],
    },
    size: {
        xs: [
            { prop: 'itemPadding', value: '0.5rem 0.625rem' },
            { prop: 'itemContentGap', value: '4' },
            { prop: 'actionContentMarginLeft', value: '0' },
            { prop: 'itemBorderRadius', value: '6' },
        ],
        s: [
            { prop: 'itemPadding', value: '0.5rem 0.625rem' },
            { prop: 'itemContentGap', value: '4' },
            { prop: 'actionContentMarginLeft', value: '2' },
            { prop: 'itemBorderRadius', value: '8' },
        ],
        m: [
            { prop: 'itemPadding', value: '0.75rem 0.875rem' },
            { prop: 'itemContentGap', value: '6' },
            { prop: 'actionContentMarginLeft', value: '4' },
            { prop: 'itemBorderRadius', value: '10' },
        ],
        l: [
            { prop: 'itemPadding', value: '1rem 1.125rem' },
            { prop: 'itemContentGap', value: '8' },
            { prop: 'actionContentMarginLeft', value: '2' },
            { prop: 'itemBorderRadius', value: '12' },
        ],
        h6: [
            { prop: 'itemPadding', value: '0rem' },
            { prop: 'itemContentGap', value: '10' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'itemBorderRadius', value: '6' },
        ],
        h5: [
            { prop: 'itemPadding', value: '0rem' },
            { prop: 'itemContentGap', value: '10' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'itemBorderRadius', value: '6' },
        ],
        h4: [
            { prop: 'itemPadding', value: '0rem' },
            { prop: 'itemContentGap', value: '10' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'itemBorderRadius', value: '6' },
        ],
        h3: [
            { prop: 'itemPadding', value: '0rem' },
            { prop: 'itemContentGap', value: '12' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'itemBorderRadius', value: '8' },
        ],
        h2: [
            { prop: 'itemPadding', value: '0rem' },
            { prop: 'itemContentGap', value: '14' },
            { prop: 'actionContentMarginLeft', value: '-2' },
            { prop: 'itemBorderRadius', value: '10' },
        ],
        h1: [
            { prop: 'itemPadding', value: '0rem' },
            { prop: 'itemContentGap', value: '16' },
            { prop: 'actionContentMarginLeft', value: '0' },
            { prop: 'itemBorderRadius', value: '12' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
];
