import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'background', type: 'color', variations: ['view'], params: { web: ['background'] } },
    { name: 'backgroundError', type: 'color', variations: ['view'], params: { web: ['backgroundError'] } },
    { name: 'backgroundSuccess', type: 'color', variations: ['view'], params: { web: ['backgroundSuccess'] } },
    { name: 'dividerColor', type: 'color', variations: ['view'], params: { web: ['dividerColor'] } },
    { name: 'labelColor', type: 'color', variations: ['view'], params: { web: ['labelColor'] } },
    { name: 'leftHelperColor', type: 'color', variations: ['view'], params: { web: ['leftHelperColor'] } },
    { name: 'leftHelperColorError', type: 'color', variations: ['view'], params: { web: ['leftHelperColorError'] } },
    { name: 'leftHelperColorSuccess', type: 'color', variations: ['view'], params: { web: ['leftHelperColorSuccess'] } },
    { name: 'titleCaptionColor', type: 'color', variations: ['view'], params: { web: ['titleCaptionColor'] } },
    { name: 'hintIconColor', type: 'color', variations: ['view'], params: { web: ['hintIconColor'] } },
    { name: 'contentSlotColor', type: 'color', variations: ['view'], params: { web: ['contentSlotColor'] } },
    { name: 'contentSlotColorHover', type: 'color', variations: ['view'], params: { web: ['contentSlotColorHover'] } },
    { name: 'contentSlotColorActive', type: 'color', variations: ['view'], params: { web: ['contentSlotColorActive'] } },
    { name: 'embedIconButtonFocusColor', type: 'color', variations: ['view'], params: { web: ['embedIconButtonFocusColor'] } },
    { name: 'contentSlotRightColor', type: 'color', variations: ['view'], params: { web: ['contentSlotRightColor'] } },
    { name: 'contentSlotRightColorHover', type: 'color', variations: ['view'], params: { web: ['contentSlotRightColorHover'] } },
    { name: 'contentSlotRightColorActive', type: 'color', variations: ['view'], params: { web: ['contentSlotRightColorActive'] } },
    { name: 'textFieldContentSlotColor', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotColor'] } },
    { name: 'textFieldContentSlotColorHover', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotColorHover'] } },
    { name: 'textFieldContentSlotColorActive', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotColorActive'] } },
    { name: 'textFieldContentSlotRightColor', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotRightColor'] } },
    { name: 'textFieldContentSlotRightColorHover', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotRightColorHover'] } },
    { name: 'textFieldContentSlotRightColorActive', type: 'color', variations: ['view'], params: { web: ['textFieldContentSlotRightColorActive'] } },
    { name: 'textFieldColor', type: 'color', variations: ['view'], params: { web: ['textFieldColor'] } },
    { name: 'textFieldPlaceholderColor', type: 'color', variations: ['view'], params: { web: ['textFieldPlaceholderColor'] } },
    { name: 'textFieldCaretColor', type: 'color', variations: ['view'], params: { web: ['textFieldCaretColor'] } },
    { name: 'textFieldBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundColorHover'] } },
    { name: 'textFieldBackgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundColorFocus'] } },
    { name: 'textFieldBackgroundErrorColor', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundErrorColor'] } },
    { name: 'textFieldBackgroundErrorColorHover', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundErrorColorHover'] } },
    { name: 'textFieldBackgroundErrorColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundErrorColorFocus'] } },
    { name: 'textFieldBackgroundSuccessColor', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundSuccessColor'] } },
    { name: 'textFieldBackgroundSuccessColorHover', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundSuccessColorHover'] } },
    { name: 'textFieldBackgroundSuccessColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundSuccessColorFocus'] } },
    { name: 'textFieldTextBeforeColor', type: 'color', variations: ['view'], params: { web: ['textFieldTextBeforeColor'] } },
    { name: 'textFieldTextAfterColor', type: 'color', variations: ['view'], params: { web: ['textFieldTextAfterColor'] } },
    { name: 'indicatorColor', type: 'color', variations: ['view'], params: { web: ['indicatorColor'] } },
    { name: 'focusColor', type: 'color', variations: ['view'], params: { web: ['focusColor'] } },
    { name: 'textFieldPlaceholderColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldPlaceholderColorFocus'] } },
    { name: 'dividerStyle', type: 'typography', variations: ['size'], params: { web: ['dividerFontFamily', 'dividerFontStyle', 'dividerFontSize', 'dividerFontWeight', 'dividerLetterSpacing', 'dividerLineHeight'] } },
    { name: 'textFieldStyle', type: 'typography', variations: ['size'], params: { web: ['textFieldFontFamily', 'textFieldFontStyle', 'textFieldFontSize', 'textFieldFontWeight', 'textFieldLetterSpacing', 'textFieldLineHeight'] } },
    { name: 'labelStyle', type: 'typography', variations: ['size'], params: { web: ['labelFontFamily', 'labelFontStyle', 'labelFontSize', 'labelFontWeight', 'labelLetterSpacing', 'labelLineHeight'] } },
    { name: 'titleCaptionStyle', type: 'typography', variations: ['size'], params: { web: ['titleCaptionFontFamily', 'titleCaptionFontSize', 'titleCaptionFontStyle', 'titleCaptionFontWeight', 'titleCaptionLetterSpacing', 'titleCaptionLineHeight'] } },
    { name: 'leftHelperStyle', type: 'typography', variations: ['size'], params: { web: ['leftHelperFontFamily', 'leftHelperFontSize', 'leftHelperFontStyle', 'leftHelperFontWeight', 'leftHelperLetterSpacing', 'leftHelperLineHeight'] } },
    { name: 'tooltipBackgroundColor', type: 'color', variations: ['hintView'], params: { web: ['tooltipBackgroundColor'] } },
    { name: 'tooltipBoxShadow', type: 'shadow', variations: ['hintView'], params: { web: ['tooltipBoxShadow'] } },
    { name: 'tooltipColor', type: 'color', variations: ['hintView'], params: { web: ['tooltipColor'] } },
    { name: 'tooltipArrowBackground', type: 'color', variations: ['hintView'], params: { web: ['tooltipArrowBackground'] } },
    { name: 'tooltipTextStyle', type: 'typography', variations: ['hintSize'], params: { web: ['tooltipTextFontFamily', 'tooltipTextFontSize', 'tooltipTextFontStyle', 'tooltipTextFontWeight', 'tooltipTextFontLetterSpacing', 'tooltipTextFontLineHeight'] } },
    { name: 'tooltipArrowMaskImage', type: 'value', variations: ['hintSize'], params: { web: ['tooltipArrowMaskImage'] } },
    { name: 'backgroundReadOnly', type: 'color', params: { web: ['backgroundReadOnly'] } },
    { name: 'dividerColorReadOnly', type: 'color', params: { web: ['dividerColorReadOnly'] } },
    { name: 'textFieldColorReadOnly', type: 'color', params: { web: ['textFieldColorReadOnly'] } },
    { name: 'textFieldBackgroundColorReadOnly', type: 'color', params: { web: ['textFieldBackgroundColorReadOnly'] } },
    { name: 'textFieldPlaceholderColorReadOnly', type: 'color', params: { web: ['textFieldPlaceholderColorReadOnly'] } },
    { name: 'hintMargin', type: 'value', variations: ['size'], params: { web: ['hintMargin'] } },
    { name: 'textFieldPadding', type: 'value', variations: ['size'], params: { web: ['textFieldPadding'] } },
    { name: 'rightContentMargin', type: 'float', variations: ['size'], params: { web: ['rightContentMargin'] } },
    { name: 'textFieldHeight', type: 'dimension', variations: ['size'], params: { web: ['textFieldHeight'] } },
    { name: 'embedIconButtonHeight', type: 'dimension', variations: ['size'], params: { web: ['embedIconButtonHeight'] } },
    { name: 'embedIconButtonWidth', type: 'dimension', variations: ['size'], params: { web: ['embedIconButtonWidth'] } },
    { name: 'embedIconButtonPadding', type: 'dimension', variations: ['size'], params: { web: ['embedIconButtonPadding'] } },
    { name: 'indicatorWrapperGap', type: 'dimension', variations: ['size'], params: { web: ['indicatorWrapperGap'] } },
    { name: 'labelWrapperOffset', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperOffset'] } },
    { name: 'labelWrapperTitleCaptionOffset', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperTitleCaptionOffset'] } },
    { name: 'contentGap', type: 'dimension', variations: ['size'], params: { web: ['contentGap'] } },
    { name: 'hintTargetSize', type: 'dimension', variations: ['size'], params: { web: ['hintTargetSize'] } },
    { name: 'titleCaptionOffset', type: 'dimension', variations: ['size'], params: { web: ['titleCaptionOffset'] } },
    { name: 'helpersGap', type: 'dimension', variations: ['size'], params: { web: ['helpersGap'] } },
    { name: 'indicatorSizeInner', type: 'dimension', variations: ['size'], params: { web: ['indicatorSizeInner'] } },
    { name: 'indicatorSizeOuter', type: 'dimension', variations: ['size'], params: { web: ['indicatorSizeOuter'] } },
    { name: 'indicatorMarginTop', type: 'dimension', variations: ['size'], params: { web: ['indicatorMarginTop'] } },
    { name: 'indicatorOuterLeft', type: 'dimension', variations: ['size'], params: { web: ['indicatorOuterLeft'] } },
    { name: 'tooltipPaddingTop', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingTop'] } },
    { name: 'tooltipPaddingRight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingRight'] } },
    { name: 'tooltipPaddingBottom', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingBottom'] } },
    { name: 'tooltipPaddingLeft', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingLeft'] } },
    { name: 'tooltipMinHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipMinHeight'] } },
    { name: 'tooltipContentLeftMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipContentLeftMargin'] } },
    { name: 'tooltipArrowMaskWidth', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowMaskWidth'] } },
    { name: 'tooltipArrowMaskHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowMaskHeight'] } },
    { name: 'tooltipArrowHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowHeight'] } },
    { name: 'tooltipArrowEdgeMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowEdgeMargin'] } },
    { name: 'disabledOpacity', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'readOnlyOpacity', type: 'float', params: { web: ['readOnlyOpacity'] } },
    { name: 'dividerOpacityReadOnly', type: 'float', params: { web: ['dividerOpacityReadOnly'] } },
    { name: 'rightContentOpacityReadOnly', type: 'float', params: { web: ['rightContentOpacityReadOnly'] } },
    { name: 'borderRadius', type: 'dimension', variations: ['size'], params: { web: ['borderRadius'] } },
    { name: 'textFieldBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['textFieldBorderRadius'] } },
    { name: 'embedIconButtonRadius', type: 'dimension', variations: ['size'], params: { web: ['embedIconButtonRadius'] } },
    { name: 'tooltipBorderRadius', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipBorderRadius'] } },
    { name: 'dividerPadding', type: 'dimension', variations: ['size'], params: { web: ['dividerPadding'] } },
    { name: 'leftContentMargin', type: 'dimension', variations: ['size'], params: { web: ['leftContentMargin'] } },
    { name: 'textFieldLeftContentMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldLeftContentMargin'] } },
    { name: 'textFieldRightContentMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldRightContentMargin'] } },
    { name: 'textFieldTextBeforeMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldTextBeforeMargin'] } },
    { name: 'textFieldTextAfterMargin', type: 'dimension', variations: ['size'], params: { web: ['textFieldTextAfterMargin'] } },
    { name: 'hintWithoutLabelPlacementOffset', type: 'dimension', variations: ['size'], params: { web: ['hintWithoutLabelPlacementOffset'] } },
    { name: 'hintPlacementInnerMargin', type: 'dimension', variations: ['size'], params: { web: ['hintPlacementInnerMargin'] } },
    { name: 'helpersPadding', type: 'dimension', variations: ['size'], params: { web: ['helpersPadding'] } },
    { name: 'indicatorWithoutLabelInner', type: 'dimension', variations: ['size'], params: { web: ['indicatorWithoutLabelInner'] } },
    { name: 'indicatorWithoutLabelInnerLeft', type: 'dimension', variations: ['size'], params: { web: ['indicatorWithoutLabelInnerLeft'] } },
];
