import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'background', token: 'surface.default.transparent-primary' },
            { prop: 'backgroundError', token: 'surface.default.transparent-negative' },
            { prop: 'backgroundSuccess', token: 'surface.default.transparent-positive' },
            { prop: 'dividerColor', token: 'text.default.primary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'leftHelperColor', token: 'text.default.secondary' },
            { prop: 'leftHelperColorError', token: 'text.default.negative' },
            { prop: 'leftHelperColorSuccess', token: 'text.default.positive' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColor', token: 'text.default.primary' },
            { prop: 'contentSlotColorHover', token: 'text.default.primary-hover' },
            { prop: 'contentSlotColorActive', token: 'text.default.primary-active' },
            { prop: 'embedIconButtonFocusColor', token: 'surface.default.accent' },
            { prop: 'contentSlotRightColor', token: 'text.default.primary' },
            { prop: 'contentSlotRightColorHover', token: 'text.default.primary-hover' },
            { prop: 'contentSlotRightColorActive', token: 'text.default.primary-active' },
            { prop: 'textFieldContentSlotColor', token: 'text.default.secondary' },
            { prop: 'textFieldContentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldContentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'textFieldContentSlotRightColor', token: 'text.default.secondary' },
            { prop: 'textFieldContentSlotRightColorHover', token: 'text.default.secondary-hover' },
            { prop: 'textFieldContentSlotRightColorActive', token: 'text.default.secondary-active' },
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'textFieldCaretColor', token: 'text.default.accent' },
            { prop: 'textFieldBackgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldBackgroundErrorColor', token: 'surface.default.transparent-negative' },
            { prop: 'textFieldBackgroundErrorColorHover', token: 'surface.default.transparent-negative-hover' },
            { prop: 'textFieldBackgroundErrorColorFocus', token: 'surface.default.transparent-negative-active' },
            { prop: 'textFieldBackgroundSuccessColor', token: 'surface.default.transparent-positive' },
            { prop: 'textFieldBackgroundSuccessColorHover', token: 'surface.default.transparent-positive-hover' },
            { prop: 'textFieldBackgroundSuccessColorFocus', token: 'surface.default.transparent-positive-active' },
            { prop: 'textFieldTextBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textFieldTextAfterColor', token: 'text.default.tertiary' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'focusColor', token: 'text.default.accent' },
            { prop: 'textFieldPlaceholderColorFocus', token: 'text.default.tertiary' },
        ],
    },
    size: {
        xl: [
            { prop: 'textFieldPadding', value: '1.3125rem 1.125rem' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'rightContentMargin', value: '0' },
            { prop: 'textFieldHeight', value: '64' },
            { prop: 'embedIconButtonHeight', value: '64' },
            { prop: 'embedIconButtonWidth', value: '64' },
            { prop: 'embedIconButtonPadding', value: '20' },
            { prop: 'indicatorWrapperGap', value: '4' },
            { prop: 'labelWrapperOffset', value: '12' },
            { prop: 'labelWrapperTitleCaptionOffset', value: '4' },
            { prop: 'contentGap', value: '16' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionOffset', value: '6' },
            { prop: 'helpersGap', value: '4' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorMarginTop', value: '4' },
            { prop: 'indicatorOuterLeft', value: '-12' },
            { prop: 'dividerStyle', value: 'body.l.normal' },
            { prop: 'textFieldStyle', value: 'body.l.normal' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '16' },
            { prop: 'textFieldBorderRadius', value: '16' },
            { prop: 'embedIconButtonRadius', value: '16' },
            { prop: 'dividerPadding', value: '6', adjust: [{ platform: 'web', param: 'dividerPadding', template: '0 $1' }] },
            { prop: 'leftContentMargin', value: '18', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldLeftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.0625rem $1 -0.0625rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'hintWithoutLabelPlacementOffset', value: '27.008', adjust: [{ platform: 'web', param: 'hintWithoutLabelPlacementOffset', template: '$1 -2.938rem auto auto' }] },
            { prop: 'hintPlacementInnerMargin', value: '13.008', adjust: [{ platform: 'web', param: 'hintPlacementInnerMargin', template: '0 $1 0 -0.438rem' }] },
            { prop: 'helpersPadding', value: '4', adjust: [{ platform: 'web', param: 'helpersPadding', template: '$1 0 0 0' }] },
            { prop: 'indicatorWithoutLabelInner', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInner', template: 'auto 0 $1 auto' }] },
            { prop: 'indicatorWithoutLabelInnerLeft', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInnerLeft', template: 'auto auto $1 0' }] },
        ],
        l: [
            { prop: 'textFieldPadding', value: '1.0625rem 1.125rem 1.0625rem 1.125rem' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'rightContentMargin', value: '0' },
            { prop: 'textFieldHeight', value: '56' },
            { prop: 'embedIconButtonHeight', value: '56' },
            { prop: 'embedIconButtonWidth', value: '56' },
            { prop: 'embedIconButtonPadding', value: '16' },
            { prop: 'indicatorWrapperGap', value: '4' },
            { prop: 'labelWrapperOffset', value: '12' },
            { prop: 'labelWrapperTitleCaptionOffset', value: '4' },
            { prop: 'contentGap', value: '16' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionOffset', value: '6' },
            { prop: 'helpersGap', value: '4' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorMarginTop', value: '4' },
            { prop: 'indicatorOuterLeft', value: '-12' },
            { prop: 'dividerStyle', value: 'body.l.normal' },
            { prop: 'textFieldStyle', value: 'body.l.normal' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '14' },
            { prop: 'textFieldBorderRadius', value: '14' },
            { prop: 'embedIconButtonRadius', value: '14' },
            { prop: 'dividerPadding', value: '6', adjust: [{ platform: 'web', param: 'dividerPadding', template: '0 $1' }] },
            { prop: 'leftContentMargin', value: '16', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldLeftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.0625rem $1 -0.0625rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'hintWithoutLabelPlacementOffset', value: '23.008', adjust: [{ platform: 'web', param: 'hintWithoutLabelPlacementOffset', template: '$1 -2.938rem auto auto' }] },
            { prop: 'hintPlacementInnerMargin', value: '9.008', adjust: [{ platform: 'web', param: 'hintPlacementInnerMargin', template: '0 $1 0 -0.438rem' }] },
            { prop: 'helpersPadding', value: '4', adjust: [{ platform: 'web', param: 'helpersPadding', template: '$1 0 0 0' }] },
            { prop: 'indicatorWithoutLabelInner', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInner', template: 'auto 0 $1 auto' }] },
            { prop: 'indicatorWithoutLabelInnerLeft', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInnerLeft', template: 'auto auto $1 0' }] },
        ],
        m: [
            { prop: 'hintMargin', value: '-0.688rem' },
            { prop: 'textFieldPadding', value: '0.875rem 1rem 0.875rem 1rem' },
            { prop: 'rightContentMargin', value: '0' },
            { prop: 'textFieldHeight', value: '48' },
            { prop: 'embedIconButtonHeight', value: '48' },
            { prop: 'embedIconButtonWidth', value: '48' },
            { prop: 'embedIconButtonPadding', value: '12' },
            { prop: 'indicatorWrapperGap', value: '4' },
            { prop: 'labelWrapperOffset', value: '10' },
            { prop: 'labelWrapperTitleCaptionOffset', value: '4' },
            { prop: 'contentGap', value: '14' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionOffset', value: '5.008' },
            { prop: 'helpersGap', value: '4' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorMarginTop', value: '4' },
            { prop: 'indicatorOuterLeft', value: '-12' },
            { prop: 'dividerStyle', value: 'body.m.normal' },
            { prop: 'textFieldStyle', value: 'body.m.normal' },
            { prop: 'labelStyle', value: 'body.m.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '12' },
            { prop: 'textFieldBorderRadius', value: '12' },
            { prop: 'embedIconButtonRadius', value: '12' },
            { prop: 'dividerPadding', value: '6', adjust: [{ platform: 'web', param: 'dividerPadding', template: '0 $1' }] },
            { prop: 'leftContentMargin', value: '14', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldLeftContentMargin', value: '6', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.0625rem $1 -0.0625rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-2', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'hintWithoutLabelPlacementOffset', value: '19', adjust: [{ platform: 'web', param: 'hintWithoutLabelPlacementOffset', template: '$1 -2.938rem auto auto' }] },
            { prop: 'hintPlacementInnerMargin', value: '5.008', adjust: [{ platform: 'web', param: 'hintPlacementInnerMargin', template: '0 $1 0 -0.438rem' }] },
            { prop: 'helpersPadding', value: '4', adjust: [{ platform: 'web', param: 'helpersPadding', template: '$1 0 0 0' }] },
            { prop: 'indicatorWithoutLabelInner', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInner', template: 'auto 0 $1 auto' }] },
            { prop: 'indicatorWithoutLabelInnerLeft', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInnerLeft', template: 'auto auto $1 0' }] },
        ],
        s: [
            { prop: 'hintMargin', value: '-0.688rem' },
            { prop: 'textFieldPadding', value: '0.6875rem 0.875rem 0.6875rem 0.875rem' },
            { prop: 'rightContentMargin', value: '0' },
            { prop: 'textFieldHeight', value: '40' },
            { prop: 'embedIconButtonHeight', value: '40' },
            { prop: 'embedIconButtonWidth', value: '40' },
            { prop: 'embedIconButtonPadding', value: '8' },
            { prop: 'indicatorWrapperGap', value: '4' },
            { prop: 'labelWrapperOffset', value: '8' },
            { prop: 'labelWrapperTitleCaptionOffset', value: '4' },
            { prop: 'contentGap', value: '12' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionOffset', value: '3.008' },
            { prop: 'helpersGap', value: '4' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorMarginTop', value: '4' },
            { prop: 'indicatorOuterLeft', value: '-12' },
            { prop: 'dividerStyle', value: 'body.s.normal' },
            { prop: 'textFieldStyle', value: 'body.s.normal' },
            { prop: 'labelStyle', value: 'body.s.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '10' },
            { prop: 'textFieldBorderRadius', value: '10' },
            { prop: 'embedIconButtonRadius', value: '10' },
            { prop: 'dividerPadding', value: '6', adjust: [{ platform: 'web', param: 'dividerPadding', template: '0 $1' }] },
            { prop: 'leftContentMargin', value: '12', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldLeftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.0625rem $1 -0.0625rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-3', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'hintWithoutLabelPlacementOffset', value: '15.008', adjust: [{ platform: 'web', param: 'hintWithoutLabelPlacementOffset', template: '$1 -2.938rem auto auto' }] },
            { prop: 'hintPlacementInnerMargin', value: '1.008', adjust: [{ platform: 'web', param: 'hintPlacementInnerMargin', template: '0 $1 0 -0.438rem' }] },
            { prop: 'helpersPadding', value: '4', adjust: [{ platform: 'web', param: 'helpersPadding', template: '$1 0 0 0' }] },
            { prop: 'indicatorWithoutLabelInner', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInner', template: 'auto 0 $1 auto' }] },
            { prop: 'indicatorWithoutLabelInnerLeft', value: '-8', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInnerLeft', template: 'auto auto $1 0' }] },
        ],
        xs: [
            { prop: 'hintMargin', value: '-0.688rem' },
            { prop: 'textFieldPadding', value: '0.5625rem 0.625rem 0.5625rem 0.625rem' },
            { prop: 'rightContentMargin', value: '0' },
            { prop: 'textFieldHeight', value: '32' },
            { prop: 'embedIconButtonHeight', value: '32' },
            { prop: 'embedIconButtonWidth', value: '32' },
            { prop: 'embedIconButtonPadding', value: '8' },
            { prop: 'indicatorWrapperGap', value: '4' },
            { prop: 'labelWrapperOffset', value: '6' },
            { prop: 'labelWrapperTitleCaptionOffset', value: '4' },
            { prop: 'contentGap', value: '8' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionOffset', value: '0' },
            { prop: 'helpersGap', value: '4' },
            { prop: 'indicatorSizeInner', value: '6' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'indicatorMarginTop', value: '2' },
            { prop: 'indicatorOuterLeft', value: '-12' },
            { prop: 'dividerStyle', value: 'body.xs.normal' },
            { prop: 'textFieldStyle', value: 'body.xs.normal' },
            { prop: 'labelStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '8' },
            { prop: 'textFieldBorderRadius', value: '8' },
            { prop: 'embedIconButtonRadius', value: '8' },
            { prop: 'dividerPadding', value: '6', adjust: [{ platform: 'web', param: 'dividerPadding', template: '0 $1' }] },
            { prop: 'leftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '0 0 0 $1' }] },
            { prop: 'textFieldLeftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldLeftContentMargin', template: '-0.0625rem $1 -0.0625rem -0.125rem' }] },
            { prop: 'textFieldRightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'textFieldRightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'textFieldTextBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textFieldTextAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textFieldTextAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'hintWithoutLabelPlacementOffset', value: '11.008', adjust: [{ platform: 'web', param: 'hintWithoutLabelPlacementOffset', template: '$1 -2.938rem auto auto' }] },
            { prop: 'hintPlacementInnerMargin', value: '-3.008', adjust: [{ platform: 'web', param: 'hintPlacementInnerMargin', template: '0 $1 0 -0.438rem' }] },
            { prop: 'helpersPadding', value: '4', adjust: [{ platform: 'web', param: 'helpersPadding', template: '$1 0 0 0' }] },
            { prop: 'indicatorWithoutLabelInner', value: '-6', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInner', template: 'auto 0 $1 auto' }] },
            { prop: 'indicatorWithoutLabelInnerLeft', value: '-6', adjust: [{ platform: 'web', param: 'indicatorWithoutLabelInnerLeft', template: 'auto auto $1 0' }] },
        ],
    },
    hintView: {
        default: [
            { prop: 'tooltipBackgroundColor', token: 'surface.default.solid-card-brightness' },
            { prop: 'tooltipBoxShadow', value: 'down.hard.m' },
            { prop: 'tooltipColor', token: 'text.default.primary' },
            { prop: 'tooltipArrowBackground', token: 'surface.default.solid-card-brightness' },
        ],
    },
    hintSize: {
        m: [
            { prop: 'tooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMC4xNywxMS44M2wyMCwwYy01LjUyLDAgLTEwLDMuNTkgLTEwLDhjMCwtNC40MSAtNC40OCwtOCAtMTAsLTh6IiBmaWxsPSIjMTcxNzE3IiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGlkPSJUYWlsIi8+Cjwvc3ZnPg==")' },
            { prop: 'tooltipPaddingTop', value: '11' },
            { prop: 'tooltipPaddingRight', value: '14' },
            { prop: 'tooltipPaddingBottom', value: '11' },
            { prop: 'tooltipPaddingLeft', value: '14' },
            { prop: 'tooltipMinHeight', value: '40' },
            { prop: 'tooltipContentLeftMargin', value: '6' },
            { prop: 'tooltipArrowMaskWidth', value: '20' },
            { prop: 'tooltipArrowMaskHeight', value: '20' },
            { prop: 'tooltipArrowHeight', value: '8' },
            { prop: 'tooltipArrowEdgeMargin', value: '10' },
            { prop: 'tooltipTextStyle', value: 'body.s.normal' },
            { prop: 'tooltipBorderRadius', value: '10' },
        ],
        s: [
            { prop: 'tooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMCw5Ljg1bDE2LDBjLTQuNDEsMCAtOCwyLjY5IC04LDZjMCwtMy4zMSAtMy41OSwtNiAtOCwtNnoiIGZpbGw9IiMxNzE3MTciIGZpbGwtcnVsZT0iZXZlbm9kZCIgaWQ9IlRhaWwiLz4KPC9zdmc+")' },
            { prop: 'tooltipPaddingTop', value: '8' },
            { prop: 'tooltipPaddingRight', value: '12' },
            { prop: 'tooltipPaddingBottom', value: '8' },
            { prop: 'tooltipPaddingLeft', value: '12' },
            { prop: 'tooltipMinHeight', value: '32' },
            { prop: 'tooltipContentLeftMargin', value: '4' },
            { prop: 'tooltipArrowMaskWidth', value: '16' },
            { prop: 'tooltipArrowMaskHeight', value: '16' },
            { prop: 'tooltipArrowHeight', value: '6' },
            { prop: 'tooltipArrowEdgeMargin', value: '9' },
            { prop: 'tooltipTextStyle', value: 'body.xs.normal' },
            { prop: 'tooltipBorderRadius', value: '8' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
    { prop: 'backgroundReadOnly', token: 'surface.default.transparent-primary' },
    { prop: 'dividerColorReadOnly', token: 'text.default.secondary' },
    { prop: 'textFieldColorReadOnly', token: 'text.default.primary' },
    { prop: 'textFieldBackgroundColorReadOnly', value: 'transparent' },
    { prop: 'textFieldPlaceholderColorReadOnly', token: 'text.default.secondary' },
    { prop: 'readOnlyOpacity', value: '0.1' },
    { prop: 'dividerOpacityReadOnly', value: '0.4' },
    { prop: 'rightContentOpacityReadOnly', value: '0.4' },
];
