import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    size: {
        s: [
            { prop: 'clearContentMarginLeft', value: '6' },
            { prop: 'closeIconSize', value: '16' },
            { prop: 'leftContentMarginLeft', value: '-2' },
            { prop: 'padding', value: '14' },
            { prop: 'rightContentMarginRight', value: '-2' },
            { prop: 'textStyle', value: 'body.s.normal' },
            { prop: 'clearContentMarginRight', value: '-4' },
            { prop: 'height', value: '32' },
            { prop: 'leftContentMarginRight', value: '4' },
            { prop: 'rightContentMarginLeft', value: '4' },
            { prop: 'shape', token: 'round.s' },
            { prop: 'width', value: 'auto' },
        ],
        l: [
            { prop: 'clearContentMarginRight', value: '-4' },
            { prop: 'clearContentMarginLeft', value: '10' },
            { prop: 'closeIconSize', value: '24' },
            { prop: 'leftContentMarginLeft', value: '-2' },
            { prop: 'padding', value: '16' },
            { prop: 'rightContentMarginRight', value: '-2' },
            { prop: 'textStyle', value: 'body.l.normal' },
            { prop: 'height', value: '48' },
            { prop: 'leftContentMarginRight', value: '8' },
            { prop: 'rightContentMarginLeft', value: '8' },
            { prop: 'shape', token: 'round.m' },
            { prop: 'width', value: 'auto' },
        ],
        xxs: [
            { prop: 'clearContentMarginLeft', value: '4' },
            { prop: 'closeIconSize', value: '12' },
            { prop: 'leftContentMarginLeft', value: '-2' },
            { prop: 'padding', value: '8' },
            { prop: 'rightContentMarginRight', value: '-2' },
            { prop: 'textStyle', value: 'body.xxs.normal' },
            { prop: 'clearContentMarginRight', value: '-4' },
            { prop: 'height', value: '20' },
            { prop: 'leftContentMarginRight', value: '2' },
            { prop: 'rightContentMarginLeft', value: '2' },
            { prop: 'shape', token: 'round.xs' },
            { prop: 'width', value: 'auto' },
        ],
        m: [
            { prop: 'clearContentMarginLeft', value: '8' },
            { prop: 'closeIconSize', value: '20' },
            { prop: 'leftContentMarginLeft', value: '-2' },
            { prop: 'padding', value: '14' },
            { prop: 'rightContentMarginRight', value: '-2' },
            { prop: 'textStyle', value: 'body.m.normal' },
            { prop: 'clearContentMarginRight', value: '-4' },
            { prop: 'height', value: '40' },
            { prop: 'leftContentMarginRight', value: '6' },
            { prop: 'rightContentMarginLeft', value: '6' },
            { prop: 'shape', token: 'round.s' },
            { prop: 'width', value: 'auto' },
        ],
        xs: [
            { prop: 'clearContentMarginLeft', value: '4' },
            { prop: 'closeIconSize', value: '12' },
            { prop: 'leftContentMarginLeft', value: '-2' },
            { prop: 'padding', value: '10' },
            { prop: 'rightContentMarginRight', value: '-2' },
            { prop: 'textStyle', value: 'body.xs.normal' },
            { prop: 'clearContentMarginRight', value: '-4' },
            { prop: 'height', value: '24' },
            { prop: 'leftContentMarginRight', value: '4' },
            { prop: 'rightContentMarginLeft', value: '4' },
            { prop: 'shape', token: 'round.xs' },
            { prop: 'width', value: 'auto' },
        ],
    },
    view: {
        positive: [
            { prop: 'background', token: 'surface.default.positive' },
            { prop: 'background', token: 'surface.default.positive-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.positive-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary', state: 'pressed', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'colorReadOnly', value: 'text.on-dark.primary' }] },
            { prop: 'leftContentColor', token: 'text.on-dark.primary' },
            { prop: 'background', token: 'surface.default.positive-active', state: 'pressed', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.positive-active' }] },
            { prop: 'backgroundReadOnly', token: 'surface.default.positive' },
            { prop: 'backgroundReadOnly', token: 'surface.default.positive', state: 'hovered', adjust: [{ platform: 'web', param: 'backgroundReadOnly', value: 'surface.default.positive' }] },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary' },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'closeIconColor', value: 'text.on-dark.secondary-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary' },
            { prop: 'color', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
        ],
        accent: [
            { prop: 'background', token: 'surface.default.accent-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.accent-hover' }] },
            { prop: 'backgroundReadOnly', token: 'surface.default.accent' },
            { prop: 'backgroundReadOnly', token: 'surface.default.accent', state: 'hovered', adjust: [{ platform: 'web', param: 'backgroundReadOnly', value: 'surface.default.accent' }] },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary' },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'closeIconColor', value: 'text.on-dark.secondary-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary' },
            { prop: 'color', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
            { prop: 'background', token: 'surface.default.accent' },
            { prop: 'background', token: 'surface.default.accent-active', state: 'pressed', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.accent-active' }] },
            { prop: 'color', token: 'text.on-dark.primary', state: 'pressed', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'colorReadOnly', value: 'text.on-dark.primary' }] },
            { prop: 'leftContentColor', token: 'text.on-dark.primary' },
        ],
        warning: [
            { prop: 'background', token: 'surface.default.warning-active', state: 'pressed', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.warning-active' }] },
            { prop: 'backgroundReadOnly', token: 'surface.default.warning' },
            { prop: 'backgroundReadOnly', token: 'surface.default.warning', state: 'hovered', adjust: [{ platform: 'web', param: 'backgroundReadOnly', value: 'surface.default.warning' }] },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary' },
            { prop: 'background', token: 'surface.default.warning' },
            { prop: 'background', token: 'surface.default.warning-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.warning-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary', state: 'pressed', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'closeIconColor', value: 'text.on-dark.secondary-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary' },
            { prop: 'color', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'colorReadOnly', value: 'text.on-dark.primary' }] },
            { prop: 'leftContentColor', token: 'text.on-dark.primary' },
        ],
        secondary: [
            { prop: 'background', token: 'surface.default.transparent-secondary-active', state: 'pressed', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.transparent-secondary-active' }] },
            { prop: 'backgroundReadOnly', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundReadOnly', token: 'surface.default.transparent-secondary', state: 'hovered', adjust: [{ platform: 'web', param: 'backgroundReadOnly', value: 'surface.default.transparent-secondary' }] },
            { prop: 'closeIconColor', token: 'text.default.secondary' },
            { prop: 'closeIconColor', token: 'text.default.secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'closeIconColor', value: 'text.default.secondary-hover' }] },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'color', token: 'text.default.primary', state: 'pressed', adjust: [{ platform: 'web', param: 'color', value: 'text.default.primary' }] },
            { prop: 'background', token: 'surface.default.transparent-secondary' },
            { prop: 'background', token: 'surface.default.transparent-secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.transparent-secondary-hover' }] },
            { prop: 'color', token: 'text.default.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'color', value: 'text.default.primary' }] },
            { prop: 'colorReadOnly', token: 'text.default.primary' },
            { prop: 'colorReadOnly', token: 'text.default.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'colorReadOnly', value: 'text.default.primary' }] },
            { prop: 'leftContentColor', token: 'text.default.primary' },
        ],
        default: [
            { prop: 'background', token: 'surface.default.solid-default' },
            { prop: 'background', token: 'surface.default.solid-default-active', state: 'pressed', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.solid-default-active' }] },
            { prop: 'color', token: 'text.inverse.primary', state: 'pressed', adjust: [{ platform: 'web', param: 'color', value: 'text.inverse.primary' }] },
            { prop: 'colorReadOnly', token: 'text.inverse.primary' },
            { prop: 'colorReadOnly', token: 'text.inverse.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'colorReadOnly', value: 'text.inverse.primary' }] },
            { prop: 'leftContentColor', token: 'text.inverse.primary' },
            { prop: 'background', token: 'surface.default.solid-default-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.solid-default-hover' }] },
            { prop: 'backgroundReadOnly', token: 'surface.default.solid-default' },
            { prop: 'backgroundReadOnly', token: 'surface.default.solid-default', state: 'hovered', adjust: [{ platform: 'web', param: 'backgroundReadOnly', value: 'surface.default.solid-default' }] },
            { prop: 'closeIconColor', token: 'text.inverse.secondary' },
            { prop: 'closeIconColor', token: 'text.inverse.secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'closeIconColor', value: 'text.inverse.secondary-hover' }] },
            { prop: 'color', token: 'text.inverse.primary' },
            { prop: 'color', token: 'text.inverse.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'color', value: 'text.inverse.primary' }] },
        ],
        negative: [
            { prop: 'background', token: 'surface.default.negative' },
            { prop: 'background', token: 'surface.default.negative-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.negative-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary', state: 'pressed', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'colorReadOnly', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'colorReadOnly', value: 'text.on-dark.primary' }] },
            { prop: 'leftContentColor', token: 'text.on-dark.primary' },
            { prop: 'background', token: 'surface.default.negative-active', state: 'pressed', adjust: [{ platform: 'web', param: 'background', value: 'surface.default.negative-active' }] },
            { prop: 'backgroundReadOnly', token: 'surface.default.negative' },
            { prop: 'backgroundReadOnly', token: 'surface.default.negative', state: 'hovered', adjust: [{ platform: 'web', param: 'backgroundReadOnly', value: 'surface.default.negative' }] },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary' },
            { prop: 'closeIconColor', token: 'text.on-dark.secondary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'closeIconColor', value: 'text.on-dark.secondary-hover' }] },
            { prop: 'color', token: 'text.on-dark.primary' },
            { prop: 'color', token: 'text.on-dark.primary', state: 'hovered', adjust: [{ platform: 'web', param: 'color', value: 'text.on-dark.primary' }] },
        ],
    },
    shape: {
        Pilled: [
            { prop: 'shape', token: 'round.circle' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'focusColor', token: 'text.default.accent' },
    { prop: 'disableAlpha', value: '0.4' },
];
