import { TokenType } from '../../../types';

export const spacingTokens: Array<TokenType> = [
    {
        type: 'spacing',
        name: 'spacing.0x',
        tags: ['spacing', '0x'],
        displayName: 'spacing0x',
        description: 'spacing 0x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.1x',
        tags: ['spacing', '1x'],
        displayName: 'spacing1x',
        description: 'spacing 1x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.2x',
        tags: ['spacing', '2x'],
        displayName: 'spacing2x',
        description: 'spacing 2x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.3x',
        tags: ['spacing', '3x'],
        displayName: 'spacing3x',
        description: 'spacing 3x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.4x',
        tags: ['spacing', '4x'],
        displayName: 'spacing4x',
        description: 'spacing 4x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.6x',
        tags: ['spacing', '6x'],
        displayName: 'spacing6x',
        description: 'spacing 6x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.8x',
        tags: ['spacing', '8x'],
        displayName: 'spacing8x',
        description: 'spacing 8x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.10x',
        tags: ['spacing', '10x'],
        displayName: 'spacing10x',
        description: 'spacing 10x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.12x',
        tags: ['spacing', '12x'],
        displayName: 'spacing12x',
        description: 'spacing 12x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.16x',
        tags: ['spacing', '16x'],
        displayName: 'spacing16x',
        description: 'spacing 16x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.20x',
        tags: ['spacing', '20x'],
        displayName: 'spacing20x',
        description: 'spacing 20x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.24x',
        tags: ['spacing', '24x'],
        displayName: 'spacing24x',
        description: 'spacing 24x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.32x',
        tags: ['spacing', '32x'],
        displayName: 'spacing32x',
        description: 'spacing 32x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.40x',
        tags: ['spacing', '40x'],
        displayName: 'spacing40x',
        description: 'spacing 40x',
        enabled: true,
    },
    {
        type: 'spacing',
        name: 'spacing.60x',
        tags: ['spacing', '60x'],
        displayName: 'spacing60x',
        description: 'spacing 60x',
        enabled: true,
    },
];
