import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'selectTargetInnerTop', type: 'dimension', variations: ['size'], params: { web: ['selectTargetInnerTop'] } },
    { name: 'paginationHelperTextColor', type: 'color', variations: ['view'], params: { web: ['paginationHelperTextColor'] } },
    { name: 'buttonFocusColor', type: 'color', variations: ['view'], params: { web: ['buttonFocusColor'] } },
    { name: 'selectBackgroundColor', type: 'color', variations: ['view'], params: { web: ['selectBackgroundColor'] } },
    { name: 'paginationCurrentButtonColor', type: 'color', variations: ['viewCurrentPage'], params: { web: ['paginationCurrentButtonColor'] } },
    { name: 'paginationCurrentButtonHoverBackgroundColor', type: 'value', variations: ['viewCurrentPage'], params: { web: ['paginationCurrentButtonHoverBackgroundColor'] } },
    { name: 'paginationCurrentButtonActiveBackgroundColor', type: 'value', variations: ['viewCurrentPage'], params: { web: ['paginationCurrentButtonActiveBackgroundColor'] } },
    { name: 'paginationStyle', type: 'typography', variations: ['size'], params: { web: ['paginationFontFamily', 'paginationFontSize', 'paginationFontStyle', 'paginationFontWeight', 'paginationLetterSpacing', 'paginationLineHeight'] } },
    { name: 'selectHeight', type: 'value', variations: ['size'], params: { web: ['selectHeight'] } },
    { name: 'selectItemBackground', type: 'color', variations: ['size'], params: { web: ['selectItemBackground'] } },
    { name: 'buttonDisabledOpacity', type: 'float', variations: ['view'], params: { web: ['buttonDisabledOpacity'] } },
    { name: 'buttonHeight', type: 'dimension', variations: ['size'], params: { web: ['buttonHeight'] } },
    { name: 'buttonWidth', type: 'dimension', variations: ['size'], params: { web: ['buttonWidth'] } },
    { name: 'buttonWidthShorter', type: 'dimension', variations: ['size'], params: { web: ['buttonWidthShorter'] } },
    { name: 'paginationInputWidth', type: 'dimension', variations: ['size'], params: { web: ['paginationInputWidth'] } },
    { name: 'paginationIconSize', type: 'dimension', variations: ['size'], params: { web: ['paginationIconSize'] } },
    { name: 'paginationIconDoubleSize', type: 'dimension', variations: ['size'], params: { web: ['paginationIconDoubleSize'] } },
    { name: 'selectPaddingTop', type: 'dimension', variations: ['size'], params: { web: ['selectPaddingTop'] } },
    { name: 'selectPaddingRight', type: 'dimension', variations: ['size'], params: { web: ['selectPaddingRight'] } },
    { name: 'selectPaddingBottom', type: 'dimension', variations: ['size'], params: { web: ['selectPaddingBottom'] } },
    { name: 'selectPaddingLeft', type: 'dimension', variations: ['size'], params: { web: ['selectPaddingLeft'] } },
    { name: 'selectItemHeight', type: 'dimension', variations: ['size'], params: { web: ['selectItemHeight'] } },
    { name: 'selectItemContentLeftWidth', type: 'dimension', variations: ['size'], params: { web: ['selectItemContentLeftWidth'] } },
    { name: 'selectTargetArrowRight', type: 'dimension', variations: ['size'], params: { web: ['selectTargetArrowRight'] } },
    { name: 'buttonColor', type: 'color', variations: ['view'], params: { web: ['buttonColor'] } },
    { name: 'buttonColorHover', type: 'color', variations: ['view'], params: { web: ['buttonColorHover'] } },
    { name: 'buttonColorActive', type: 'color', variations: ['view'], params: { web: ['buttonColorActive'] } },
    { name: 'buttonHoverColor', type: 'color', variations: ['view'], params: { web: ['buttonHoverColor'] } },
    { name: 'buttonBackgroundColor', type: 'color', variations: ['view'], params: { web: ['buttonBackgroundColor'] } },
    { name: 'inputBackgroundColor', type: 'color', variations: ['view'], params: { web: ['inputBackgroundColor'] } },
    { name: 'inputBorderColor', type: 'color', variations: ['view'], params: { web: ['inputBorderColor'] } },
    { name: 'paginationColor', type: 'color', variations: ['view'], params: { web: ['paginationColor'] } },
    { name: 'paginationCurrentButtonBackgroundColor', type: 'color', variations: ['viewCurrentPage'], params: { web: ['paginationCurrentButtonBackgroundColor'] } },
    { name: 'paginationCurrentButtonHoverColor', type: 'color', variations: ['viewCurrentPage'], params: { web: ['paginationCurrentButtonHoverColor'] } },
    { name: 'paginationCurrentButtonActiveColor', type: 'color', variations: ['viewCurrentPage'], params: { web: ['paginationCurrentButtonActiveColor'] } },
    { name: 'buttonBackgroundColorHover', type: 'color', variations: ['view'], params: { web: ['buttonBackgroundColorHover'] } },
    { name: 'buttonBackgroundColorActive', type: 'color', variations: ['view'], params: { web: ['buttonBackgroundColorActive'] } },
    { name: 'buttonActiveColor', type: 'color', variations: ['view'], params: { web: ['buttonActiveColor'] } },
    { name: 'buttonArrowColor', type: 'color', variations: ['view'], params: { web: ['buttonArrowColor'] } },
    { name: 'buttonArrowColorHover', type: 'color', variations: ['view'], params: { web: ['buttonArrowColorHover'] } },
    { name: 'buttonArrowColorActive', type: 'color', variations: ['view'], params: { web: ['buttonArrowColorActive'] } },
    { name: 'paginationHelperTextGap', type: 'dimension', variations: ['size'], params: { web: ['paginationHelperTextGap'] } },
    { name: 'selectTargetLabelInnerTop', type: 'dimension', variations: ['size'], params: { web: ['selectTargetLabelInnerTop'] } },
    { name: 'inputWidth', type: 'dimension', variations: ['size'], params: { web: ['inputWidth'] } },
    { name: 'inputHeight', type: 'dimension', variations: ['size'], params: { web: ['inputHeight'] } },
    { name: 'inputBorderWidth', type: 'dimension', variations: ['size'], params: { web: ['inputBorderWidth'] } },
    { name: 'buttonRadius', type: 'dimension', variations: ['size'], params: { web: ['buttonRadius'] } },
    { name: 'inputBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['inputBorderRadius'] } },
    { name: 'buttonArrowMargin', type: 'dimension', variations: ['size'], params: { web: ['buttonArrowMargin'] } },
    { name: 'selectItemPadding', type: 'dimension', variations: ['size'], params: { web: ['selectItemPadding'] } },
    { name: 'selectTargetPadding', type: 'dimension', variations: ['size'], params: { web: ['selectTargetPadding'] } },
    { name: 'inputPadding', type: 'dimension', variations: ['size'], params: { web: ['inputPadding'] } },
];
