import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'buttonActiveColor', token: 'text.inverse.primary' },
            { prop: 'buttonArrowColorActive', token: 'text.inverse.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.solid-default-hover' },
            { prop: 'buttonColorActive', token: 'text.inverse.primary-active' },
            { prop: 'buttonDisabledOpacity', value: '0.4' },
            { prop: 'buttonHoverColor', token: 'text.inverse.primary' },
            { prop: 'inputBorderColor', value: 'transparent' },
            { prop: 'paginationHelperTextColor', token: 'text.default.secondary' },
            { prop: 'buttonArrowColor', token: 'text.inverse.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.inverse.secondary-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.solid-default-active' },
            { prop: 'buttonColor', token: 'text.inverse.primary' },
            { prop: 'buttonColorHover', token: 'text.inverse.primary-hover' },
            { prop: 'buttonFocusColor', token: 'surface.default.accent' },
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'paginationColor', token: 'text.default.primary' },
        ],
        secondary: [
            { prop: 'buttonArrowColor', token: 'text.default.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.default.secondary-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.transparent-secondary-active' },
            { prop: 'buttonColor', token: 'text.default.primary' },
            { prop: 'buttonColorHover', token: 'text.default.primary-hover' },
            { prop: 'buttonFocusColor', token: 'surface.default.accent' },
            { prop: 'buttonActiveColor', token: 'text.default.primary' },
            { prop: 'buttonArrowColorActive', token: 'text.default.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'buttonColorActive', token: 'text.default.primary-active' },
            { prop: 'buttonDisabledOpacity', value: '0.4' },
            { prop: 'buttonHoverColor', token: 'text.default.primary' },
            { prop: 'inputBorderColor', value: 'transparent' },
            { prop: 'paginationHelperTextColor', token: 'text.default.secondary' },
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'paginationColor', token: 'text.default.primary' },
            { prop: 'selectBackgroundColor', token: 'surface.default.solid-secondary' },
        ],
        clear: [
            { prop: 'buttonActiveColor', token: 'text.default.primary' },
            { prop: 'buttonArrowColor', token: 'text.default.secondary' },
            { prop: 'buttonArrowColorHover', token: 'text.default.secondary-hover' },
            { prop: 'buttonBackgroundColorActive', token: 'surface.default.clear' },
            { prop: 'buttonColor', token: 'text.default.primary' },
            { prop: 'buttonColorHover', token: 'text.default.primary-hover' },
            { prop: 'buttonFocusColor', token: 'surface.default.accent' },
            { prop: 'inputBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'paginationColor', token: 'text.default.primary' },
            { prop: 'selectBackgroundColor', token: 'surface.default.solid-card' },
            { prop: 'buttonArrowColorActive', token: 'text.default.secondary-hover' },
            { prop: 'buttonBackgroundColor', token: 'surface.default.clear' },
            { prop: 'buttonBackgroundColorHover', token: 'surface.default.clear' },
            { prop: 'buttonColorActive', token: 'text.default.primary-active' },
            { prop: 'buttonDisabledOpacity', value: '0.4' },
            { prop: 'buttonHoverColor', token: 'text.default.primary' },
            { prop: 'inputBorderColor', value: 'transparent' },
            { prop: 'paginationHelperTextColor', token: 'text.default.secondary' },
        ],
    },
    viewCurrentPage: {
        default: [
            { prop: 'paginationCurrentButtonBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'paginationCurrentButtonHoverColor', token: 'text.inverse.primary' },
            { prop: 'paginationCurrentButtonActiveColor', token: 'text.inverse.primary' },
            { prop: 'paginationCurrentButtonColor', token: 'text.inverse.primary' },
        ],
        secondary: [
            { prop: 'paginationCurrentButtonBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'paginationCurrentButtonHoverColor', token: 'text.default.primary' },
            { prop: 'paginationCurrentButtonActiveColor', token: 'text.default.primary' },
            { prop: 'paginationCurrentButtonColor', token: 'text.default.primary' },
        ],
        clear: [
            { prop: 'paginationCurrentButtonActiveColor', token: 'text.default.primary' },
            { prop: 'paginationCurrentButtonColor', token: 'text.default.primary' },
            { prop: 'paginationCurrentButtonHoverColor', token: 'text.default.primary' },
            { prop: 'paginationCurrentButtonActiveBackgroundColor', value: 'color-mix(in srgb, var(--text-primary), var(--surface-clear) 90%)' },
            { prop: 'paginationCurrentButtonBackgroundColor', token: 'surface.default.clear' },
            { prop: 'paginationCurrentButtonHoverBackgroundColor', value: 'color-mix(in srgb, var(--text-primary), var(--surface-clear) 95%)' },
        ],
    },
    size: {
        l: [
            { prop: 'buttonRadius', value: '14' },
            { prop: 'buttonWidthShorter', value: '36' },
            { prop: 'inputBorderWidth', value: '1' },
            { prop: 'inputPadding', value: '10', adjust: [{ platform: 'web', param: 'inputPadding', template: '0 $1' }] },
            { prop: 'inputWidth', value: '64' },
            { prop: 'paginationIconSize', value: '19.2' },
            { prop: 'paginationStyle', value: 'body.l.bold' },
            { prop: 'selectItemBackground', value: 'transparent' },
            { prop: 'selectItemHeight', value: '24' },
            { prop: 'selectPaddingLeft', value: '2' },
            { prop: 'selectPaddingTop', value: '2' },
            { prop: 'selectTargetInnerTop', value: '8' },
            { prop: 'selectTargetPadding', value: '24', adjust: [{ platform: 'web', param: 'selectTargetPadding', template: '$1 0 $1' }] },
            { prop: 'buttonArrowMargin', value: '8', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonHeight', value: '56' },
            { prop: 'buttonWidth', value: '48' },
            { prop: 'inputBorderRadius', value: '14' },
            { prop: 'inputHeight', value: '56' },
            { prop: 'paginationHelperTextGap', value: '8', adjust: [{ platform: 'web', param: 'paginationHelperTextGap', template: '$1 2.5rem' }] },
            { prop: 'paginationIconDoubleSize', value: '23.2' },
            { prop: 'paginationInputWidth', value: '64' },
            { prop: 'selectHeight', value: 'auto' },
            { prop: 'selectItemContentLeftWidth', value: '30' },
            { prop: 'selectItemPadding', value: '16', adjust: [{ platform: 'web', param: 'selectItemPadding', template: '$1 0.5rem $1 0.5rem' }] },
            { prop: 'selectPaddingBottom', value: '2' },
            { prop: 'selectPaddingRight', value: '2' },
            { prop: 'selectTargetArrowRight', value: '16' },
            { prop: 'selectTargetLabelInnerTop', value: '6' },
        ],
        m: [
            { prop: 'buttonArrowMargin', value: '6', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonHeight', value: '48' },
            { prop: 'buttonWidth', value: '48' },
            { prop: 'inputBorderRadius', value: '12' },
            { prop: 'inputHeight', value: '48' },
            { prop: 'paginationHelperTextGap', value: '8', adjust: [{ platform: 'web', param: 'paginationHelperTextGap', template: '$1 2.5rem' }] },
            { prop: 'paginationIconDoubleSize', value: '20.8' },
            { prop: 'paginationInputWidth', value: '56' },
            { prop: 'selectHeight', value: 'auto' },
            { prop: 'selectItemContentLeftWidth', value: '28' },
            { prop: 'selectItemPadding', value: '12', adjust: [{ platform: 'web', param: 'selectItemPadding', template: '$1 0.5rem $1 0.5rem' }] },
            { prop: 'selectPaddingBottom', value: '2' },
            { prop: 'selectPaddingRight', value: '2' },
            { prop: 'selectTargetArrowRight', value: '14' },
            { prop: 'selectTargetLabelInnerTop', value: '6' },
            { prop: 'buttonRadius', value: '12' },
            { prop: 'buttonWidthShorter', value: '32' },
            { prop: 'inputBorderWidth', value: '1' },
            { prop: 'inputPadding', value: '10', adjust: [{ platform: 'web', param: 'inputPadding', template: '0 $1' }] },
            { prop: 'inputWidth', value: '56' },
            { prop: 'paginationIconSize', value: '16.8' },
            { prop: 'paginationStyle', value: 'body.m.bold' },
            { prop: 'selectItemBackground', value: 'transparent' },
            { prop: 'selectItemHeight', value: '24' },
            { prop: 'selectPaddingLeft', value: '2' },
            { prop: 'selectPaddingTop', value: '2' },
            { prop: 'selectTargetInnerTop', value: '8' },
            { prop: 'selectTargetPadding', value: '20', adjust: [{ platform: 'web', param: 'selectTargetPadding', template: '$1 0 $1' }] },
        ],
        s: [
            { prop: 'buttonRadius', value: '10' },
            { prop: 'buttonWidthShorter', value: '28' },
            { prop: 'inputBorderWidth', value: '1' },
            { prop: 'inputPadding', value: '10', adjust: [{ platform: 'web', param: 'inputPadding', template: '0 $1' }] },
            { prop: 'inputWidth', value: '48' },
            { prop: 'paginationIconSize', value: '14.4' },
            { prop: 'paginationStyle', value: 'body.s.bold' },
            { prop: 'buttonArrowMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonHeight', value: '40' },
            { prop: 'buttonWidth', value: '40' },
            { prop: 'inputBorderRadius', value: '10' },
            { prop: 'inputHeight', value: '40' },
            { prop: 'paginationHelperTextGap', value: '8', adjust: [{ platform: 'web', param: 'paginationHelperTextGap', template: '$1 2.5rem' }] },
            { prop: 'paginationIconDoubleSize', value: '18.4' },
            { prop: 'paginationInputWidth', value: '48' },
            { prop: 'selectHeight', value: 'auto' },
            { prop: 'selectItemContentLeftWidth', value: '28' },
            { prop: 'selectItemBackground', value: 'transparent' },
            { prop: 'selectItemHeight', value: '24' },
            { prop: 'selectPaddingLeft', value: '2' },
            { prop: 'selectPaddingTop', value: '2' },
            { prop: 'selectTargetInnerTop', value: '8' },
            { prop: 'selectTargetPadding', value: '16', adjust: [{ platform: 'web', param: 'selectTargetPadding', template: '$1 0 $1' }] },
            { prop: 'selectItemPadding', value: '8', adjust: [{ platform: 'web', param: 'selectItemPadding', template: '$1 0.5rem $1 0.5rem' }] },
            { prop: 'selectPaddingBottom', value: '2' },
            { prop: 'selectPaddingRight', value: '2' },
            { prop: 'selectTargetArrowRight', value: '12' },
            { prop: 'selectTargetLabelInnerTop', value: '6' },
        ],
        xs: [
            { prop: 'buttonArrowMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonArrowMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'buttonHeight', value: '32' },
            { prop: 'buttonWidth', value: '32' },
            { prop: 'inputBorderRadius', value: '8' },
            { prop: 'inputHeight', value: '32' },
            { prop: 'paginationHelperTextGap', value: '8', adjust: [{ platform: 'web', param: 'paginationHelperTextGap', template: '$1 2.5rem' }] },
            { prop: 'paginationIconDoubleSize', value: '16' },
            { prop: 'paginationInputWidth', value: '40' },
            { prop: 'selectHeight', value: 'auto' },
            { prop: 'selectItemContentLeftWidth', value: '20' },
            { prop: 'selectItemPadding', value: '8', adjust: [{ platform: 'web', param: 'selectItemPadding', template: '$1 0.5rem $1 0.5rem' }] },
            { prop: 'selectPaddingBottom', value: '2' },
            { prop: 'selectPaddingRight', value: '2' },
            { prop: 'selectTargetArrowRight', value: '8' },
            { prop: 'selectTargetLabelInnerTop', value: '6' },
            { prop: 'buttonRadius', value: '8' },
            { prop: 'buttonWidthShorter', value: '24' },
            { prop: 'inputBorderWidth', value: '1' },
            { prop: 'inputPadding', value: '10', adjust: [{ platform: 'web', param: 'inputPadding', template: '0 $1' }] },
            { prop: 'inputWidth', value: '40' },
            { prop: 'paginationIconSize', value: '12' },
            { prop: 'paginationStyle', value: 'body.xs.bold' },
            { prop: 'selectItemBackground', value: 'transparent' },
            { prop: 'selectItemHeight', value: '16' },
            { prop: 'selectPaddingLeft', value: '2' },
            { prop: 'selectPaddingTop', value: '2' },
            { prop: 'selectTargetInnerTop', value: '8' },
            { prop: 'selectTargetPadding', value: '12', adjust: [{ platform: 'web', param: 'selectTargetPadding', template: '$1 0 $1' }] },
        ],
    },
};
