import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'chipWidth', type: 'value', variations: ['size'], params: { web: ['chipWidth'] } },
    { name: 'tooltipArrowMaskImage', type: 'value', variations: ['hintSize'], params: { web: ['tooltipArrowMaskImage'] } },
    { name: 'dividerColorHover', type: 'color', variations: ['view'], params: { web: ['dividerColorHover'] } },
    { name: 'rightHelperStyle', type: 'typography', variations: ['size'], params: { web: ['rightHelperFontFamily', 'rightHelperFontSize', 'rightHelperFontStyle', 'rightHelperFontWeight', 'rightHelperLetterSpacing', 'rightHelperLineHeight'] } },
    { name: 'indicatorLabelPlacementOuterRight', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementOuterRight'] } },
    { name: 'rightContentWithHintMargin', type: 'dimension', variations: ['size'], params: { web: ['rightContentWithHintMargin'] } },
    { name: 'optionalColor', type: 'color', variations: ['view'], params: { web: ['optionalColor'] } },
    { name: 'dividerColorFocus', type: 'color', variations: ['view'], params: { web: ['dividerColorFocus'] } },
    { name: 'focusColor', type: 'color', variations: ['view'], params: { web: ['focusColor'] } },
    { name: 'labelStyle', type: 'typography', variations: ['size'], params: { web: ['labelFontFamily', 'labelFontSize', 'labelFontStyle', 'labelFontWeight', 'labelLetterSpacing', 'labelLineHeight'] } },
    { name: 'labelOffset', type: 'dimension', variations: ['size'], params: { web: ['labelOffset'] } },
    { name: 'hintTargetSize', type: 'dimension', variations: ['size'], params: { web: ['hintTargetSize'] } },
    { name: 'textBeforeColor', type: 'color', variations: ['view'], params: { web: ['textBeforeColor'] } },
    { name: 'textAfterColor', type: 'color', variations: ['view'], params: { web: ['textAfterColor'] } },
    { name: 'labelColor', type: 'color', variations: ['view'], params: { web: ['labelColor'] } },
    { name: 'leftHelperColor', type: 'color', variations: ['view'], params: { web: ['leftHelperColor'] } },
    { name: 'rightHelperColor', type: 'color', variations: ['view'], params: { web: ['rightHelperColor'] } },
    { name: 'titleCaptionColor', type: 'color', variations: ['view'], params: { web: ['titleCaptionColor'] } },
    { name: 'hintIconColor', type: 'color', variations: ['view'], params: { web: ['hintIconColor'] } },
    { name: 'contentSlotColor', type: 'color', variations: ['view'], params: { web: ['contentSlotColor'] } },
    { name: 'contentSlotColorHover', type: 'color', variations: ['view'], params: { web: ['contentSlotColorHover'] } },
    { name: 'contentSlotColorActive', type: 'color', variations: ['view'], params: { web: ['contentSlotColorActive'] } },
    { name: 'dividerColor', type: 'color', variations: ['view'], params: { web: ['dividerColor'] } },
    { name: 'indicatorColor', type: 'color', variations: ['view'], params: { web: ['indicatorColor'] } },
    { name: 'textStyle', type: 'typography', variations: ['size'], params: { web: ['fontFamily', 'fontSize', 'fontStyle', 'fontWeight', 'letterSpacing', 'lineHeight'] } },
    { name: 'height', type: 'dimension', variations: ['size'], params: { web: ['height'] } },
    { name: 'paddingWithChips', type: 'dimension', variations: ['size'], params: { web: ['paddingWithChips'] } },
    { name: 'chipGap', type: 'dimension', variations: ['size'], params: { web: ['chipGap'] } },
    { name: 'borderRadius', type: 'dimension', variations: ['size'], params: { web: ['borderRadius'] } },
    { name: 'backgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['backgroundColorFocus'] } },
    { name: 'caretColor', type: 'color', variations: ['view'], params: { web: ['caretColor'] } },
    { name: 'chipColor', type: 'color', variations: ['chipView'], params: { web: ['chipColor'] } },
    { name: 'chipBackground', type: 'color', variations: ['chipView'], params: { web: ['chipBackground'] } },
    { name: 'chipColorHover', type: 'color', variations: ['chipView'], params: { web: ['chipColorHover'] } },
    { name: 'chipBackgroundHover', type: 'color', variations: ['chipView'], params: { web: ['chipBackgroundHover'] } },
    { name: 'chipColorActive', type: 'color', variations: ['chipView'], params: { web: ['chipColorActive'] } },
    { name: 'chipBackgroundActive', type: 'color', variations: ['chipView'], params: { web: ['chipBackgroundActive'] } },
    { name: 'tooltipTextStyle', type: 'typography', variations: ['hintSize'], params: { web: ['tooltipTextFontFamily', 'tooltipTextFontSize', 'tooltipTextFontStyle', 'tooltipTextFontWeight', 'tooltipTextFontLetterSpacing', 'tooltipTextFontLineHeight'] } },
    { name: 'colorReadOnly', type: 'color', params: { web: ['colorReadOnly'] } },
    { name: 'backgroundColorReadOnly', type: 'color', params: { web: ['backgroundColorReadOnly'] } },
    { name: 'placeholderColorReadOnly', type: 'color', params: { web: ['placeholderColorReadOnly'] } },
    { name: 'leftHelperColorReadOnly', type: 'color', params: { web: ['leftHelperColorReadOnly'] } },
    { name: 'rightHelperColorReadOnly', type: 'color', params: { web: ['rightHelperColorReadOnly'] } },
    { name: 'titleCaptionColorReadOnly', type: 'color', params: { web: ['titleCaptionColorReadOnly'] } },
    { name: 'labelColorReadOnly', type: 'color', params: { web: ['labelColorReadOnly'] } },
    { name: 'dividerColorReadOnly', type: 'color', params: { web: ['dividerColorReadOnly'] } },
    { name: 'contentRightWrapperGap', type: 'dimension', variations: ['size'], params: { web: ['contentRightWrapperGap'] } },
    { name: 'tooltipArrowEdgeMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowEdgeMargin'] } },
    { name: 'disabledOpacity', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'readOnlyOpacity', type: 'float', params: { web: ['readOnlyOpacity'] } },
    { name: 'tooltipBorderRadius', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipBorderRadius'] } },
    { name: 'chipBorderRadius', type: 'dimension', variations: ['size'], params: { web: ['chipBorderRadius'] } },
    { name: 'textBeforeMargin', type: 'dimension', variations: ['size'], params: { web: ['textBeforeMargin'] } },
    { name: 'titleCaptionStyle', type: 'typography', variations: ['size'], params: { web: ['titleCaptionFontFamily', 'titleCaptionFontSize', 'titleCaptionFontStyle', 'titleCaptionFontWeight', 'titleCaptionLetterSpacing', 'titleCaptionLineHeight'] } },
    { name: 'titleCaptionInnerLabelOffset', type: 'dimension', variations: ['size'], params: { web: ['titleCaptionInnerLabelOffset'] } },
    { name: 'chipStyle', type: 'typography', variations: ['size'], params: { web: ['chipFontFamily', 'chipFontSize', 'chipFontStyle', 'chipFontWeight', 'chipLetterSpacing', 'chipLineHeight'] } },
    { name: 'labelInnerStyle', type: 'typography', variations: ['size', 'labelPlacement'], params: { web: ['labelInnerFontFamily', 'labelInnerFontSize', 'labelInnerFontStyle', 'labelInnerFontWeight', 'labelInnerLetterSpacing', 'labelInnerLineHeight'] } },
    { name: 'chipBackgroundReadOnly', type: 'color', variations: ['chipView'], params: { web: ['chipBackgroundReadOnly'] } },
    { name: 'chipColorReadOnly', type: 'color', variations: ['chipView'], params: { web: ['chipColorReadOnly'] } },
    { name: 'chipBackgroundReadOnlyHover', type: 'color', variations: ['chipView'], params: { web: ['chipBackgroundReadOnlyHover'] } },
    { name: 'chipColorReadOnlyHover', type: 'color', variations: ['chipView'], params: { web: ['chipColorReadOnlyHover'] } },
    { name: 'chipCloseIconColor', type: 'color', variations: ['chipView'], params: { web: ['chipCloseIconColor'] } },
    { name: 'chipCloseIconColorReadonly', type: 'color', variations: ['chipView'], params: { web: ['chipCloseIconColorReadonly'] } },
    { name: 'chipCloseIconColorHover', type: 'color', variations: ['chipView'], params: { web: ['chipCloseIconColorHover'] } },
    { name: 'tooltipBackgroundColor', type: 'color', variations: ['hintView'], params: { web: ['tooltipBackgroundColor'] } },
    { name: 'tooltipBoxShadow', type: 'shadow', variations: ['hintView'], params: { web: ['tooltipBoxShadow'] } },
    { name: 'chipMarginRight', type: 'dimension', variations: ['size'], params: { web: ['chipMarginRight'] } },
    { name: 'chipHeight', type: 'dimension', variations: ['size'], params: { web: ['chipHeight'] } },
    { name: 'chipClearContentMarginLeft', type: 'dimension', variations: ['size'], params: { web: ['chipClearContentMarginLeft'] } },
    { name: 'chipClearContentMarginRight', type: 'dimension', variations: ['size'], params: { web: ['chipClearContentMarginRight'] } },
    { name: 'chipCloseIconSize', type: 'dimension', variations: ['size'], params: { web: ['chipCloseIconSize'] } },
    { name: 'indicatorSizeInner', type: 'dimension', variations: ['size'], params: { web: ['indicatorSizeInner'] } },
    { name: 'indicatorSizeOuter', type: 'dimension', variations: ['size'], params: { web: ['indicatorSizeOuter'] } },
    { name: 'borderWidth', type: 'dimension', variations: ['size'], params: { web: ['borderWidth'] } },
    { name: 'chipOpacityReadonly', type: 'float', variations: ['chipView'], params: { web: ['chipOpacityReadonly'] } },
    { name: 'contentSlotRightOpacityReadOnly', type: 'float', params: { web: ['contentSlotRightOpacityReadOnly'] } },
    { name: 'rightContentMargin', type: 'dimension', variations: ['size'], params: { web: ['rightContentMargin'] } },
    { name: 'hintInnerLabelPlacementOffset', type: 'dimension', variations: ['size'], params: { web: ['hintInnerLabelPlacementOffset'] } },
    { name: 'leftHelperOffset', type: 'dimension', variations: ['size'], params: { web: ['leftHelperOffset'] } },
    { name: 'rightHelperOffset', type: 'dimension', variations: ['size'], params: { web: ['rightHelperOffset'] } },
    { name: 'labelInnerPadding', type: 'dimension', variations: ['size'], params: { web: ['labelInnerPadding'] } },
    { name: 'contentLabelInnerPadding', type: 'dimension', variations: ['size'], params: { web: ['contentLabelInnerPadding'] } },
    { name: 'textAfterMargin', type: 'dimension', variations: ['size'], params: { web: ['textAfterMargin'] } },
    { name: 'chipPadding', type: 'dimension', variations: ['size'], params: { web: ['chipPadding'] } },
    { name: 'indicatorLabelPlacementInner', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementInner'] } },
    { name: 'indicatorLabelPlacementOuter', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementOuter'] } },
    { name: 'indicatorLabelPlacementInnerRight', type: 'dimension', variations: ['size'], params: { web: ['indicatorLabelPlacementInnerRight'] } },
    { name: 'contentRightWrapperMargin', type: 'dimension', variations: ['size'], params: { web: ['contentRightWrapperMargin'] } },
    { name: 'clearHintInnerLabelPlacementOffset', type: 'dimension', variations: ['size'], params: { web: ['clearHintInnerLabelPlacementOffset'] } },
    { name: 'leftHelperStyle', type: 'typography', variations: ['size'], params: { web: ['leftHelperFontFamily', 'leftHelperFontSize', 'leftHelperFontStyle', 'leftHelperFontWeight', 'leftHelperLetterSpacing', 'leftHelperLineHeight'] } },
    { name: 'tooltipColor', type: 'color', variations: ['hintView'], params: { web: ['tooltipColor'] } },
    { name: 'tooltipArrowBackground', type: 'color', variations: ['hintView'], params: { web: ['tooltipArrowBackground'] } },
    { name: 'hintMargin', type: 'value', variations: ['size'], params: { web: ['hintMargin'] } },
    { name: 'tooltipPaddingTop', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingTop'] } },
    { name: 'tooltipPaddingRight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingRight'] } },
    { name: 'tooltipPaddingBottom', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingBottom'] } },
    { name: 'tooltipPaddingLeft', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipPaddingLeft'] } },
    { name: 'tooltipMinHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipMinHeight'] } },
    { name: 'tooltipContentLeftMargin', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipContentLeftMargin'] } },
    { name: 'tooltipArrowMaskWidth', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowMaskWidth'] } },
    { name: 'tooltipArrowMaskHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowMaskHeight'] } },
    { name: 'tooltipArrowHeight', type: 'dimension', variations: ['hintSize'], params: { web: ['tooltipArrowHeight'] } },
    { name: 'leftContentMargin', type: 'dimension', variations: ['size'], params: { web: ['leftContentMargin'] } },
    { name: 'padding', type: 'value', variations: ['size'], params: { web: ['padding'] } },
    { name: 'color', type: 'color', variations: ['view'], params: { web: ['color'] } },
    { name: 'placeholderColor', type: 'color', variations: ['view', 'labelPlacement'], params: { web: ['placeholderColor'] } },
    { name: 'placeholderColorFocus', type: 'color', variations: ['view'], params: { web: ['placeholderColorFocus'] } },
    { name: 'backgroundColor', type: 'color', variations: ['view'], params: { web: ['backgroundColor'] } },
    { name: 'backgroundColorHover', type: 'color', variations: ['view'], params: { web: ['backgroundColorHover'] } },
];
