import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'backgroundColorHover', token: 'surface.default.transparent-primary-hover' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'textBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textAfterColor', token: 'text.default.tertiary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'leftHelperColor', token: 'text.default.secondary' },
            { prop: 'rightHelperColor', token: 'text.default.secondary' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'contentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'dividerColor', token: 'surface.default.transparent-tertiary' },
            { prop: 'dividerColorHover', token: 'text.default.secondary' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'focusColor', token: 'text.default.accent' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
        ],
        positive: [
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-positive' },
            { prop: 'backgroundColorHover', token: 'surface.default.transparent-positive-hover' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-positive-active' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'textBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textAfterColor', token: 'text.default.tertiary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'leftHelperColor', token: 'text.default.positive' },
            { prop: 'rightHelperColor', token: 'text.default.positive' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'contentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'dividerColor', token: 'surface.default.positive' },
            { prop: 'dividerColorHover', token: 'surface.default.positive' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'focusColor', token: 'text.default.accent' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
        ],
        warning: [
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-warning' },
            { prop: 'backgroundColorHover', token: 'surface.default.transparent-warning-hover' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-warning-active' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'textBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textAfterColor', token: 'text.default.tertiary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'leftHelperColor', token: 'text.default.warning' },
            { prop: 'rightHelperColor', token: 'text.default.warning' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'contentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'dividerColor', token: 'surface.default.warning' },
            { prop: 'dividerColorHover', token: 'surface.default.warning' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'focusColor', token: 'text.default.accent' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
        ],
        negative: [
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'placeholderColorFocus', token: 'text.default.tertiary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-negative' },
            { prop: 'backgroundColorHover', token: 'surface.default.transparent-negative-hover' },
            { prop: 'backgroundColorFocus', token: 'surface.default.transparent-negative-active' },
            { prop: 'caretColor', token: 'text.default.accent' },
            { prop: 'textBeforeColor', token: 'text.default.tertiary' },
            { prop: 'textAfterColor', token: 'text.default.tertiary' },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'leftHelperColor', token: 'text.default.negative' },
            { prop: 'rightHelperColor', token: 'text.default.negative' },
            { prop: 'titleCaptionColor', token: 'text.default.secondary' },
            { prop: 'hintIconColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColor', token: 'text.default.secondary' },
            { prop: 'contentSlotColorHover', token: 'text.default.secondary-hover' },
            { prop: 'contentSlotColorActive', token: 'text.default.secondary-active' },
            { prop: 'dividerColor', token: 'surface.default.negative' },
            { prop: 'dividerColorHover', token: 'surface.default.negative' },
            { prop: 'dividerColorFocus', token: 'surface.default.accent' },
            { prop: 'focusColor', token: 'text.default.accent' },
            { prop: 'indicatorColor', token: 'surface.default.negative' },
            { prop: 'optionalColor', token: 'text.default.tertiary' },
        ],
    },
    size: {
        xl: [
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'padding', value: '1.3125rem 1.125rem' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'height', value: '64' },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'labelOffset', value: '12' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'chipGap', value: '2' },
            { prop: 'chipMarginRight', value: '16' },
            { prop: 'chipHeight', value: '52' },
            { prop: 'chipClearContentMarginLeft', value: '10' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipCloseIconSize', value: '24' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'textStyle', value: 'body.l.normal' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightHelperStyle', value: 'body.xs.normal' },
            { prop: 'chipStyle', value: 'body.l.normal' },
            { prop: 'labelInnerStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '16' },
            { prop: 'chipBorderRadius', value: '10' },
            { prop: 'leftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'rightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '13.12', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'rightHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'rightHelperOffset', template: '$1 0 0 0.25rem' }] },
            { prop: 'labelInnerPadding', value: '13', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'contentLabelInnerPadding', value: '29.008', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'chipPadding', value: '12', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '8', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
        ],
        l: [
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'padding', value: '1.0625rem 1.125rem 1.0625rem 1.125rem' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'height', value: '56' },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'labelOffset', value: '12' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipHeight', value: '44' },
            { prop: 'chipClearContentMarginLeft', value: '10' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipCloseIconSize', value: '24' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'borderWidth', value: '1' },
            { prop: 'contentRightWrapperGap', value: '4' },
            { prop: 'textStyle', value: 'body.l.normal' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightHelperStyle', value: 'body.xs.normal' },
            { prop: 'chipStyle', value: 'body.l.normal' },
            { prop: 'borderRadius', value: '14' },
            { prop: 'chipBorderRadius', value: '8' },
            { prop: 'leftContentMargin', value: '8', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'rightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '9.008', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'rightHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'rightHelperOffset', template: '$1 0 0 0.25rem' }] },
            { prop: 'labelInnerPadding', value: '9', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'contentLabelInnerPadding', value: '25', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'chipPadding', value: '12', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '8', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'rightContentWithHintMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'rightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'contentRightWrapperMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'contentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'clearHintInnerLabelPlacementOffset', value: '9.008', adjust: [{ platform: 'web', param: 'clearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
        ],
        m: [
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'padding', value: '0.875rem 1rem 0.875rem 1rem' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'height', value: '48' },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'labelOffset', value: '10' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipHeight', value: '36' },
            { prop: 'chipClearContentMarginLeft', value: '8' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipCloseIconSize', value: '20' },
            { prop: 'indicatorSizeInner', value: '8' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'borderWidth', value: '1' },
            { prop: 'contentRightWrapperGap', value: '4' },
            { prop: 'textStyle', value: 'body.m.normal' },
            { prop: 'labelStyle', value: 'body.m.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightHelperStyle', value: 'body.xs.normal' },
            { prop: 'chipStyle', value: 'body.m.normal' },
            { prop: 'borderRadius', value: '12' },
            { prop: 'chipBorderRadius', value: '6' },
            { prop: 'leftContentMargin', value: '6', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'rightContentMargin', value: '-2', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '4.992', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'rightHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'rightHelperOffset', template: '$1 0 0 0.25rem' }] },
            { prop: 'labelInnerPadding', value: '6', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'contentLabelInnerPadding', value: '22', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'chipPadding', value: '10', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '6', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'rightContentWithHintMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'rightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'contentRightWrapperMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'contentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'clearHintInnerLabelPlacementOffset', value: '4.992', adjust: [{ platform: 'web', param: 'clearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
        ],
        s: [
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'padding', value: '0.6875rem 0.875rem 0.6875rem 0.875rem' },
            { prop: 'hintMargin', value: '-0.688rem -0.5rem' },
            { prop: 'height', value: '40' },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'labelOffset', value: '8' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipHeight', value: '28' },
            { prop: 'chipClearContentMarginLeft', value: '6' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipCloseIconSize', value: '16' },
            { prop: 'indicatorSizeInner', value: '6' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'borderWidth', value: '1' },
            { prop: 'contentRightWrapperGap', value: '4' },
            { prop: 'textStyle', value: 'body.s.normal' },
            { prop: 'labelStyle', value: 'body.s.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightHelperStyle', value: 'body.xs.normal' },
            { prop: 'chipStyle', value: 'body.s.normal' },
            { prop: 'borderRadius', value: '10' },
            { prop: 'chipBorderRadius', value: '4' },
            { prop: 'leftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'rightContentMargin', value: '-3', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '0.992', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'rightHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'rightHelperOffset', template: '$1 0 0 0.25rem' }] },
            { prop: 'labelInnerPadding', value: '5', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'contentLabelInnerPadding', value: '17', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'chipPadding', value: '8', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '5', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'rightContentWithHintMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'rightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'contentRightWrapperMargin', value: '-7.008', adjust: [{ platform: 'web', param: 'contentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'clearHintInnerLabelPlacementOffset', value: '0.992', adjust: [{ platform: 'web', param: 'clearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
        ],
        xs: [
            { prop: 'chipWidth', value: 'auto' },
            { prop: 'padding', value: '0.5625rem 0.625rem 0.5625rem 0.625rem' },
            { prop: 'hintMargin', value: '-0.75rem -0.625rem -0.75rem -0.5rem' },
            { prop: 'height', value: '32' },
            { prop: 'paddingWithChips', value: '6' },
            { prop: 'labelOffset', value: '6' },
            { prop: 'hintTargetSize', value: '38' },
            { prop: 'titleCaptionInnerLabelOffset', value: '4' },
            { prop: 'chipGap', value: '4' },
            { prop: 'chipHeight', value: '20' },
            { prop: 'chipClearContentMarginLeft', value: '4' },
            { prop: 'chipClearContentMarginRight', value: '0' },
            { prop: 'chipCloseIconSize', value: '12' },
            { prop: 'indicatorSizeInner', value: '6' },
            { prop: 'indicatorSizeOuter', value: '6' },
            { prop: 'borderWidth', value: '1' },
            { prop: 'contentRightWrapperGap', value: '4' },
            { prop: 'textStyle', value: 'body.xs.normal' },
            { prop: 'labelStyle', value: 'body.xs.normal' },
            { prop: 'titleCaptionStyle', value: 'body.xs.normal' },
            { prop: 'leftHelperStyle', value: 'body.xs.normal' },
            { prop: 'rightHelperStyle', value: 'body.xs.normal' },
            { prop: 'chipStyle', value: 'body.xs.normal' },
            { prop: 'borderRadius', value: '8' },
            { prop: 'chipBorderRadius', value: '2' },
            { prop: 'leftContentMargin', value: '4', adjust: [{ platform: 'web', param: 'leftContentMargin', template: '-0.125rem $1 -0.125rem -0.125rem' }] },
            { prop: 'rightContentMargin', value: '-1', adjust: [{ platform: 'web', param: 'rightContentMargin', template: '$1 -0.125rem $1 0.75rem' }] },
            { prop: 'hintInnerLabelPlacementOffset', value: '-3.008', adjust: [{ platform: 'web', param: 'hintInnerLabelPlacementOffset', template: '$1 -2.813rem auto auto' }] },
            { prop: 'leftHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'leftHelperOffset', template: '$1 0 0 0' }] },
            { prop: 'rightHelperOffset', value: '4', adjust: [{ platform: 'web', param: 'rightHelperOffset', template: '$1 0 0 0.25rem' }] },
            { prop: 'labelInnerPadding', value: '5', adjust: [{ platform: 'web', param: 'labelInnerPadding', template: '$1 0 0.125rem 0' }] },
            { prop: 'contentLabelInnerPadding', value: '17', adjust: [{ platform: 'web', param: 'contentLabelInnerPadding', template: '$1 0 0.375rem 0' }] },
            { prop: 'textBeforeMargin', value: '4', adjust: [{ platform: 'web', param: 'textBeforeMargin', template: '0 $1 0 0' }] },
            { prop: 'textAfterMargin', value: '4', adjust: [{ platform: 'web', param: 'textAfterMargin', template: '0 0 0 $1' }] },
            { prop: 'chipPadding', value: '6', adjust: [{ platform: 'web', param: 'chipPadding', template: '0 $1 0 0.875rem' }] },
            { prop: 'indicatorLabelPlacementInner', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInner', template: '$1 0 0 0' }] },
            { prop: 'indicatorLabelPlacementOuter', value: '4', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuter', template: '$1 auto auto -0.75rem' }] },
            { prop: 'indicatorLabelPlacementInnerRight', value: '0', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementInnerRight', template: '$1 0 auto auto' }] },
            { prop: 'indicatorLabelPlacementOuterRight', value: '2', adjust: [{ platform: 'web', param: 'indicatorLabelPlacementOuterRight', template: '$1 -0.6875rem auto auto' }] },
            { prop: 'rightContentWithHintMargin', value: '-11.008', adjust: [{ platform: 'web', param: 'rightContentWithHintMargin', template: '-0.125rem $1 -0.125rem 0.75rem' }] },
            { prop: 'contentRightWrapperMargin', value: '-11.008', adjust: [{ platform: 'web', param: 'contentRightWrapperMargin', template: '$1 $1 $1 0' }] },
            { prop: 'clearHintInnerLabelPlacementOffset', value: '-3.008', adjust: [{ platform: 'web', param: 'clearHintInnerLabelPlacementOffset', template: '$1 -2.188rem auto auto' }] },
        ],
    },
    labelPlacement: {
        inner: [
            { prop: 'placeholderColor', token: 'text.default.secondary' },
            { prop: 'labelInnerStyle', value: 'body.xs.normal' },
        ],
    },
    chipView: {
        default: [
            { prop: 'chipColor', token: 'text.inverse.primary' },
            { prop: 'chipBackground', token: 'surface.default.solid-default' },
            { prop: 'chipColorHover', token: 'text.inverse.primary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.solid-default-hover' },
            { prop: 'chipColorActive', token: 'text.inverse.primary' },
            { prop: 'chipBackgroundActive', token: 'surface.default.solid-default-active' },
            { prop: 'chipBackgroundReadOnly', token: 'surface.default.solid-default' },
            { prop: 'chipColorReadOnly', token: 'text.inverse.primary' },
            { prop: 'chipBackgroundReadOnlyHover', token: 'surface.default.solid-default' },
            { prop: 'chipColorReadOnlyHover', token: 'text.inverse.primary' },
            { prop: 'chipCloseIconColor', token: 'text.inverse.secondary' },
            { prop: 'chipCloseIconColorReadonly', token: 'text.inverse.secondary' },
            { prop: 'chipCloseIconColorHover', token: 'text.inverse.secondary-hover' },
            { prop: 'chipOpacityReadonly', value: '1' },
        ],
        secondary: [
            { prop: 'chipColor', token: 'text.default.primary' },
            { prop: 'chipBackground', token: 'surface.default.transparent-secondary' },
            { prop: 'chipColorHover', token: 'text.default.primary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.transparent-secondary-hover' },
            { prop: 'chipColorActive', token: 'text.default.primary' },
            { prop: 'chipBackgroundActive', token: 'surface.default.transparent-secondary-active' },
            { prop: 'chipBackgroundReadOnly', token: 'surface.default.transparent-secondary' },
            { prop: 'chipColorReadOnly', token: 'text.default.primary' },
            { prop: 'chipBackgroundReadOnlyHover', token: 'surface.default.transparent-secondary' },
            { prop: 'chipColorReadOnlyHover', token: 'text.default.primary' },
            { prop: 'chipCloseIconColor', token: 'text.default.secondary' },
            { prop: 'chipCloseIconColorReadonly', token: 'text.default.secondary' },
            { prop: 'chipCloseIconColorHover', token: 'text.default.secondary-hover' },
            { prop: 'chipOpacityReadonly', value: '1' },
        ],
        accent: [
            { prop: 'chipColor', token: 'text.on-dark.primary' },
            { prop: 'chipBackground', token: 'surface.default.accent' },
            { prop: 'chipColorHover', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.accent-hover' },
            { prop: 'chipColorActive', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundActive', token: 'surface.default.accent-active' },
            { prop: 'chipBackgroundReadOnly', token: 'surface.default.accent' },
            { prop: 'chipColorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundReadOnlyHover', token: 'surface.default.accent' },
            { prop: 'chipColorReadOnlyHover', token: 'text.on-dark.primary' },
            { prop: 'chipCloseIconColor', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorReadonly', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'chipOpacityReadonly', value: '1' },
        ],
        positive: [
            { prop: 'chipColor', token: 'text.on-dark.primary' },
            { prop: 'chipBackground', token: 'surface.default.positive' },
            { prop: 'chipColorHover', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.positive-hover' },
            { prop: 'chipColorActive', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundActive', token: 'surface.default.positive-active' },
            { prop: 'chipBackgroundReadOnly', token: 'surface.default.positive' },
            { prop: 'chipColorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundReadOnlyHover', token: 'surface.default.positive' },
            { prop: 'chipColorReadOnlyHover', token: 'text.on-dark.primary' },
            { prop: 'chipCloseIconColor', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorReadonly', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'chipOpacityReadonly', value: '1' },
        ],
        warning: [
            { prop: 'chipColor', token: 'text.on-dark.primary' },
            { prop: 'chipBackground', token: 'surface.default.warning' },
            { prop: 'chipColorHover', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.warning-hover' },
            { prop: 'chipColorActive', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundActive', token: 'surface.default.warning-active' },
            { prop: 'chipBackgroundReadOnly', token: 'surface.default.warning' },
            { prop: 'chipColorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundReadOnlyHover', token: 'surface.default.warning' },
            { prop: 'chipColorReadOnlyHover', token: 'text.on-dark.primary' },
            { prop: 'chipCloseIconColor', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorReadonly', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'chipOpacityReadonly', value: '1' },
        ],
        negative: [
            { prop: 'chipColor', token: 'text.on-dark.primary' },
            { prop: 'chipBackground', token: 'surface.default.negative' },
            { prop: 'chipColorHover', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundHover', token: 'surface.default.negative-hover' },
            { prop: 'chipColorActive', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundActive', token: 'surface.default.negative-active' },
            { prop: 'chipBackgroundReadOnly', token: 'surface.default.negative' },
            { prop: 'chipColorReadOnly', token: 'text.on-dark.primary' },
            { prop: 'chipBackgroundReadOnlyHover', token: 'surface.default.negative' },
            { prop: 'chipColorReadOnlyHover', token: 'text.on-dark.primary' },
            { prop: 'chipCloseIconColor', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorReadonly', token: 'text.on-dark.secondary' },
            { prop: 'chipCloseIconColorHover', token: 'text.on-dark.secondary-hover' },
            { prop: 'chipOpacityReadonly', value: '1' },
        ],
    },
    hintView: {
        default: [
            { prop: 'tooltipBackgroundColor', token: 'surface.default.solid-card-brightness' },
            { prop: 'tooltipBoxShadow', value: 'down.hard.m' },
            { prop: 'tooltipColor', token: 'text.default.primary' },
            { prop: 'tooltipArrowBackground', token: 'surface.default.solid-card-brightness' },
        ],
    },
    hintSize: {
        m: [
            { prop: 'tooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMjAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMC4xNywxMS44M2wyMCwwYy01LjUyLDAgLTEwLDMuNTkgLTEwLDhjMCwtNC40MSAtNC40OCwtOCAtMTAsLTh6IiBmaWxsPSIjMTcxNzE3IiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGlkPSJUYWlsIi8+Cjwvc3ZnPg==")' },
            { prop: 'tooltipPaddingTop', value: '11' },
            { prop: 'tooltipPaddingRight', value: '14' },
            { prop: 'tooltipPaddingBottom', value: '11' },
            { prop: 'tooltipPaddingLeft', value: '14' },
            { prop: 'tooltipMinHeight', value: '40' },
            { prop: 'tooltipContentLeftMargin', value: '6' },
            { prop: 'tooltipArrowMaskWidth', value: '20' },
            { prop: 'tooltipArrowMaskHeight', value: '20' },
            { prop: 'tooltipArrowHeight', value: '8' },
            { prop: 'tooltipArrowEdgeMargin', value: '10' },
            { prop: 'tooltipTextStyle', value: 'body.s.normal' },
            { prop: 'tooltipBorderRadius', value: '10' },
        ],
        s: [
            { prop: 'tooltipArrowMaskImage', value: 'url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPHBhdGggY2xpcC1ydWxlPSJldmVub2RkIiBkPSJtMCw5Ljg1bDE2LDBjLTQuNDEsMCAtOCwyLjY5IC04LDZjMCwtMy4zMSAtMy41OSwtNiAtOCwtNnoiIGZpbGw9IiMxNzE3MTciIGZpbGwtcnVsZT0iZXZlbm9kZCIgaWQ9IlRhaWwiLz4KPC9zdmc+")' },
            { prop: 'tooltipPaddingTop', value: '8' },
            { prop: 'tooltipPaddingRight', value: '12' },
            { prop: 'tooltipPaddingBottom', value: '8' },
            { prop: 'tooltipPaddingLeft', value: '12' },
            { prop: 'tooltipMinHeight', value: '32' },
            { prop: 'tooltipContentLeftMargin', value: '4' },
            { prop: 'tooltipArrowMaskWidth', value: '16' },
            { prop: 'tooltipArrowMaskHeight', value: '16' },
            { prop: 'tooltipArrowHeight', value: '6' },
            { prop: 'tooltipArrowEdgeMargin', value: '9' },
            { prop: 'tooltipTextStyle', value: 'body.xs.normal' },
            { prop: 'tooltipBorderRadius', value: '8' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
    { prop: 'readOnlyOpacity', value: '0.1' },
    { prop: 'colorReadOnly', token: 'text.default.primary' },
    { prop: 'backgroundColorReadOnly', token: 'surface.default.transparent-primary' },
    { prop: 'placeholderColorReadOnly', token: 'text.default.secondary' },
    { prop: 'leftHelperColorReadOnly', token: 'text.default.secondary' },
    { prop: 'rightHelperColorReadOnly', token: 'text.default.secondary' },
    { prop: 'titleCaptionColorReadOnly', token: 'text.default.secondary' },
    { prop: 'labelColorReadOnly', token: 'text.default.primary' },
    { prop: 'dividerColorReadOnly', token: 'surface.default.transparent-primary' },
    { prop: 'contentSlotRightOpacityReadOnly', value: '0.4' },
];
