name: 'Prepare environment'

description: 'Setup node.js env and install all dependencies'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.16.1'
        cache: 'npm'
        cache-dependency-path: js/package-lock.json

    - name: Cache node modules
      id: node_modules
      uses: actions/cache@v3
      with:
        path: js/node_modules
        key: node-modules-${{ hashFiles('js/package-lock.json') }}
        restore-keys: |
          node-modules-${{ hashFiles('js/package-lock.json') }}
          node-modules-

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.cache
        key: cache-${{ hashFiles('js/package-lock.json') }}
        restore-keys: |
          cache-${{ hashFiles('js/package-lock.json') }}
          cache-            

    - name: Setup packages
      shell: bash
      if: ${{ steps.cache.outputs.cache-hit != 'true' && steps.node_modules.outputs.cache-hit != 'true' }}
      working-directory: js
      run: npm ci --no-progress
