import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.primary' },
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.solid-default' },
        ],
        secondary: [
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.transparent-secondary' },
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.secondary' },
        ],
        accent: [
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.accent' },
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.accent' },
        ],
        positive: [
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.positive' },
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.positive' },
        ],
        warning: [
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.warning' },
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.warning' },
        ],
        negative: [
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.negative' },
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.negative' },
        ],
        info: [
            { prop: 'overlayColor', token: 'overlay.default.soft' },
            { prop: 'progressBarCircularContentColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.info' },
            { prop: 'progressBarCircularBackgroundStroke', token: 'surface.default.transparent-tertiary' },
            { prop: 'progressBarCircularStroke', token: 'surface.default.info' },
        ],
    },
    size: {
        xxl: [
            { prop: 'progressBarCircularContentStyle', value: 'header.h2.bold' },
            { prop: 'progressBarCircularSize', value: '128' },
            { prop: 'progressBarCircularStrokeWidth', value: '4' },
            { prop: 'spinnerSize', value: '128' },
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularHeight', value: '128' },
            { prop: 'progressBarCircularStrokeSize', value: '4' },
            { prop: 'progressBarCircularWidth', value: '128' },
            { prop: 'width', value: '100%' },
        ],
        xl: [
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularHeight', value: '88' },
            { prop: 'progressBarCircularStrokeSize', value: '4' },
            { prop: 'progressBarCircularWidth', value: '88' },
            { prop: 'width', value: '100%' },
            { prop: 'progressBarCircularContentStyle', value: 'header.h5.bold' },
            { prop: 'progressBarCircularSize', value: '88' },
            { prop: 'progressBarCircularStrokeWidth', value: '4' },
            { prop: 'spinnerSize', value: '88' },
        ],
        l: [
            { prop: 'progressBarCircularContentStyle', value: 'body.l.normal' },
            { prop: 'progressBarCircularSize', value: '56' },
            { prop: 'progressBarCircularStrokeWidth', value: '2' },
            { prop: 'spinnerSize', value: '56' },
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularHeight', value: '56' },
            { prop: 'progressBarCircularStrokeSize', value: '2' },
            { prop: 'progressBarCircularWidth', value: '56' },
            { prop: 'width', value: '100%' },
        ],
        m: [
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularHeight', value: '48' },
            { prop: 'progressBarCircularStrokeSize', value: '2' },
            { prop: 'progressBarCircularWidth', value: '48' },
            { prop: 'width', value: '100%' },
            { prop: 'progressBarCircularContentStyle', value: 'body.m.normal' },
            { prop: 'progressBarCircularSize', value: '48' },
            { prop: 'progressBarCircularStrokeWidth', value: '2' },
            { prop: 'spinnerSize', value: '48' },
        ],
        s: [
            { prop: 'progressBarCircularContentStyle', value: 'body.s.normal' },
            { prop: 'progressBarCircularSize', value: '32' },
            { prop: 'progressBarCircularStrokeWidth', value: '2' },
            { prop: 'spinnerSize', value: '36' },
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularHeight', value: '36' },
            { prop: 'progressBarCircularStrokeSize', value: '2' },
            { prop: 'progressBarCircularWidth', value: '36' },
            { prop: 'width', value: '100%' },
        ],
        xs: [
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularContentStyle', value: 'body.xs.normal' },
            { prop: 'progressBarCircularSize', value: '24' },
            { prop: 'progressBarCircularStrokeWidth', value: '2' },
            { prop: 'spinnerSize', value: '24' },
            { prop: 'progressBarCircularHeight', value: '24' },
            { prop: 'progressBarCircularStrokeSize', value: '2' },
            { prop: 'progressBarCircularWidth', value: '24' },
            { prop: 'width', value: '100%' },
        ],
        xxs: [
            { prop: 'height', value: '100%' },
            { prop: 'progressBarCircularHeight', value: '16' },
            { prop: 'progressBarCircularStrokeSize', value: '2' },
            { prop: 'progressBarCircularWidth', value: '16' },
            { prop: 'width', value: '100%' },
            { prop: 'progressBarCircularContentStyle', value: 'body.xxs.normal' },
            { prop: 'progressBarCircularSize', value: '16' },
            { prop: 'progressBarCircularStrokeWidth', value: '2' },
            { prop: 'spinnerSize', value: '16' },
        ],
    },
};
