import * as schema from '../../schema';

export async function seedPropertyVariations(
    db: any,
    ctx: {
        properties: Record<string, any>;
        variations: Record<string, any>;
    },
) {
    const p = ctx.properties;
    const v = ctx.variations;

    const rows = await db
        .insert(schema.propertyVariations)
        .values([
            // ── IconButton ──────────────────────────────────────────────────────────
            // View
            { propertyId: p.ib_backgroundColor.id, variationId: v.iconButtonView.id },
            { propertyId: p.ib_loadingBackgroundColor.id, variationId: v.iconButtonView.id },
            { propertyId: p.ib_iconColor.id, variationId: v.iconButtonView.id },
            { propertyId: p.ib_spinnerColor.id, variationId: v.iconButtonView.id },
            // Size
            { propertyId: p.ib_height.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_paddingStart.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_paddingEnd.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_minWidth.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_iconSize.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_spinnerSize.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_spinnerStrokeWidth.id, variationId: v.iconButtonSize.id },
            { propertyId: p.ib_shape.id, variationId: v.iconButtonSize.id },
            // Shape
            { propertyId: p.ib_shape.id, variationId: v.iconButtonShape.id },

            // ── Button ──────────────────────────────────────────────────────────────
            // View
            { propertyId: p.btn_backgroundColor.id, variationId: v.buttonView.id },
            { propertyId: p.btn_loadingBackgroundColor.id, variationId: v.buttonView.id },
            { propertyId: p.btn_labelColor.id, variationId: v.buttonView.id },
            { propertyId: p.btn_iconColor.id, variationId: v.buttonView.id },
            { propertyId: p.btn_spinnerColor.id, variationId: v.buttonView.id },
            { propertyId: p.btn_valueColor.id, variationId: v.buttonView.id },
            // Size
            { propertyId: p.btn_shape.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_height.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_paddingStart.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_paddingEnd.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_minWidth.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_iconSize.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_spinnerSize.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_spinnerStrokeWidth.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_iconMargin.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_valueMargin.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_labelStyle.id, variationId: v.buttonSize.id },
            { propertyId: p.btn_valueStyle.id, variationId: v.buttonSize.id },
            // Shape
            { propertyId: p.btn_shape.id, variationId: v.buttonShape.id },

            // ── Link ────────────────────────────────────────────────────────────────
            // View
            { propertyId: p.link_textColor.id, variationId: v.linkView.id },
            { propertyId: p.link_textColorVisited.id, variationId: v.linkView.id },
            { propertyId: p.link_underlineBorderWidth.id, variationId: v.linkView.id },
            // Size
            { propertyId: p.link_textStyle.id, variationId: v.linkSize.id },

            // ── Checkbox ──────────────────────────────────────────────────────────────
            // View
            { propertyId: p.cb_toggleCheckedBackgroundColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_iconColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_labelColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_descriptionColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_toggleBackgroundColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_toggleCheckedBorderColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_toggleBorderColor.id, variationId: v.checkboxView.id },
            { propertyId: p.cb_toggleIndeterminateIconColor.id, variationId: v.checkboxView.id },
            // Size
            { propertyId: p.cb_margin.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_togglePadding.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleShape.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleBorderWidth.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleCheckedBorderWidth.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleWidth.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleHeight.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleCheckedIconWidth.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleCheckedIconHeight.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleIndeterminateIconWidth.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_toggleIndeterminateIconHeight.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_horizontalPadding.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_verticalPadding.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_descriptionPadding.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_labelStyle.id, variationId: v.checkboxSize.id },
            { propertyId: p.cb_descriptionStyle.id, variationId: v.checkboxSize.id },

            // ── Radiobox ──────────────────────────────────────────────────────────────
            // View
            { propertyId: p.rb_toggleCheckedBackgroundColor.id, variationId: v.radioboxView.id },
            { propertyId: p.rb_ellipseColor.id, variationId: v.radioboxView.id },
            { propertyId: p.rb_labelColor.id, variationId: v.radioboxView.id },
            { propertyId: p.rb_descriptionColor.id, variationId: v.radioboxView.id },
            { propertyId: p.rb_toggleBackgroundColor.id, variationId: v.radioboxView.id },
            { propertyId: p.rb_toggleCheckedBorderColor.id, variationId: v.radioboxView.id },
            { propertyId: p.rb_toggleBorderColor.id, variationId: v.radioboxView.id },
            // Size
            { propertyId: p.rb_margin.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_togglePadding.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleShape.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleBorderWidth.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleCheckedBorderWidth.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleWidth.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleHeight.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_ellipseWidth.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_ellipseHeight.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleCheckedIconWidth.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_toggleCheckedIconHeight.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_horizontalPadding.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_verticalPadding.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_descriptionPadding.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_labelStyle.id, variationId: v.radioboxSize.id },
            { propertyId: p.rb_descriptionStyle.id, variationId: v.radioboxSize.id },

            // ── Counter ──────────────────────────────────────────────────────────
            { propertyId: p.cou_color.id, variationId: v.counterView.id },
            { propertyId: p.cou_background.id, variationId: v.counterView.id },
            { propertyId: p.cou_shape.id, variationId: v.counterSize.id },
            { propertyId: p.cou_height.id, variationId: v.counterSize.id },
            { propertyId: p.cou_padding.id, variationId: v.counterSize.id },
            { propertyId: p.cou_labelStyle.id, variationId: v.counterSize.id },

            // ── Indicator ──────────────────────────────────────────────────────────
            { propertyId: p.ind_size.id, variationId: v.indicatorSize.id },
            { propertyId: p.ind_color.id, variationId: v.indicatorView.id },

            // ── Badge ──────────────────────────────────────────────────────────
            { propertyId: p.bad_background.id, variationId: v.badgeView.id },
            { propertyId: p.bad_color.id, variationId: v.badgeView.id },
            { propertyId: p.bad_colorTransparent.id, variationId: v.badgeView.id },
            { propertyId: p.bad_backgroundTransparent.id, variationId: v.badgeView.id },
            { propertyId: p.bad_colorClear.id, variationId: v.badgeView.id },
            { propertyId: p.bad_shape.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_height.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_padding.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_paddingIconOnly.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_textStyle.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_leftContentMarginLeft.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_leftContentMarginRight.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_rightContentMarginLeft.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_rightContentMarginRight.id, variationId: v.badgeSize.id },
            { propertyId: p.bad_shape.id, variationId: v.badgeShape.id },

            // ── Spinner ──────────────────────────────────────────────────────────
            { propertyId: p.spi_size.id, variationId: v.spinnerSize.id },
            { propertyId: p.spi_color.id, variationId: v.spinnerView.id },

            // ── Chip ──────────────────────────────────────────────────────────
            { propertyId: p.chi_color.id, variationId: v.chipView.id },
            { propertyId: p.chi_background.id, variationId: v.chipView.id },
            { propertyId: p.chi_backgroundReadOnly.id, variationId: v.chipView.id },
            { propertyId: p.chi_colorReadOnly.id, variationId: v.chipView.id },
            { propertyId: p.chi_closeIconColor.id, variationId: v.chipView.id },
            { propertyId: p.chi_leftContentColor.id, variationId: v.chipView.id },
            { propertyId: p.chi_width.id, variationId: v.chipSize.id },
            { propertyId: p.chi_height.id, variationId: v.chipSize.id },
            { propertyId: p.chi_padding.id, variationId: v.chipSize.id },
            { propertyId: p.chi_textStyle.id, variationId: v.chipSize.id },
            { propertyId: p.chi_closeIconSize.id, variationId: v.chipSize.id },
            { propertyId: p.chi_clearContentMarginLeft.id, variationId: v.chipSize.id },
            { propertyId: p.chi_clearContentMarginRight.id, variationId: v.chipSize.id },
            { propertyId: p.chi_leftContentMarginRight.id, variationId: v.chipSize.id },
            { propertyId: p.chi_rightContentMarginRight.id, variationId: v.chipSize.id },
            { propertyId: p.chi_leftContentMarginLeft.id, variationId: v.chipSize.id },
            { propertyId: p.chi_rightContentMarginLeft.id, variationId: v.chipSize.id },
            { propertyId: p.chi_shape.id, variationId: v.chipSize.id },
            { propertyId: p.chi_outlineSize.id, variationId: v.chipSize.id },
            { propertyId: p.chi_shape.id, variationId: v.chipShape.id },

            // ── Switch ──────────────────────────────────────────────────────────
            { propertyId: p.swi_textStyle.id, variationId: v.switchComponentSize.id },
            { propertyId: p.swi_descriptionStyle.id, variationId: v.switchComponentSize.id },
            { propertyId: p.swi_verticalGap.id, variationId: v.switchComponentSize.id },
            { propertyId: p.swi_labelOffset.id, variationId: v.switchComponentSize.id },
            { propertyId: p.swi_trackWidth.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_trackHeight.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_trackBorderRadius.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_thumbSize.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_thumbBorderRadius.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_thumbOffsetOn.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_thumbOffsetOff.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_thumbPressScale.id, variationId: v.switchComponentToggleSize.id },
            { propertyId: p.swi_labelColor.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_descriptionColor.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_descriptionMaxLines.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_trackBackgroundColorOff.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_trackBackgroundColorOn.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_trackBorderWidthOn.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_trackBorderWidthOff.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_thumbBackgroundColorOn.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_thumbBackgroundColorOff.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_trackBorderColorOn.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_trackBorderColorOff.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_thumbBorderColorOff.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_thumbBorderColorOn.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_thumbBoxShadow.id, variationId: v.switchComponentView.id },
            { propertyId: p.swi_thumbBorderWidth.id, variationId: v.switchComponentToggleSize.id },

            // ── Skeleton ──────────────────────────────────────────────────────────
            { propertyId: p.ske_fadeOutColor.id, variationId: v.skeletonView.id },
            { propertyId: p.ske_fadeInColor.id, variationId: v.skeletonView.id },
            { propertyId: p.ske_lineHeight.id, variationId: v.skeletonSize.id },
            { propertyId: p.ske_visibleLineHeight.id, variationId: v.skeletonSize.id },

            // ── List ──────────────────────────────────────────────────────────
            { propertyId: p.lis_listItemColor.id, variationId: v.listView.id },
            { propertyId: p.lis_listItemBackground.id, variationId: v.listView.id },
            { propertyId: p.lis_listItemBorderColor.id, variationId: v.listView.id },
            { propertyId: p.lis_listGap.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemPaddingRight.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemPaddingBottom.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemPaddingLeft.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemPaddingTop.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemBorderRadius.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemBorderWidth.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemGap.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemTightDifference.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemStyle.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemDividerWidth.id, variationId: v.listSize.id },
            { propertyId: p.lis_listBackground.id, variationId: v.listView.id },
            { propertyId: p.lis_listPadding.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemDividerColor.id, variationId: v.listView.id },
            { propertyId: p.lis_listBorderRadius.id, variationId: v.listSize.id },
            { propertyId: p.lis_listItemContentPadding.id, variationId: v.listSize.id },

            // ── LinkButton ──────────────────────────────────────────────────────────
            { propertyId: p.lin_linkButtonColor.id, variationId: v.linkButtonView.id },
            { propertyId: p.lin_linkButtonTextColor.id, variationId: v.linkButtonView.id },
            { propertyId: p.lin_linkButtonIconColor.id, variationId: v.linkButtonView.id },
            { propertyId: p.lin_linkButtonBackgroundColor.id, variationId: v.linkButtonView.id },
            { propertyId: p.lin_linkButtonHeight.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonPadding.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonRadius.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_textStyle.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonSpinnerSize.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonTextPadding.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonLeftContentMargin.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonRightContentMargin.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonAdditionalContentMargin.id, variationId: v.linkButtonSize.id },
            { propertyId: p.lin_linkButtonSpinnerColor.id, variationId: v.linkButtonView.id },

            // ── EmbedIconButton ──────────────────────────────────────────────────────────
            { propertyId: p.emb_embedIconButtonColor.id, variationId: v.embedIconButtonView.id },
            { propertyId: p.emb_embedIconButtonBackgroundColor.id, variationId: v.embedIconButtonView.id },
            { propertyId: p.emb_embedIconButtonLoadingBackgroundColor.id, variationId: v.embedIconButtonView.id },
            { propertyId: p.emb_textStyle.id, variationId: v.embedIconButtonSize.id },
            { propertyId: p.emb_embedIconButtonHeight.id, variationId: v.embedIconButtonSize.id },
            { propertyId: p.emb_embedIconButtonPadding.id, variationId: v.embedIconButtonSize.id },
            { propertyId: p.emb_embedIconButtonRadius.id, variationId: v.embedIconButtonSize.id },
            { propertyId: p.emb_embedIconButtonSpinnerSize.id, variationId: v.embedIconButtonSize.id },
            { propertyId: p.emb_embedIconButtonSpinnerColor.id, variationId: v.embedIconButtonView.id },
            { propertyId: p.emb_embedIconButtonWidth.id, variationId: v.embedIconButtonSize.id },

            // ── Cell ──────────────────────────────────────────────────────────
            { propertyId: p.cel_cellColor.id, variationId: v.cellView.id },
            { propertyId: p.cel_cellLabelColor.id, variationId: v.cellView.id },
            { propertyId: p.cel_cellTitleColor.id, variationId: v.cellView.id },
            { propertyId: p.cel_cellBackgroundColor.id, variationId: v.cellView.id },
            { propertyId: p.cel_cellSubtitleColor.id, variationId: v.cellView.id },
            { propertyId: p.cel_cellPaddingLeftContent.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellPadding.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellWidth.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellPaddingContent.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellPaddingRightContent.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellTextboxGap.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellGap.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellLabelStyle.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellTitleStyle.id, variationId: v.cellSize.id },
            { propertyId: p.cel_cellSubtitleStyle.id, variationId: v.cellSize.id },

            // ── Divider ──────────────────────────────────────────────────────────
            { propertyId: p.div_background.id, variationId: v.dividerView.id },
            { propertyId: p.div_baseSideSize.id, variationId: v.dividerOrientation.id },
            { propertyId: p.div_borderRadius.id, variationId: v.dividerSize.id },

            // ── EmptyState ──────────────────────────────────────────────────────────
            { propertyId: p.emp_borderRadius.id, variationId: v.emptyStateSize.id },
            { propertyId: p.emp_buttonHeight.id, variationId: v.emptyStateSize.id },
            { propertyId: p.emp_buttonMargin.id, variationId: v.emptyStateSize.id },
            { propertyId: p.emp_descriptionMargin.id, variationId: v.emptyStateSize.id },
            { propertyId: p.emp_iconMargin.id, variationId: v.emptyStateSize.id },
            { propertyId: p.emp_padding.id, variationId: v.emptyStateSize.id },
            { propertyId: p.emp_textStyle.id, variationId: v.emptyStateSize.id },

            // ── Accordion ──────────────────────────────────────────────────────────
            { propertyId: p.acc_accordionItemGap.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionWidth.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemBackground.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemTitleColor.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemTextColor.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemIconColor.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemFocus.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionBackground.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemBorderBottom.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemPaddingVertical.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemPaddingHorizontal.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemGap.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemBorderRadius.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemTextStyle.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemTitleStyle.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemViewBorderRadius.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemHeaderLeftGapDefault.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemHeaderLeftGapClear.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemHeaderLeftGap.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemShadow.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemOpenedTitleColor.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionGap.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemBodyPaddingBottom.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemBorder.id, variationId: v.accordionView.id },
            { propertyId: p.acc_accordionItemIconSize.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemPadding.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemPaddingHorizontalLeft.id, variationId: v.accordionSize.id },
            { propertyId: p.acc_accordionItemPadding.id, variationId: v.accordionView.id },

            // ── Slider ──────────────────────────────────────────────────────────
            { propertyId: p.sli_labelColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_rangeValueColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_thumbBorderColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_thumbBackgroundColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_thumbFocusBorderColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_railBackgroundColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_fillColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_tickDotColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_tickDotFilledColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldCaretColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldPlaceholderColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_doubleWrapperGap.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_labelWrapperMarginRight.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_labelStyle.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_rangeValueHorizontalMargin.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_rangeValueVerticalMargin.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_railThickness.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_railBorderRadius.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFieldPadding.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFieldStyle.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_thumbBorderWidth.id, variationId: v.sliderPointerSize.id },
            { propertyId: p.sli_textFieldBorderColorFocus.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldBackgroundColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_size.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_labelWrapperMarginBottom.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_labelWrapperVerticalMargin.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_valueStyle.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_rangeValueHorizontalOffset.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_currentValueTopOffset.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFieldHeight.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_thumbSize.id, variationId: v.sliderPointerSize.id },
            { propertyId: p.sli_textFieldBorderColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldWebClipPath.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFieldWebMarginRight.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFiledFocusColor.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldBackgroundColorFocus.id, variationId: v.sliderView.id },
            { propertyId: p.sli_labelWrapperGap.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_labelWrapperOnlyIconMarginRight.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_rangeValueBottomOffset.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_tickSize.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFieldWrapperGap.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_textFieldBorderRadius.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_thumbBorderStyle.id, variationId: v.sliderPointerSize.id },
            { propertyId: p.sli_textFieldBorderWidth.id, variationId: v.sliderSize.id },
            { propertyId: p.sli_doubleBoxShadow.id, variationId: v.sliderView.id },
            { propertyId: p.sli_textFieldWebReversedClipPath.id, variationId: v.sliderSize.id },

            // ── Note ──────────────────────────────────────────────────────────
            { propertyId: p.not_background.id, variationId: v.noteView.id },
            { propertyId: p.not_color.id, variationId: v.noteView.id },
            { propertyId: p.not_actionContentMargin.id, variationId: v.noteSize.id },
            { propertyId: p.not_borderRadius.id, variationId: v.noteSize.id },
            { propertyId: p.not_closeIconButtonSize.id, variationId: v.noteSize.id },
            { propertyId: p.not_closeIconMargin.id, variationId: v.noteSize.id },
            { propertyId: p.not_closeIconRight.id, variationId: v.noteSize.id },
            { propertyId: p.not_closeIconSize.id, variationId: v.noteSize.id },
            { propertyId: p.not_closeIconTop.id, variationId: v.noteSize.id },
            { propertyId: p.not_contentGap.id, variationId: v.noteSize.id },
            { propertyId: p.not_fixedContentBeforeHeight.id, variationId: v.noteSize.id },
            { propertyId: p.not_fixedContentBeforePadding.id, variationId: v.noteSize.id },
            { propertyId: p.not_fixedContentBeforeWidth.id, variationId: v.noteSize.id },
            { propertyId: p.not_gapScalable.id, variationId: v.noteSize.id },
            { propertyId: p.not_gap.id, variationId: v.noteSize.id },
            { propertyId: p.not_contentBeforeColor.id, variationId: v.noteView.id },
            { propertyId: p.not_closeIconColor.id, variationId: v.noteSize.id },
            { propertyId: p.not_padding.id, variationId: v.noteSize.id },
            { propertyId: p.not_paddingBottomWithActionContent.id, variationId: v.noteSize.id },
            { propertyId: p.not_paddingScalable.id, variationId: v.noteSize.id },
            { propertyId: p.not_textStyle.id, variationId: v.noteSize.id },
            { propertyId: p.not_titlePaddingRight.id, variationId: v.noteSize.id },
            { propertyId: p.not_titleStyle.id, variationId: v.noteSize.id },
        ])
        .onConflictDoNothing()
        .returning();

    console.log(`  property_variations: ${rows.length} rows`);
}
