import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        clear: [
            { prop: 'itemColor', token: 'text.default.secondary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.primary-hover' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemAdditionalColor', token: 'text.default.tertiary' },
            { prop: 'itemAdditionalColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedColor', token: 'text.default.primary-hover' },
            { prop: 'itemSelectedBackgroundColor', value: 'transparent' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColorHover', value: 'transparent' },
            { prop: 'itemSelectedAdditionalColor', token: 'text.default.secondary' },
            { prop: 'itemSelectedAdditionalColorHover', token: 'text.default.secondary' },
            { prop: 'outlineFocusColor', token: 'text.default.accent' },
        ],
        secondary: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.primary-hover' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemAdditionalColor', token: 'text.default.secondary' },
            { prop: 'itemAdditionalColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedColor', token: 'text.default.primary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.transparent-card' },
            { prop: 'itemSelectedColorHover', token: 'text.default.primary-hover' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.transparent-card' },
            { prop: 'itemSelectedAdditionalColor', token: 'text.default.secondary' },
            { prop: 'itemSelectedAdditionalColorHover', token: 'text.default.secondary' },
            { prop: 'outlineFocusColor', token: 'text.default.accent' },
        ],
        default: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.primary-hover' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemAdditionalColor', token: 'text.default.secondary' },
            { prop: 'itemAdditionalColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedColor', token: 'text.inverse.primary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'itemSelectedColorHover', token: 'text.inverse.primary-hover' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.solid-default' },
            { prop: 'itemSelectedAdditionalColor', token: 'text.inverse.secondary' },
            { prop: 'itemSelectedAdditionalColorHover', token: 'text.inverse.secondary' },
            { prop: 'outlineFocusColor', token: 'text.default.accent' },
        ],
        accent: [
            { prop: 'itemColor', token: 'text.default.primary' },
            { prop: 'itemBackgroundColor', value: 'transparent' },
            { prop: 'itemColorHover', token: 'text.default.primary-hover' },
            { prop: 'itemBackgroundColorHover', value: 'transparent' },
            { prop: 'itemAdditionalColor', token: 'text.default.secondary' },
            { prop: 'itemAdditionalColorHover', token: 'text.default.secondary' },
            { prop: 'itemSelectedColor', token: 'text.on-dark.primary' },
            { prop: 'itemSelectedBackgroundColor', token: 'surface.default.accent' },
            { prop: 'itemSelectedColorHover', token: 'text.on-dark.primary-hover' },
            { prop: 'itemSelectedBackgroundColorHover', token: 'surface.default.accent' },
            { prop: 'itemSelectedAdditionalColor', token: 'text.on-dark.secondary' },
            { prop: 'itemSelectedAdditionalColorHover', token: 'text.on-dark.secondary' },
            { prop: 'outlineFocusColor', token: 'text.default.accent' },
        ],
    },
    size: {
        xs: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemPilledPadding', value: '0.5rem 0.5rem' },
            { prop: 'itemContentPadding', value: '0.0625rem 0.125rem' },
            { prop: 'itemHeight', value: '32' },
            { prop: 'itemIconMargin', value: '2' },
            { prop: 'itemMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.xs.bold' },
            { prop: 'itemBorderRadius', value: '8' },
            { prop: 'itemPadding', value: '12', adjust: [{ platform: 'web', param: 'itemPadding', template: '0.5rem $1' }] },
        ],
        s: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemPilledPadding', value: '0.5rem 0.5rem' },
            { prop: 'itemContentPadding', value: '0.1875rem 0.125rem' },
            { prop: 'itemHeight', value: '40' },
            { prop: 'itemIconMargin', value: '2' },
            { prop: 'itemMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.s.bold' },
            { prop: 'itemBorderRadius', value: '10' },
            { prop: 'itemPadding', value: '16', adjust: [{ platform: 'web', param: 'itemPadding', template: '0.5rem $1' }] },
        ],
        m: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemContentPadding', value: '0.125rem' },
            { prop: 'itemPilledPadding', value: '0.75rem 0.75rem' },
            { prop: 'itemHeight', value: '48' },
            { prop: 'itemIconMargin', value: '4' },
            { prop: 'itemMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.m.bold' },
            { prop: 'itemBorderRadius', value: '12' },
            { prop: 'itemPadding', value: '20', adjust: [{ platform: 'web', param: 'itemPadding', template: '0.5rem $1' }] },
        ],
        l: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemPilledPadding', value: '1rem 1rem' },
            { prop: 'itemContentPadding', value: '0.0625rem 0.125rem' },
            { prop: 'itemHeight', value: '56' },
            { prop: 'itemIconMargin', value: '6' },
            { prop: 'itemMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.l.bold' },
            { prop: 'itemBorderRadius', value: '14' },
            { prop: 'itemPadding', value: '24', adjust: [{ platform: 'web', param: 'itemPadding', template: '0.5rem $1' }] },
        ],
        xl: [
            { prop: 'itemWidth', value: 'auto' },
            { prop: 'itemPilledPadding', value: '1.25rem' },
            { prop: 'itemContentPadding', value: '0.0625rem 0.125rem' },
            { prop: 'itemHeight', value: '64' },
            { prop: 'itemIconMargin', value: '6' },
            { prop: 'itemMarginLeft', value: '0' },
            { prop: 'textStyle', value: 'body.l.bold' },
            { prop: 'itemBorderRadius', value: '16' },
            { prop: 'itemPadding', value: '28', adjust: [{ platform: 'web', param: 'itemPadding', template: '0.5rem $1' }] },
        ],
    },
    pilled: {
        true: [
            { prop: 'itemPilledBorderRadius', token: 'round.circle' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledOpacity', value: '0.4' },
];
