import type { ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'helperTextColor', token: 'text.default.secondary' },
            { prop: 'outlineIconColor', token: 'text.default.primary' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'iconColor', token: 'text.default.primary' },
        ],
        accent: [
            { prop: 'helperTextColor', token: 'text.default.secondary' },
            { prop: 'outlineIconColor', token: 'text.default.tertiary' },
            { prop: 'color', token: 'text.default.primary' },
            { prop: 'iconColor', value: '#F3A912' },
        ],
    },
    size: {
        xs: [
            { prop: 'actualIconSize', value: '16' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '2' },
            { prop: 'scaleFactor', value: '0.75' },
            { prop: 'singleIconMarginBottom', value: '2' },
            { prop: 'textStyle', value: 'body.xs.bold' },
            { prop: 'contentGap', value: '6' },
            { prop: 'helperTextStyle', value: 'body.xxs.normal' },
            { prop: 'iconSize', value: '12' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'starsWrapperGap', value: '2' },
        ],
        xxs: [
            { prop: 'contentGap', value: '6' },
            { prop: 'helperTextStyle', value: 'body.xxs.normal' },
            { prop: 'scaleFactor', value: '0.75' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'actualIconSize', value: '16' },
            { prop: 'gap', value: '4' },
            { prop: 'iconSize', value: '12' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'textStyle', value: 'body.xxs.bold' },
        ],
        h1: [
            { prop: 'contentGap', value: '16' },
            { prop: 'helperTextStyle', value: 'body.m.normal' },
            { prop: 'singleIconContentGap', value: '8' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '4' },
            { prop: 'singleIconMarginBottom', value: '4' },
            { prop: 'textStyle', value: 'header.h1.bold' },
        ],
        h2: [
            { prop: 'contentGap', value: '14' },
            { prop: 'helperTextStyle', value: 'body.s.normal' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '4' },
            { prop: 'singleIconMarginBottom', value: '4' },
            { prop: 'textStyle', value: 'header.h2.bold' },
            { prop: 'singleIconContentGap', value: '8' },
            { prop: 'starsWrapperGap', value: '2' },
        ],
        h3: [
            { prop: 'contentGap', value: '12' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '6' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '2' },
            { prop: 'singleIconMarginBottom', value: '2' },
            { prop: 'textStyle', value: 'header.h3.bold' },
        ],
        h4: [
            { prop: 'contentGap', value: '10' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '2' },
            { prop: 'singleIconMarginBottom', value: '2' },
            { prop: 'textStyle', value: 'header.h4.bold' },
        ],
        h5: [
            { prop: 'contentGap', value: '10' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '2' },
            { prop: 'singleIconMarginBottom', value: '2' },
            { prop: 'textStyle', value: 'header.h5.bold' },
        ],
        h6: [
            { prop: 'contentGap', value: '10' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'gap', value: '4' },
            { prop: 'iconMarginBottom', value: '2' },
            { prop: 'singleIconMarginBottom', value: '2' },
            { prop: 'textStyle', value: 'header.h6.bold' },
        ],
        displayL: [
            { prop: 'contentGap', value: '24' },
            { prop: 'helperTextStyle', value: 'header.h3.normal' },
            { prop: 'singleIconMarginBottom', value: '8' },
            { prop: 'textStyle', value: 'display.l.bold' },
            { prop: 'gap', value: '6' },
            { prop: 'singleIconContentGap', value: '12' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'wrapperGap', value: '10' },
        ],
        displayM: [
            { prop: 'contentGap', value: '24' },
            { prop: 'helperTextStyle', value: 'body.l.normal' },
            { prop: 'singleIconMarginBottom', value: '8' },
            { prop: 'textStyle', value: 'display.m.bold' },
            { prop: 'gap', value: '6' },
            { prop: 'singleIconContentGap', value: '12' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'wrapperGap', value: '8' },
        ],
        displayS: [
            { prop: 'contentGap', value: '24' },
            { prop: 'helperTextStyle', value: 'body.l.normal' },
            { prop: 'singleIconMarginBottom', value: '5.008' },
            { prop: 'textStyle', value: 'display.s.bold' },
            { prop: 'gap', value: '6' },
            { prop: 'singleIconContentGap', value: '12' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'wrapperGap', value: '6' },
        ],
        l: [
            { prop: 'gap', value: '4' },
            { prop: 'iconSize', value: '20' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'contentGap', value: '10' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'textStyle', value: 'body.l.bold' },
        ],
        m: [
            { prop: 'contentGap', value: '8' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'textStyle', value: 'body.m.bold' },
            { prop: 'gap', value: '4' },
            { prop: 'iconSize', value: '20' },
            { prop: 'starsWrapperGap', value: '2' },
        ],
        s: [
            { prop: 'gap', value: '4' },
            { prop: 'iconSize', value: '16' },
            { prop: 'starsWrapperGap', value: '2' },
            { prop: 'contentGap', value: '8' },
            { prop: 'helperTextStyle', value: 'body.xs.normal' },
            { prop: 'singleIconContentGap', value: '4' },
            { prop: 'textStyle', value: 'body.s.bold' },
        ],
    },
};
