import { TokenType } from '../../../types';

export const typographyTokens: Array<TokenType> = [
    {
        type: 'typography',
        name: 'screen-s.display.l.normal',
        tags: ['screen-s', 'display', 'l', 'normal'],
        displayName: 'displayL N',
        description: 'typography s display-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.l.bold',
        tags: ['screen-s', 'display', 'l', 'bold'],
        displayName: 'displayL B',
        description: 'typography s display-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.l.medium',
        tags: ['screen-s', 'display', 'l', 'medium'],
        displayName: 'displayL M',
        description: 'typography s display-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.m.normal',
        tags: ['screen-s', 'display', 'm', 'normal'],
        displayName: 'displayM N',
        description: 'typography s display-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.m.bold',
        tags: ['screen-s', 'display', 'm', 'bold'],
        displayName: 'displayM B',
        description: 'typography s display-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.m.medium',
        tags: ['screen-s', 'display', 'm', 'medium'],
        displayName: 'displayM M',
        description: 'typography s display-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.s.normal',
        tags: ['screen-s', 'display', 's', 'normal'],
        displayName: 'displayS N',
        description: 'typography s display-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.s.bold',
        tags: ['screen-s', 'display', 's', 'bold'],
        displayName: 'displayS B',
        description: 'typography s display-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.display.s.medium',
        tags: ['screen-s', 'display', 's', 'medium'],
        displayName: 'displayS M',
        description: 'typography s display-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h1.normal',
        tags: ['screen-s', 'header', 'h1', 'normal'],
        displayName: 'headerH1 N',
        description: 'typography s header-h1',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h1.bold',
        tags: ['screen-s', 'header', 'h1', 'bold'],
        displayName: 'headerH1 B',
        description: 'typography s header-h1-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h1.medium',
        tags: ['screen-s', 'header', 'h1', 'medium'],
        displayName: 'headerH1 M',
        description: 'typography s header-h1-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h2.normal',
        tags: ['screen-s', 'header', 'h2', 'normal'],
        displayName: 'headerH2 N',
        description: 'typography s header-h2',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h2.bold',
        tags: ['screen-s', 'header', 'h2', 'bold'],
        displayName: 'headerH2 B',
        description: 'typography s header-h2-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h2.medium',
        tags: ['screen-s', 'header', 'h2', 'medium'],
        displayName: 'headerH2 M',
        description: 'typography s header-h2-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h3.normal',
        tags: ['screen-s', 'header', 'h3', 'normal'],
        displayName: 'headerH3 N',
        description: 'typography s header-h3',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h3.bold',
        tags: ['screen-s', 'header', 'h3', 'bold'],
        displayName: 'headerH3 B',
        description: 'typography s header-h3-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h3.medium',
        tags: ['screen-s', 'header', 'h3', 'medium'],
        displayName: 'headerH3 M',
        description: 'typography s header-h3-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h4.normal',
        tags: ['screen-s', 'header', 'h4', 'normal'],
        displayName: 'headerH4 N',
        description: 'typography s header-h4',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h4.bold',
        tags: ['screen-s', 'header', 'h4', 'bold'],
        displayName: 'headerH4 B',
        description: 'typography s header-h4-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h4.medium',
        tags: ['screen-s', 'header', 'h4', 'medium'],
        displayName: 'headerH4 M',
        description: 'typography s header-h4-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h5.normal',
        tags: ['screen-s', 'header', 'h5', 'normal'],
        displayName: 'headerH5 N',
        description: 'typography s header-h5',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h5.bold',
        tags: ['screen-s', 'header', 'h5', 'bold'],
        displayName: 'headerH5 B',
        description: 'typography s header-h5-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.header.h5.medium',
        tags: ['screen-s', 'header', 'h5', 'medium'],
        displayName: 'headerH5 M',
        description: 'typography s header-h5-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.l.normal',
        tags: ['screen-s', 'body', 'l', 'normal'],
        displayName: 'bodyL N',
        description: 'typography s body-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.l.bold',
        tags: ['screen-s', 'body', 'l', 'bold'],
        displayName: 'bodyL B',
        description: 'typography s body-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.l.medium',
        tags: ['screen-s', 'body', 'l', 'medium'],
        displayName: 'bodyL M',
        description: 'typography s body-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.m.normal',
        tags: ['screen-s', 'body', 'm', 'normal'],
        displayName: 'bodyM N',
        description: 'typography s body-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.m.bold',
        tags: ['screen-s', 'body', 'm', 'bold'],
        displayName: 'bodyM B',
        description: 'typography s body-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.m.medium',
        tags: ['screen-s', 'body', 'm', 'medium'],
        displayName: 'bodyM M',
        description: 'typography s body-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.s.normal',
        tags: ['screen-s', 'body', 's', 'normal'],
        displayName: 'bodyS N',
        description: 'typography s body-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.s.bold',
        tags: ['screen-s', 'body', 's', 'bold'],
        displayName: 'bodyS B',
        description: 'typography s body-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.s.medium',
        tags: ['screen-s', 'body', 's', 'medium'],
        displayName: 'bodyS M',
        description: 'typography s body-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xs.normal',
        tags: ['screen-s', 'body', 'xs', 'normal'],
        displayName: 'bodyXs N',
        description: 'typography s body-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xs.bold',
        tags: ['screen-s', 'body', 'xs', 'bold'],
        displayName: 'bodyXs B',
        description: 'typography s body-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xs.medium',
        tags: ['screen-s', 'body', 'xs', 'medium'],
        displayName: 'bodyXs M',
        description: 'typography s body-xs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xxs.normal',
        tags: ['screen-s', 'body', 'xxs', 'normal'],
        displayName: 'bodyXxs N',
        description: 'typography s body-xxs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xxs.bold',
        tags: ['screen-s', 'body', 'xxs', 'bold'],
        displayName: 'bodyXxs B',
        description: 'typography s body-xxs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.body.xxs.medium',
        tags: ['screen-s', 'body', 'xxs', 'medium'],
        displayName: 'bodyXxs M',
        description: 'typography s body-xxs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.l.normal',
        tags: ['screen-s', 'text', 'l', 'normal'],
        displayName: 'textL N',
        description: 'typography s text-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.l.bold',
        tags: ['screen-s', 'text', 'l', 'bold'],
        displayName: 'textL B',
        description: 'typography s text-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.l.medium',
        tags: ['screen-s', 'text', 'l', 'medium'],
        displayName: 'textL M',
        description: 'typography s text-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.m.normal',
        tags: ['screen-s', 'text', 'm', 'normal'],
        displayName: 'textM N',
        description: 'typography s text-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.m.bold',
        tags: ['screen-s', 'text', 'm', 'bold'],
        displayName: 'textM B',
        description: 'typography s text-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.m.medium',
        tags: ['screen-s', 'text', 'm', 'medium'],
        displayName: 'textM M',
        description: 'typography s text-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.s.normal',
        tags: ['screen-s', 'text', 's', 'normal'],
        displayName: 'textS N',
        description: 'typography s text-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.s.bold',
        tags: ['screen-s', 'text', 's', 'bold'],
        displayName: 'textS B',
        description: 'typography s text-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.s.medium',
        tags: ['screen-s', 'text', 's', 'medium'],
        displayName: 'textS M',
        description: 'typography s text-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.xs.normal',
        tags: ['screen-s', 'text', 'xs', 'normal'],
        displayName: 'textXs N',
        description: 'typography s text-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.xs.bold',
        tags: ['screen-s', 'text', 'xs', 'bold'],
        displayName: 'textXs B',
        description: 'typography s text-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-s.text.xs.medium',
        tags: ['screen-s', 'text', 'xs', 'medium'],
        displayName: 'textXs M',
        description: 'typography s text-xs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.l.normal',
        tags: ['screen-m', 'display', 'l', 'normal'],
        displayName: 'displayL N',
        description: 'typography m display-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.l.bold',
        tags: ['screen-m', 'display', 'l', 'bold'],
        displayName: 'displayL B',
        description: 'typography m display-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.l.medium',
        tags: ['screen-m', 'display', 'l', 'medium'],
        displayName: 'displayL M',
        description: 'typography m display-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.m.normal',
        tags: ['screen-m', 'display', 'm', 'normal'],
        displayName: 'displayM N',
        description: 'typography m display-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.m.bold',
        tags: ['screen-m', 'display', 'm', 'bold'],
        displayName: 'displayM B',
        description: 'typography m display-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.m.medium',
        tags: ['screen-m', 'display', 'm', 'medium'],
        displayName: 'displayM M',
        description: 'typography m display-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.s.normal',
        tags: ['screen-m', 'display', 's', 'normal'],
        displayName: 'displayS N',
        description: 'typography m display-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.s.bold',
        tags: ['screen-m', 'display', 's', 'bold'],
        displayName: 'displayS B',
        description: 'typography m display-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.display.s.medium',
        tags: ['screen-m', 'display', 's', 'medium'],
        displayName: 'displayS M',
        description: 'typography m display-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h1.normal',
        tags: ['screen-m', 'header', 'h1', 'normal'],
        displayName: 'headerH1 N',
        description: 'typography m header-h1',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h1.bold',
        tags: ['screen-m', 'header', 'h1', 'bold'],
        displayName: 'headerH1 B',
        description: 'typography m header-h1-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h1.medium',
        tags: ['screen-m', 'header', 'h1', 'medium'],
        displayName: 'headerH1 M',
        description: 'typography m header-h1-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h2.normal',
        tags: ['screen-m', 'header', 'h2', 'normal'],
        displayName: 'headerH2 N',
        description: 'typography m header-h2',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h2.bold',
        tags: ['screen-m', 'header', 'h2', 'bold'],
        displayName: 'headerH2 B',
        description: 'typography m header-h2-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h2.medium',
        tags: ['screen-m', 'header', 'h2', 'medium'],
        displayName: 'headerH2 M',
        description: 'typography m header-h2-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h3.normal',
        tags: ['screen-m', 'header', 'h3', 'normal'],
        displayName: 'headerH3 N',
        description: 'typography m header-h3',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h3.bold',
        tags: ['screen-m', 'header', 'h3', 'bold'],
        displayName: 'headerH3 B',
        description: 'typography m header-h3-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h3.medium',
        tags: ['screen-m', 'header', 'h3', 'medium'],
        displayName: 'headerH3 M',
        description: 'typography m header-h3-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h4.normal',
        tags: ['screen-m', 'header', 'h4', 'normal'],
        displayName: 'headerH4 N',
        description: 'typography m header-h4',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h4.bold',
        tags: ['screen-m', 'header', 'h4', 'bold'],
        displayName: 'headerH4 B',
        description: 'typography m header-h4-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h4.medium',
        tags: ['screen-m', 'header', 'h4', 'medium'],
        displayName: 'headerH4 M',
        description: 'typography m header-h4-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h5.normal',
        tags: ['screen-m', 'header', 'h5', 'normal'],
        displayName: 'headerH5 N',
        description: 'typography m header-h5',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h5.bold',
        tags: ['screen-m', 'header', 'h5', 'bold'],
        displayName: 'headerH5 B',
        description: 'typography m header-h5-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.header.h5.medium',
        tags: ['screen-m', 'header', 'h5', 'medium'],
        displayName: 'headerH5 M',
        description: 'typography m header-h5-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.l.normal',
        tags: ['screen-m', 'body', 'l', 'normal'],
        displayName: 'bodyL N',
        description: 'typography m body-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.l.bold',
        tags: ['screen-m', 'body', 'l', 'bold'],
        displayName: 'bodyL B',
        description: 'typography m body-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.l.medium',
        tags: ['screen-m', 'body', 'l', 'medium'],
        displayName: 'bodyL M',
        description: 'typography m body-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.m.normal',
        tags: ['screen-m', 'body', 'm', 'normal'],
        displayName: 'bodyM N',
        description: 'typography m body-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.m.bold',
        tags: ['screen-m', 'body', 'm', 'bold'],
        displayName: 'bodyM B',
        description: 'typography m body-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.m.medium',
        tags: ['screen-m', 'body', 'm', 'medium'],
        displayName: 'bodyM M',
        description: 'typography m body-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.s.normal',
        tags: ['screen-m', 'body', 's', 'normal'],
        displayName: 'bodyS N',
        description: 'typography m body-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.s.bold',
        tags: ['screen-m', 'body', 's', 'bold'],
        displayName: 'bodyS B',
        description: 'typography m body-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.s.medium',
        tags: ['screen-m', 'body', 's', 'medium'],
        displayName: 'bodyS M',
        description: 'typography m body-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xs.normal',
        tags: ['screen-m', 'body', 'xs', 'normal'],
        displayName: 'bodyXs N',
        description: 'typography m body-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xs.bold',
        tags: ['screen-m', 'body', 'xs', 'bold'],
        displayName: 'bodyXs B',
        description: 'typography m body-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xs.medium',
        tags: ['screen-m', 'body', 'xs', 'medium'],
        displayName: 'bodyXs M',
        description: 'typography m body-xs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xxs.normal',
        tags: ['screen-m', 'body', 'xxs', 'normal'],
        displayName: 'bodyXxs N',
        description: 'typography m body-xxs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xxs.bold',
        tags: ['screen-m', 'body', 'xxs', 'bold'],
        displayName: 'bodyXxs B',
        description: 'typography m body-xxs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.body.xxs.medium',
        tags: ['screen-m', 'body', 'xxs', 'medium'],
        displayName: 'bodyXxs M',
        description: 'typography m body-xxs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.l.normal',
        tags: ['screen-m', 'text', 'l', 'normal'],
        displayName: 'textL N',
        description: 'typography m text-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.l.bold',
        tags: ['screen-m', 'text', 'l', 'bold'],
        displayName: 'textL B',
        description: 'typography m text-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.l.medium',
        tags: ['screen-m', 'text', 'l', 'medium'],
        displayName: 'textL M',
        description: 'typography m text-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.m.normal',
        tags: ['screen-m', 'text', 'm', 'normal'],
        displayName: 'textM N',
        description: 'typography m text-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.m.bold',
        tags: ['screen-m', 'text', 'm', 'bold'],
        displayName: 'textM B',
        description: 'typography m text-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.m.medium',
        tags: ['screen-m', 'text', 'm', 'medium'],
        displayName: 'textM M',
        description: 'typography m text-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.s.normal',
        tags: ['screen-m', 'text', 's', 'normal'],
        displayName: 'textS N',
        description: 'typography m text-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.s.bold',
        tags: ['screen-m', 'text', 's', 'bold'],
        displayName: 'textS B',
        description: 'typography m text-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.s.medium',
        tags: ['screen-m', 'text', 's', 'medium'],
        displayName: 'textS M',
        description: 'typography m text-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.xs.normal',
        tags: ['screen-m', 'text', 'xs', 'normal'],
        displayName: 'textXs N',
        description: 'typography m text-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.xs.bold',
        tags: ['screen-m', 'text', 'xs', 'bold'],
        displayName: 'textXs B',
        description: 'typography m text-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-m.text.xs.medium',
        tags: ['screen-m', 'text', 'xs', 'medium'],
        displayName: 'textXs M',
        description: 'typography m text-xs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.l.normal',
        tags: ['screen-l', 'display', 'l', 'normal'],
        displayName: 'displayL N',
        description: 'typography l display-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.l.bold',
        tags: ['screen-l', 'display', 'l', 'bold'],
        displayName: 'displayL B',
        description: 'typography l display-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.l.medium',
        tags: ['screen-l', 'display', 'l', 'medium'],
        displayName: 'displayL M',
        description: 'typography l display-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.m.normal',
        tags: ['screen-l', 'display', 'm', 'normal'],
        displayName: 'displayM N',
        description: 'typography l display-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.m.bold',
        tags: ['screen-l', 'display', 'm', 'bold'],
        displayName: 'displayM B',
        description: 'typography l display-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.m.medium',
        tags: ['screen-l', 'display', 'm', 'medium'],
        displayName: 'displayM M',
        description: 'typography l display-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.s.normal',
        tags: ['screen-l', 'display', 's', 'normal'],
        displayName: 'displayS N',
        description: 'typography l display-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.s.bold',
        tags: ['screen-l', 'display', 's', 'bold'],
        displayName: 'displayS B',
        description: 'typography l display-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.display.s.medium',
        tags: ['screen-l', 'display', 's', 'medium'],
        displayName: 'displayS M',
        description: 'typography l display-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h1.normal',
        tags: ['screen-l', 'header', 'h1', 'normal'],
        displayName: 'headerH1 N',
        description: 'typography l header-h1',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h1.bold',
        tags: ['screen-l', 'header', 'h1', 'bold'],
        displayName: 'headerH1 B',
        description: 'typography l header-h1-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h1.medium',
        tags: ['screen-l', 'header', 'h1', 'medium'],
        displayName: 'headerH1 M',
        description: 'typography l header-h1-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h2.normal',
        tags: ['screen-l', 'header', 'h2', 'normal'],
        displayName: 'headerH2 N',
        description: 'typography l header-h2',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h2.bold',
        tags: ['screen-l', 'header', 'h2', 'bold'],
        displayName: 'headerH2 B',
        description: 'typography l header-h2-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h2.medium',
        tags: ['screen-l', 'header', 'h2', 'medium'],
        displayName: 'headerH2 M',
        description: 'typography l header-h2-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h3.normal',
        tags: ['screen-l', 'header', 'h3', 'normal'],
        displayName: 'headerH3 N',
        description: 'typography l header-h3',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h3.bold',
        tags: ['screen-l', 'header', 'h3', 'bold'],
        displayName: 'headerH3 B',
        description: 'typography l header-h3-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h3.medium',
        tags: ['screen-l', 'header', 'h3', 'medium'],
        displayName: 'headerH3 M',
        description: 'typography l header-h3-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h4.normal',
        tags: ['screen-l', 'header', 'h4', 'normal'],
        displayName: 'headerH4 N',
        description: 'typography l header-h4',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h4.bold',
        tags: ['screen-l', 'header', 'h4', 'bold'],
        displayName: 'headerH4 B',
        description: 'typography l header-h4-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h4.medium',
        tags: ['screen-l', 'header', 'h4', 'medium'],
        displayName: 'headerH4 M',
        description: 'typography l header-h4-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h5.normal',
        tags: ['screen-l', 'header', 'h5', 'normal'],
        displayName: 'headerH5 N',
        description: 'typography l header-h5',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h5.bold',
        tags: ['screen-l', 'header', 'h5', 'bold'],
        displayName: 'headerH5 B',
        description: 'typography l header-h5-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.header.h5.medium',
        tags: ['screen-l', 'header', 'h5', 'medium'],
        displayName: 'headerH5 M',
        description: 'typography l header-h5-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.l.normal',
        tags: ['screen-l', 'body', 'l', 'normal'],
        displayName: 'bodyL N',
        description: 'typography l body-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.l.bold',
        tags: ['screen-l', 'body', 'l', 'bold'],
        displayName: 'bodyL B',
        description: 'typography l body-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.l.medium',
        tags: ['screen-l', 'body', 'l', 'medium'],
        displayName: 'bodyL M',
        description: 'typography l body-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.m.normal',
        tags: ['screen-l', 'body', 'm', 'normal'],
        displayName: 'bodyM N',
        description: 'typography l body-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.m.bold',
        tags: ['screen-l', 'body', 'm', 'bold'],
        displayName: 'bodyM B',
        description: 'typography l body-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.m.medium',
        tags: ['screen-l', 'body', 'm', 'medium'],
        displayName: 'bodyM M',
        description: 'typography l body-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.s.normal',
        tags: ['screen-l', 'body', 's', 'normal'],
        displayName: 'bodyS N',
        description: 'typography l body-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.s.bold',
        tags: ['screen-l', 'body', 's', 'bold'],
        displayName: 'bodyS B',
        description: 'typography l body-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.s.medium',
        tags: ['screen-l', 'body', 's', 'medium'],
        displayName: 'bodyS M',
        description: 'typography l body-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xs.normal',
        tags: ['screen-l', 'body', 'xs', 'normal'],
        displayName: 'bodyXs N',
        description: 'typography l body-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xs.bold',
        tags: ['screen-l', 'body', 'xs', 'bold'],
        displayName: 'bodyXs B',
        description: 'typography l body-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xs.medium',
        tags: ['screen-l', 'body', 'xs', 'medium'],
        displayName: 'bodyXs M',
        description: 'typography l body-xs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xxs.normal',
        tags: ['screen-l', 'body', 'xxs', 'normal'],
        displayName: 'bodyXxs N',
        description: 'typography l body-xxs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xxs.bold',
        tags: ['screen-l', 'body', 'xxs', 'bold'],
        displayName: 'bodyXxs B',
        description: 'typography l body-xxs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.body.xxs.medium',
        tags: ['screen-l', 'body', 'xxs', 'medium'],
        displayName: 'bodyXxs M',
        description: 'typography l body-xxs-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.l.normal',
        tags: ['screen-l', 'text', 'l', 'normal'],
        displayName: 'textL N',
        description: 'typography l text-l',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.l.bold',
        tags: ['screen-l', 'text', 'l', 'bold'],
        displayName: 'textL B',
        description: 'typography l text-l-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.l.medium',
        tags: ['screen-l', 'text', 'l', 'medium'],
        displayName: 'textL M',
        description: 'typography l text-l-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.m.normal',
        tags: ['screen-l', 'text', 'm', 'normal'],
        displayName: 'textM N',
        description: 'typography l text-m',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.m.bold',
        tags: ['screen-l', 'text', 'm', 'bold'],
        displayName: 'textM B',
        description: 'typography l text-m-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.m.medium',
        tags: ['screen-l', 'text', 'm', 'medium'],
        displayName: 'textM M',
        description: 'typography l text-m-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.s.normal',
        tags: ['screen-l', 'text', 's', 'normal'],
        displayName: 'textS N',
        description: 'typography l text-s',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.s.bold',
        tags: ['screen-l', 'text', 's', 'bold'],
        displayName: 'textS B',
        description: 'typography l text-s-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.s.medium',
        tags: ['screen-l', 'text', 's', 'medium'],
        displayName: 'textS M',
        description: 'typography l text-s-medium',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.xs.normal',
        tags: ['screen-l', 'text', 'xs', 'normal'],
        displayName: 'textXs N',
        description: 'typography l text-xs',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.xs.bold',
        tags: ['screen-l', 'text', 'xs', 'bold'],
        displayName: 'textXs B',
        description: 'typography l text-xs-bold',
        enabled: true,
    },
    {
        type: 'typography',
        name: 'screen-l.text.xs.medium',
        tags: ['screen-l', 'text', 'xs', 'medium'],
        displayName: 'textXs M',
        description: 'typography l text-xs-medium',
        enabled: true,
    },
];
