ktor:
    application:
        modules:
            - com.dsbuilder.publisher.app.ApplicationKt.module
    deployment:
        port: 8081

r2dbc:
    url: ${DBC_URL}
    username: ${DBC_USERNAME}
    password: ${DBC_PASSWORD}
    pool:
        maxSize: 10
        initialSize: 2