import type { PropertySeed } from '../../component-seed';

export const properties: PropertySeed[] = [
    { name: 'disabledAlpha', type: 'float', params: { web: ['disabledOpacity'] } },
    { name: 'rangeValueBottomOffset', type: 'dimension', variations: ['size'], params: { web: ['rangeValueBottomOffset'] } },
    { name: 'rangeValueHorizontalMargin', type: 'dimension', variations: ['size'], params: { web: ['rangeValueHorizontalMargin'] } },
    { name: 'rangeValueHorizontalOffset', type: 'dimension', variations: ['size'], params: { web: ['rangeValueHorizontalOffset'] } },
    { name: 'textFieldWebClipPath', type: 'color', variations: ['size'], params: { web: ['textFieldWebClipPath'] } },
    { name: 'labelWrapperMarginBottom', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperMarginBottom'] } },
    { name: 'labelWrapperMarginRight', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperMarginRight'] } },
    { name: 'labelWrapperOnlyIconMarginRight', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperOnlyIconMarginRight'] } },
    { name: 'labelWrapperVerticalMargin', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperVerticalMargin'] } },
    { name: 'labelWrapperGap', type: 'dimension', variations: ['size'], params: { web: ['labelWrapperGap'] } },
    { name: 'thumbFocusBorderColor', type: 'color', variations: ['view'], params: { web: ['thumbFocusBorderColor'] } },
    { name: 'tickSize', type: 'dimension', variations: ['size'], params: { web: ['tickSize'] } },
    { name: 'tickDotFilledColor', type: 'color', variations: ['view'], params: { web: ['tickDotFilledColor'] } },
    { name: 'currentValueTopOffset', type: 'dimension', variations: ['size'], params: { web: ['currentValueTopOffset'] } },
    { name: 'railBackgroundColor', type: 'color', variations: ['view'], params: { web: ['railBackgroundColor'] } },
    { name: 'textFieldWebReversedClipPath', type: 'color', variations: ['size'], params: { web: ['textFieldWebReversedClipPath'] } },
    { name: 'textFieldWebMarginRight', type: 'dimension', variations: ['size'], params: { web: ['textFieldWebMarginRight'] } },
    { name: 'thumbBorderRadius', type: 'shape', params: { web: ['thumbBorderRadius'] } },
    { name: 'tickSeparatorWidth', type: 'dimension', params: { web: ['tickSeparatorWidth'] } },
    { name: 'tickSeparatorHeight', type: 'dimension', params: { web: ['tickSeparatorHeight'] } },
    { name: 'tickSeparatorGap', type: 'dimension', params: { web: ['tickSeparatorGap'] } },
    { name: 'tickSeparatorBorderRadius', type: 'shape', params: { web: ['tickSeparatorBorderRadius'] } },
    { name: 'trackSegmentBorderRadius', type: 'shape', params: { web: ['trackSegmentBorderRadius'] } },
    { name: 'disabledBackgroundOpacity', type: 'float', params: { web: ['disabledBackgroundOpacity'] } },
    { name: 'disabledInnerContentOpacity', type: 'float', params: { web: ['disabledInnerContentOpacity'] } },
    { name: 'railBorderRadius', type: 'shape', variations: ['size'], params: { web: ['railBorderRadius'] } },
    { name: 'size', type: 'dimension', variations: ['size'], params: { web: ['size'] } },
    { name: 'textFieldWrapperGap', type: 'dimension', variations: ['size'], params: { web: ['textFieldWrapperGap'] } },
    { name: 'textFieldStyle', type: 'typography', variations: ['size'], params: { web: ['textFieldFontFamily', 'textFieldFontSize', 'textFieldFontStyle', 'textFieldFontWeight', 'textFieldLetterSpacing', 'textFieldLineHeight'] } },
    { name: 'valueStyle', type: 'typography', variations: ['size'], params: { web: ['valueFontFamily', 'valueFontSize', 'valueFontStyle', 'valueFontWeight', 'valueLetterSpacing', 'valueLineHeight'] } },
    { name: 'railThickness', type: 'dimension', variations: ['size'], params: { web: ['railThickness'] } },
    { name: 'textFieldHeight', type: 'dimension', variations: ['size'], params: { web: ['textFieldHeight'] } },
    { name: 'textFieldPadding', type: 'dimension', variations: ['size'], params: { web: ['textFieldPadding'] } },
    { name: 'textFieldBorderRadius', type: 'shape', variations: ['size'], params: { web: ['textFieldBorderRadius'] } },
    { name: 'textFieldPlaceholderColor', type: 'color', variations: ['view'], params: { web: ['textFieldPlaceholderColor'] } },
    { name: 'textFieldBackgroundColor', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundColor'] } },
    { name: 'textFieldBackgroundColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldBackgroundColorFocus'] } },
    { name: 'textFieldBorderWidth', type: 'dimension', variations: ['size'], params: { web: ['textFieldBorderWidth'] } },
    { name: 'textFieldBorderColor', type: 'color', variations: ['view'], params: { web: ['textFieldBorderColor'] } },
    { name: 'textFieldBorderColorFocus', type: 'color', variations: ['view'], params: { web: ['textFieldBorderColorFocus'] } },
    { name: 'labelStyle', type: 'typography', variations: ['size'], params: { web: ['labelFontFamily', 'labelFontSize', 'labelFontStyle', 'labelFontWeight', 'labelLetterSpacing', 'labelLineHeight'] } },
    { name: 'labelColor', type: 'color', variations: ['view'], params: { web: ['labelColor'] } },
    { name: 'rangeValueVerticalMargin', type: 'dimension', variations: ['size'], params: { web: ['rangeValueVerticalMargin'] } },
    { name: 'rangeValueColor', type: 'color', variations: ['view'], params: { web: ['rangeValueColor'] } },
    { name: 'doubleWrapperGap', type: 'dimension', variations: ['size'], params: { web: ['doubleWrapperGap'] } },
    { name: 'doubleBoxShadow', type: 'shadow', variations: ['view'], params: { web: ['doubleBoxShadow'] } },
    { name: 'thumbSize', type: 'dimension', variations: ['pointerSize'], params: { web: ['thumbWidth'] } },
    { name: 'thumbBorderWidth', type: 'dimension', variations: ['pointerSize'], params: { web: ['thumbBorderWidth'] } },
    { name: 'thumbBorderColor', type: 'color', variations: ['view'], params: { web: ['thumbBorderColor'] } },
    { name: 'thumbBackgroundColor', type: 'color', variations: ['view'], params: { web: ['thumbBackgroundColor'] } },
    { name: 'fillColor', type: 'color', variations: ['view'], params: { web: ['fillColor'] } },
    { name: 'tickDotColor', type: 'color', variations: ['view'], params: { web: ['tickDotColor'] } },
    { name: 'textFieldColor', type: 'color', variations: ['view'], params: { web: ['textFieldColor'] } },
    { name: 'textFiledFocusColor', type: 'color', variations: ['view'], params: { web: ['textFiledFocusColor'] } },
    { name: 'textFieldCaretColor', type: 'color', variations: ['view'], params: { web: ['textFieldCaretColor'] } },
];
