import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    size: {
        s: [
            { prop: 'currentValueTopOffset', value: '20' },
            { prop: 'labelStyle', value: 'body.s.normal' },
            { prop: 'labelWrapperMarginBottom', value: '4' },
            { prop: 'labelWrapperOnlyIconMarginRight', value: '10' },
            { prop: 'railBorderRadius', token: 'round.xxs' },
            { prop: 'rangeValueBottomOffset', value: '10' },
            { prop: 'rangeValueHorizontalOffset', value: '10' },
            { prop: 'size', value: '16' },
            { prop: 'textFieldHeight', value: '40' },
            { prop: 'textFieldStyle', value: 'body.s.normal' },
            { prop: 'tickSize', value: '8' },
            { prop: 'doubleWrapperGap', value: '6' },
            { prop: 'labelWrapperGap', value: '4' },
            { prop: 'labelWrapperMarginRight', value: '16' },
            { prop: 'labelWrapperVerticalMargin', value: '10' },
            { prop: 'railThickness', value: '4' },
            { prop: 'rangeValueHorizontalMargin', value: '8' },
            { prop: 'rangeValueVerticalMargin', value: '8' },
            { prop: 'textFieldBorderRadius', token: 'round.xxs' },
            { prop: 'textFieldPadding', value: '8' },
            { prop: 'textFieldWrapperGap', value: '2' },
            { prop: 'valueStyle', value: 'body.xs.normal' },
        ],
        l: [
            { prop: 'doubleWrapperGap', value: '6' },
            { prop: 'labelWrapperGap', value: '4' },
            { prop: 'labelWrapperMarginRight', value: '16' },
            { prop: 'labelWrapperVerticalMargin', value: '16' },
            { prop: 'railThickness', value: '4' },
            { prop: 'currentValueTopOffset', value: '26' },
            { prop: 'labelStyle', value: 'body.l.normal' },
            { prop: 'labelWrapperMarginBottom', value: '4' },
            { prop: 'labelWrapperOnlyIconMarginRight', value: '10' },
            { prop: 'railBorderRadius', token: 'round.xxs' },
            { prop: 'rangeValueBottomOffset', value: '14' },
            { prop: 'rangeValueHorizontalOffset', value: '14' },
            { prop: 'size', value: '24' },
            { prop: 'textFieldHeight', value: '56' },
            { prop: 'textFieldStyle', value: 'body.l.normal' },
            { prop: 'tickSize', value: '8' },
            { prop: 'rangeValueHorizontalMargin', value: '12' },
            { prop: 'rangeValueVerticalMargin', value: '12' },
            { prop: 'textFieldBorderRadius', token: 'round.m' },
            { prop: 'textFieldPadding', value: '20' },
            { prop: 'textFieldWrapperGap', value: '2' },
            { prop: 'valueStyle', value: 'body.m.normal' },
        ],
        m: [
            { prop: 'currentValueTopOffset', value: '28' },
            { prop: 'labelStyle', value: 'body.m.normal' },
            { prop: 'labelWrapperMarginBottom', value: '4' },
            { prop: 'labelWrapperOnlyIconMarginRight', value: '10' },
            { prop: 'railBorderRadius', token: 'round.xxs' },
            { prop: 'rangeValueBottomOffset', value: '12' },
            { prop: 'rangeValueHorizontalOffset', value: '14' },
            { prop: 'size', value: '24' },
            { prop: 'textFieldHeight', value: '48' },
            { prop: 'textFieldStyle', value: 'body.m.normal' },
            { prop: 'tickSize', value: '8' },
            { prop: 'doubleWrapperGap', value: '6' },
            { prop: 'labelWrapperGap', value: '4' },
            { prop: 'labelWrapperMarginRight', value: '16' },
            { prop: 'labelWrapperVerticalMargin', value: '12' },
            { prop: 'railThickness', value: '4' },
            { prop: 'rangeValueHorizontalMargin', value: '12' },
            { prop: 'rangeValueVerticalMargin', value: '10' },
            { prop: 'textFieldBorderRadius', token: 'round.m' },
            { prop: 'textFieldPadding', value: '14' },
            { prop: 'textFieldWrapperGap', value: '2' },
            { prop: 'valueStyle', value: 'body.s.normal' },
        ],
    },
    pointerSize: {
        none: [
            { prop: 'thumbSize', value: '0' },
        ],
        small: [
            { prop: 'thumbSize', value: '16' },
            { prop: 'thumbBorderWidth', value: '1' },
        ],
        large: [
            { prop: 'thumbBorderWidth', value: '1' },
            { prop: 'thumbSize', value: '20' },
        ],
    },
    view: {
        default: [
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'rangeValueColor', token: 'text.default.secondary' },
            { prop: 'textFieldCaretColor', token: 'text.default.accent' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'thumbBackgroundColor', token: 'surface.on-light.solid-card' },
            { prop: 'thumbFocusBorderColor', token: 'surface.default.solid-default' },
            { prop: 'tickDotFilledColor', token: 'surface.default.solid-default' },
            { prop: 'fillColor', token: 'surface.default.solid-default' },
            { prop: 'railBackgroundColor', token: 'surface.default.solid-tertiary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-primary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'textFieldBackgroundColor', value: 'surface.default.transparent-primary-hover' }] },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFiledFocusColor', token: 'text.default.primary' },
            { prop: 'thumbBorderColor', token: 'surface.default.solid-tertiary' },
            { prop: 'tickDotColor', token: 'surface.default.solid-tertiary' },
        ],
        accent: [
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'rangeValueColor', token: 'text.default.secondary' },
            { prop: 'textFieldCaretColor', token: 'text.default.accent' },
            { prop: 'textFieldPlaceholderColor', token: 'text.default.secondary' },
            { prop: 'thumbBackgroundColor', token: 'surface.on-light.solid-card' },
            { prop: 'thumbFocusBorderColor', token: 'surface.default.accent' },
            { prop: 'tickDotFilledColor', token: 'surface.default.accent' },
            { prop: 'fillColor', token: 'surface.default.accent' },
            { prop: 'railBackgroundColor', token: 'surface.default.solid-tertiary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-primary' },
            { prop: 'textFieldBackgroundColor', token: 'surface.default.transparent-primary-hover', state: 'hovered', adjust: [{ platform: 'web', param: 'textFieldBackgroundColor', value: 'surface.default.transparent-primary-hover' }] },
            { prop: 'textFieldBackgroundColorFocus', token: 'surface.default.transparent-secondary' },
            { prop: 'textFieldColor', token: 'text.default.primary' },
            { prop: 'textFiledFocusColor', token: 'text.default.primary' },
            { prop: 'thumbBorderColor', token: 'surface.default.solid-tertiary' },
            { prop: 'tickDotColor', token: 'surface.default.solid-tertiary' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disabledAlpha', value: '1' },
];
