name: Deploy design-system-builder

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/prepare-environment

      - name: Prepare directory build
        run: mkdir -p s3_build

      # TODO: https://github.com/salute-developers/plasma/issues/255
      - name: Npm install
        run: | 
          npm install --prefix="./client"

      # 2 папки, так как названия разные - в первом случае нужно для replace
      - name: Build Design System Builder Builder
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build --prefix="./client"
          cp -R ./client/dist ./s3_build/design-system-builder-next

      - name: Install s3cmd
        run: |
          pip3 install s3cmd

      - name: s3 Upload build
        run: >
          s3cmd
          --access_key ${{ secrets.AWS_ACCESS_KEY_ID }}
          --secret_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          --host ${{ secrets.AWS_ENDPOINT }}
          --host-bucket ${{ secrets.AWS_ENDPOINT }}
          --bucket-location ${{ secrets.AWS_REGION }}
          --signature-v2
          --delete-removed
          --no-mime-magic
          sync
          ./s3_build/design-system-builder-next/
          s3://${{ secrets.AWS_S3_BUCKET_2 }}/design-system-builder/
