import type { ValueSeed, ValuesSeed } from '../../component-seed';

export const values: ValuesSeed = {
    view: {
        default: [
            { prop: 'backgroundColor', token: 'surface.default.solid-default' },
            { prop: 'backgroundColor', token: 'surface.default.solid-default-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.solid-default-hover' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.solid-default-hover' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.solid-default-hover' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.solid-default-hover' }] },
            { prop: 'iconColor', token: 'text.inverse.primary' },
            { prop: 'iconColor', token: 'text.inverse.primary', state: 'pressed', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'text.inverse.primary' }, { platform: 'compose', param: 'iconColor', value: 'text.inverse.primary' }, { platform: 'ios', param: 'iconColor', value: 'text.inverse.primary' }] },
            { prop: 'loadingBackgroundColor', token: 'surface.default.solid-default' },
            { prop: 'backgroundColor', token: 'surface.default.solid-default-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.solid-default-active' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.solid-default-active' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.solid-default-active' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.solid-default-active' }] },
            { prop: 'iconColor', token: 'text.inverse.primary', state: 'hovered', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'text.inverse.primary' }, { platform: 'compose', param: 'iconColor', value: 'text.inverse.primary' }, { platform: 'ios', param: 'iconColor', value: 'text.inverse.primary' }] },
            { prop: 'labelColor', token: 'text.inverse.primary' },
            { prop: 'spinnerColor', token: 'text.inverse.primary' },
            { prop: 'valueColor', token: 'text.inverse.secondary' },
        ],
        secondary: [
            { prop: 'backgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-secondary-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.transparent-secondary-active' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.transparent-secondary-active' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.transparent-secondary-active' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.transparent-secondary-active' }] },
            { prop: 'iconColor', token: 'text.default.primary-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'text.default.primary-hover' }, { platform: 'compose', param: 'iconColor', value: 'text.default.primary-hover' }, { platform: 'ios', param: 'iconColor', value: 'text.default.primary-hover' }] },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.primary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-secondary-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.transparent-secondary-hover' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.transparent-secondary-hover' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.transparent-secondary-hover' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.transparent-secondary-hover' }] },
            { prop: 'iconColor', token: 'text.default.primary' },
            { prop: 'iconColor', token: 'text.default.primary-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'text.default.primary-active' }, { platform: 'compose', param: 'iconColor', value: 'text.default.primary-active' }, { platform: 'ios', param: 'iconColor', value: 'text.default.primary-active' }] },
            { prop: 'loadingBackgroundColor', token: 'surface.default.transparent-secondary' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
        accent: [
            { prop: 'backgroundColor', token: 'surface.default.accent' },
            { prop: 'backgroundColor', token: 'surface.default.accent-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.accent-active' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.accent-active' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.accent-active' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.accent-active' }] },
            { prop: 'iconColor', token: 'surface.default.accent-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'surface.default.accent-hover' }, { platform: 'compose', param: 'iconColor', value: 'surface.default.accent-hover' }, { platform: 'ios', param: 'iconColor', value: 'surface.default.accent-hover' }] },
            { prop: 'labelColor', token: 'text.on-dark.primary' },
            { prop: 'spinnerColor', token: 'text.on-dark.primary' },
            { prop: 'backgroundColor', token: 'surface.default.accent-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.accent-hover' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.accent-hover' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.accent-hover' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.accent-hover' }] },
            { prop: 'iconColor', token: 'surface.default.accent' },
            { prop: 'iconColor', token: 'surface.default.accent-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'surface.default.accent-active' }, { platform: 'compose', param: 'iconColor', value: 'surface.default.accent-active' }, { platform: 'ios', param: 'iconColor', value: 'surface.default.accent-active' }] },
            { prop: 'loadingBackgroundColor', token: 'surface.default.accent' },
            { prop: 'valueColor', token: 'text.on-dark.secondary' },
        ],
        clear: [
            { prop: 'backgroundColor', token: 'surface.default.clear' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-secondary-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.transparent-secondary-active' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.transparent-secondary-active' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.transparent-secondary-active' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.transparent-secondary-active' }] },
            { prop: 'iconColor', token: 'text.default.primary-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'text.default.primary-hover' }, { platform: 'compose', param: 'iconColor', value: 'text.default.primary-hover' }, { platform: 'ios', param: 'iconColor', value: 'text.default.primary-hover' }] },
            { prop: 'labelColor', token: 'text.default.primary' },
            { prop: 'spinnerColor', token: 'text.default.primary' },
            { prop: 'backgroundColor', token: 'surface.default.transparent-secondary-hover', state: 'hovered', adjust: [{ platform: 'xml', param: 'backgroundTint', value: 'surface.default.transparent-secondary-hover' }, { platform: 'compose', param: 'backgroundColor', value: 'surface.default.transparent-secondary-hover' }, { platform: 'ios', param: 'backgroundColor', value: 'surface.default.transparent-secondary-hover' }, { platform: 'web', param: 'buttonBackgroundColor', value: 'surface.default.transparent-secondary-hover' }] },
            { prop: 'iconColor', token: 'text.default.primary' },
            { prop: 'iconColor', token: 'text.default.primary-active', state: 'pressed', adjust: [{ platform: 'xml', param: 'sd_iconTint', value: 'text.default.primary-active' }, { platform: 'compose', param: 'iconColor', value: 'text.default.primary-active' }, { platform: 'ios', param: 'iconColor', value: 'text.default.primary-active' }] },
            { prop: 'loadingBackgroundColor', token: 'surface.default.clear' },
            { prop: 'valueColor', token: 'text.default.secondary' },
        ],
    },
    size: {
        xl: [
            { prop: 'height', value: '64' },
            { prop: 'labelStyle', value: 'body.l.bold' },
            { prop: 'paddingEnd', value: '28' },
            { prop: 'shape', token: 'round.l' },
            { prop: 'spinnerStrokeWidth', value: '2' },
            { prop: 'iconMargin', value: '10', adjust: [{ platform: 'web', param: 'buttonLeftContentMargin', template: '0 $1 -0.125rem' }, { platform: 'web', param: 'buttonRightContentMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'iconSize', value: '24' },
            { prop: 'minWidth', value: '200' },
            { prop: 'paddingStart', value: '28' },
            { prop: 'spinnerSize', value: '24' },
            { prop: 'valueMargin', value: '2', adjust: [{ platform: 'web', param: 'buttonValueMargin', template: '0 0 0 $1' }] },
            { prop: 'valueStyle', value: 'body.l.bold' },
        ],
        l: [
            { prop: 'height', value: '56' },
            { prop: 'labelStyle', value: 'body.l.bold' },
            { prop: 'paddingEnd', value: '24' },
            { prop: 'shape', token: 'round.l', adjust: [{ platform: 'xml', param: 'sd_shapeAppearance', value: '-2' }, { platform: 'compose', param: 'shape', value: '-2' }, { platform: 'ios', param: 'cornerRadius', value: '-2' }, { platform: 'web', param: 'buttonRadius', value: '-2' }] },
            { prop: 'spinnerSize', value: '22' },
            { prop: 'valueMargin', value: '2', adjust: [{ platform: 'web', param: 'buttonValueMargin', template: '0 0 0 $1' }] },
            { prop: 'valueStyle', value: 'body.l.bold' },
            { prop: 'iconMargin', value: '8', adjust: [{ platform: 'web', param: 'buttonLeftContentMargin', template: '0 $1 -0.125rem' }, { platform: 'web', param: 'buttonRightContentMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'iconSize', value: '22' },
            { prop: 'minWidth', value: '200' },
            { prop: 'paddingStart', value: '24' },
            { prop: 'spinnerStrokeWidth', value: '2' },
        ],
        m: [
            { prop: 'iconMargin', value: '6', adjust: [{ platform: 'web', param: 'buttonLeftContentMargin', template: '0 $1 -0.125rem' }, { platform: 'web', param: 'buttonRightContentMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'iconSize', value: '22' },
            { prop: 'minWidth', value: '180' },
            { prop: 'paddingStart', value: '20' },
            { prop: 'spinnerSize', value: '22' },
            { prop: 'valueMargin', value: '2', adjust: [{ platform: 'web', param: 'buttonValueMargin', template: '0 0 0 $1' }] },
            { prop: 'valueStyle', value: 'body.m.bold' },
            { prop: 'height', value: '48' },
            { prop: 'labelStyle', value: 'body.m.bold' },
            { prop: 'paddingEnd', value: '20' },
            { prop: 'shape', token: 'round.m' },
            { prop: 'spinnerStrokeWidth', value: '2' },
        ],
        xs: [
            { prop: 'height', value: '32' },
            { prop: 'labelStyle', value: 'body.xs.bold' },
            { prop: 'paddingEnd', value: '12' },
            { prop: 'shape', token: 'round.s' },
            { prop: 'spinnerStrokeWidth', value: '2' },
            { prop: 'iconMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonLeftContentMargin', template: '0 $1 -0.125rem' }, { platform: 'web', param: 'buttonRightContentMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'iconSize', value: '16' },
            { prop: 'minWidth', value: '160' },
            { prop: 'paddingStart', value: '12' },
            { prop: 'spinnerSize', value: '16' },
            { prop: 'valueMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonValueMargin', template: '0 0 0 $1' }] },
            { prop: 'valueStyle', value: 'body.xs.bold' },
        ],
        s: [
            { prop: 'iconMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonLeftContentMargin', template: '0 $1 -0.125rem' }, { platform: 'web', param: 'buttonRightContentMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'iconSize', value: '22' },
            { prop: 'minWidth', value: '180' },
            { prop: 'paddingStart', value: '16' },
            { prop: 'spinnerStrokeWidth', value: '2' },
            { prop: 'height', value: '40' },
            { prop: 'labelStyle', value: 'body.s.bold' },
            { prop: 'paddingEnd', value: '16' },
            { prop: 'spinnerSize', value: '22' },
            { prop: 'valueMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonValueMargin', template: '0 0 0 $1' }] },
            { prop: 'valueStyle', value: 'body.s.bold' },
        ],
        xxs: [
            { prop: 'height', value: '24' },
            { prop: 'labelStyle', value: 'body.xs.bold' },
            { prop: 'paddingEnd', value: '10' },
            { prop: 'shape', token: 'round.xs' },
            { prop: 'spinnerStrokeWidth', value: '2' },
            { prop: 'iconMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonLeftContentMargin', template: '0 $1 -0.125rem' }, { platform: 'web', param: 'buttonRightContentMargin', template: '0 -0.125rem 0 $1' }] },
            { prop: 'iconSize', value: '16' },
            { prop: 'minWidth', value: '140' },
            { prop: 'paddingStart', value: '10' },
            { prop: 'spinnerSize', value: '12' },
            { prop: 'valueMargin', value: '4', adjust: [{ platform: 'web', param: 'buttonValueMargin', template: '0 0 0 $1' }] },
            { prop: 'valueStyle', value: 'body.xs.bold' },
        ],
    },
    shape: {
        pilled: [
            { prop: 'shape', token: 'round.circle' },
        ],
    },
};

export const invariants: ValueSeed[] = [
    { prop: 'disableAlpha', value: '0.4' },
    { prop: 'loadingAlpha', value: '0' },
    { prop: 'focusColor', token: 'text.default.accent' },
];
